import { createFileRoute, Link } from "@tanstack/react-router";
import { Camera, Check, ChevronLeft, ChevronRight, Coffee, Droplet, Moon, Plus, Trash2, Utensils } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/wk/shell";
import { Action, DataRow, EmptyState, Metric, Panel, PageHeader, ProgressIndicator, SectionHeader, StatusIndicator, Timeline } from "@/components/wk/ui";
import { apiDeleteDiary, apiDiary, apiStatsToday, todayISO, type DiaryItem, type TodayStats } from "@/lib/api";

export const Route=createFileRoute("/diary")({head:()=>({meta:[{title:"Diary — WK Health"},{name:"description",content:"Live food diary and nutrition ledger."}]}),component:DiaryPage});

function DiaryPage(){
 const [date,setDate]=useState(todayISO());
 const [items,setItems]=useState<DiaryItem[]>([]);
 const [stats,setStats]=useState<TodayStats|null>(null);
 const [loading,setLoading]=useState(true);
 const [busyId,setBusyId]=useState("");
 const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[d,s]=await Promise.all([apiDiary(date),apiStatsToday()]);setItems(d);setStats(s)}catch(e){setError(e instanceof Error?e.message:"โหลดไดอารี่ไม่สำเร็จ")}finally{setLoading(false)}},[date]);
 useEffect(()=>{void load()},[load]);
 const grouped=useMemo(()=>{const groups=new Map<string,DiaryItem[]>();for(const item of items){const key=item.slot||"อื่น ๆ";groups.set(key,[...(groups.get(key)??[]),item])}return Array.from(groups.entries())},[items]);
 const consumed=items.reduce((a,x)=>a+x.kcal,0),protein=items.reduce((a,x)=>a+x.protein,0),carb=items.reduce((a,x)=>a+x.carb,0),fat=items.reduce((a,x)=>a+x.fat,0);
 const remove=async(id:string)=>{setBusyId(id);setError("");try{await apiDeleteDiary(id);await load()}catch(e){setError(e instanceof Error?e.message:"ลบรายการไม่สำเร็จ")}finally{setBusyId("")}};
 const shift=(delta:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+delta);setDate(todayISO(d))};
 return <AppShell title="Diary"><PageHeader eyebrow="Today / Diary" title="Today, written down." description="ไดอารี่จากข้อมูลจริงของบัญชีเดียวกับ WK Health" actions={<div className="flex items-center gap-2"><StatusIndicator label={loading?"SYNCING":"LIVE"} state={loading?"live":error?"warn":"live"}/><Link to="/scan"><Action icon={Camera} variant="outline">Scan meal</Action></Link><Link to="/scan"><Action icon={Plus} variant="solid">New entry</Action></Link></div>}/>
 <div className="flex items-center justify-between hairline-b py-4"><Action icon={ChevronLeft} size="sm" onClick={()=>shift(-1)} aria-label="Previous day"/><div className="text-center"><p className="label-xs">Diary date</p><p className="num mt-2 text-sm">{date===todayISO()?"Today":new Date(`${date}T12:00:00`).toLocaleDateString("th-TH",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}</p></div><Action icon={ChevronRight} size="sm" onClick={()=>shift(1)} aria-label="Next day"/></div>
 {error?<Panel className="mt-8 border-destructive/30"><p className="text-sm text-destructive">{error}</p><p className="mt-1 text-xs text-muted-foreground">ตรวจสอบ session และ backend แล้วลอง Sync อีกครั้ง</p></Panel>:null}
 <div className="grid gap-8 py-10 lg:grid-cols-[1.4fr_1fr]"><div className="space-y-10"><div><SectionHeader title="Meals" meta={`${items.length} entries`}/>{loading?<Panel bare><div className="py-14 text-center text-sm text-muted-foreground">กำลังซิงก์ข้อมูล…</div></Panel>:grouped.length===0?<Panel bare><EmptyState label="No entries yet" body="เริ่มจาก Scan meal หรือเพิ่มรายการผ่านระบบที่เชื่อมกับ backend" action={<Link to="/scan"><Action icon={Camera} variant="outline">Scan a meal</Action></Link>}/></Panel>:grouped.map(([slot,list])=><div key={slot} className="mb-7"><SectionHeader title={slot} meta={`${list.reduce((a,x)=>a+x.kcal,0).toLocaleString("th-TH")} kcal`}/><Panel bare className="px-5 py-2">{list.map((it)=><DataRow key={it.id} label={it.name} meta={`${it.time||"—"} · ${it.source}`} value={`${it.kcal.toLocaleString("th-TH")} kcal`} icon={slot.toLowerCase().includes("break")?<Coffee/>:<Utensils/>} right={<Action icon={busyId===it.id?Check:Trash2} size="sm" variant="ghost" onClick={()=>void remove(it.id)} disabled={!it.id||busyId===it.id} aria-label={`Delete ${it.name}`}/>} />)}</Panel></div>)}</div><div><SectionHeader title="Day timeline" meta={`${items.length} events`}/><Panel bare className="px-5 py-6">{items.length?<Timeline items={items.slice().sort((a,b)=>a.time.localeCompare(b.time)).map((x,i)=>({time:x.time||"—",title:x.name,detail:`${x.kcal} kcal · P ${x.protein} g · C ${x.carb} g · F ${x.fat} g`,state:i===items.length-1?"active":"done"}))}/>:<EmptyState label="No timeline" body="ข้อมูลที่บันทึกวันนี้จะปรากฏตรงนี้"/>}</Panel></div></div>
 <aside className="space-y-8"><Panel title="Energy ledger" meta="LIVE"><Metric label="Consumed" value={consumed.toLocaleString("th-TH")} unit="kcal" size="lg" footnote={`Target ${stats?.goal?.toLocaleString("th-TH")??"—"} kcal`}/><div className="mt-7 space-y-5"><ProgressIndicator label={`Protein ${Math.round(protein)} g`} right={`${Math.min(100,Math.round((protein/Math.max(stats?.proteinGoal??1,1))*100))}%`} value={(protein/Math.max(stats?.proteinGoal??1,1))*100}/><ProgressIndicator label={`Carbs ${Math.round(carb)} g`} right={`${Math.min(100,Math.round((carb/Math.max(stats?.carbGoal??1,1))*100))}%`} value={(carb/Math.max(stats?.carbGoal??1,1))*100}/><ProgressIndicator label={`Fat ${Math.round(fat)} g`} right={`${Math.min(100,Math.round((fat/Math.max(stats?.fatGoal??1,1))*100))}%`} value={(fat/Math.max(stats?.fatGoal??1,1))*100}/></div></Panel><Panel title="Hydration" bare><div className="p-5"><div className="flex gap-1.5">{Array.from({length:stats?.waterGoal??8},(_,i)=><span key={i} className={`h-10 flex-1 border ${i<(stats?.water??0)?"border-transparent bg-foreground":"border-border bg-transparent"}`}/>)}</div><div className="mt-4 flex items-center justify-between"><span className="num text-[11px] text-muted-foreground">{stats?.water??0} of {stats?.waterGoal??8} glasses</span><Link to="/"><Action icon={Droplet} size="sm" variant="outline">Add</Action></Link></div></div></Panel><Panel title="Sleep" bare><div className="px-5 py-2"><DataRow label="Sleep data" value="—" icon={Moon} meta="not provided by diary API"/></div></Panel><Panel title="Sync status" bare><div className="px-5 py-2"><DataRow label="Backend" value={loading?"Syncing":"Live"}/><DataRow label="Date" value={date}/><DataRow label="Entries" value={String(items.length)}/><div className="py-3"><Action className="w-full" variant="outline" onClick={()=>void load()}>Sync again</Action></div></div></Panel></aside></div></AppShell>
}
