import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Copy, Heart, Loader2, Share2, Flame, UserPlus, Users } from "lucide-react";
import { AppShell } from "@/components/app/app-shell";
import { Chip, Eyebrow, Panel, SectionHeader, SuccessState } from "@/components/app/lovable-primitives";
import { ErrorState, Skeleton } from "@/components/app/states";
import { useAuth } from "@/lib/auth";
import { apiFriendsList, apiFriendsCheer, apiFriendsInviteCode, apiFriendsAdd, apiStatsWeekSummary } from "@/lib/api-new-features";
import { renderWeekShareImage, shareOrDownloadImage } from "@/lib/share-image";

export const Route = createFileRoute("/friends")({ head: () => ({ meta: [{ title: "Friends — WK Health" }, { name: "description", content: "สังคมสุขภาพที่แชร์เฉพาะสัญญาณที่คุณเลือก" }] }), component: FriendsPage });

function FriendsPage() {
  const { isAuthenticated } = useAuth(); const qc = useQueryClient(); const [code,setCode]=useState(""); const [shareResult,setShareResult]=useState<"shared"|"downloaded"|null>(null);
  const friends=useQuery({queryKey:["friends","list"],queryFn:apiFriendsList,enabled:isAuthenticated}); const invite=useQuery({queryKey:["friends","invite"],queryFn:apiFriendsInviteCode,enabled:isAuthenticated}); const week=useQuery({queryKey:["stats","week-summary"],queryFn:apiStatsWeekSummary,enabled:isAuthenticated});
  const cheer=useMutation({mutationFn:apiFriendsCheer,onSuccess:()=>void qc.invalidateQueries({queryKey:["friends","list"]})});
  const addFriend=useMutation({mutationFn:()=>apiFriendsAdd(code),onSuccess:()=>{setCode("");void qc.invalidateQueries({queryKey:["friends","list"]})}});
  const share=useMutation({mutationFn:async()=>{const blob=await renderWeekShareImage({streak:week.data?.streak??0,avgKcal:week.data?.avgKcal??0,daysOnGoal:week.data?.daysOnGoal??0});return shareOrDownloadImage(blob,`wk-health-week-summary-${new Date().toISOString().slice(0,10)}.png`)},onSuccess:(result)=>{if(result!=="cancelled"){setShareResult(result);setTimeout(()=>setShareResult(null),3000)}}});
  const sorted=[...(friends.data??[])].sort((a,b)=>b.streak-a.streak);

  return <AppShell><div className="rise-in pb-10">
    <header className="border-b border-border py-7 sm:py-9"><div className="flex flex-wrap items-end justify-between gap-5"><div><Eyebrow>Social layer</Eyebrow><h1 className="display mt-2 text-3xl sm:text-4xl">Friends</h1><p className="mt-2 text-sm text-muted-foreground">แชร์แรงส่งและกิจกรรม โดยไม่เปิดเผยข้อมูลสุขภาพดิบ</p></div><Chip tone="signal">Private by design</Chip></div></header>
    <section className="grid gap-6 py-7 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,.8fr)]">
      <Panel className="grain flex flex-col justify-between gap-8"><div><div className="flex items-center justify-between gap-4"><Eyebrow>Weekly summary</Eyebrow><button onClick={()=>share.mutate()} disabled={share.isPending||week.isLoading} aria-label="Share weekly summary" className="press grid size-10 place-items-center rounded-xl border border-border disabled:opacity-50">{share.isPending?<Loader2 className="size-4 animate-spin"/>:<Share2 className="size-4"/>}</button></div>{week.isLoading?<Skeleton className="mt-5 h-20 w-full rounded-2xl"/>:week.isError?<div className="mt-4"><ErrorState error={week.error} onRetry={()=>void week.refetch()}/></div>:<><p className="numeric mt-4 text-6xl font-medium">{week.data?.streak??0}<span className="ml-2 text-base font-normal text-muted-foreground">day streak</span></p><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3"><Stat label="Avg kcal" value={week.data?.avgKcal??0}/><Stat label="Days on goal" value={`${week.data?.daysOnGoal??0}/7`}/><Stat label="Share" value="Ready"/></div></>}{shareResult?<div className="mt-5"><SuccessState title={shareResult==="shared"?"Shared successfully":"Saved to device"} body="Weekly summary is ready to share."/></div>:null}</div></Panel>
      <Panel><Eyebrow>Your circle</Eyebrow><p className="display mt-2 text-2xl">Invite someone in</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Use a private invite code. Location and raw health metrics stay hidden unless explicitly shared.</p><div className="mt-6 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Invite code" className="min-h-11 min-w-0 flex-1 rounded-xl border border-border bg-surface-2 px-3 text-sm outline-none"/><button onClick={()=>code&&addFriend.mutate()} disabled={!code||addFriend.isPending} className="press flex min-h-11 items-center gap-2 rounded-xl bg-foreground px-4 text-sm text-background disabled:opacity-50">{addFriend.isPending?<Loader2 className="size-4 animate-spin"/>:<UserPlus className="size-4"/>}Add</button></div>{invite.data?.code?<button onClick={()=>void navigator.clipboard.writeText(invite.data!.code)} className="press mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-border text-xs text-muted-foreground"><Copy className="size-3.5"/>Your invite code <span className="font-semibold text-foreground">{invite.data.code}</span></button>:null}</Panel>
    </section>
    <section className="py-2"><SectionHeader eyebrow="Circle" title="Activity standing" action={<Chip>{sorted.length} people</Chip>}/><div className="mt-2 divide-y divide-border">{friends.isLoading?<div className="space-y-2 py-5"><Skeleton className="h-16 rounded-2xl"/><Skeleton className="h-16 rounded-2xl"/></div>:friends.isError?<ErrorState error={friends.error} onRetry={()=>void friends.refetch()}/>:sorted.length===0?<div className="py-12 text-center"><Users className="mx-auto size-5 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">No friends yet. Invite someone to start your shared streak.</p></div>:sorted.map((f,i)=><div key={f.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 py-5"><span className="numeric grid size-10 place-items-center rounded-full border border-border text-xs">#{i+1}</span><div className="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-3 min-w-0"><span className="numeric grid size-11 place-items-center rounded-full border border-border text-xs">{(f.name??"WK").slice(0,2).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{f.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Flame className="size-3"/>{f.streak} day streak</p></div></div><button onClick={()=>cheer.mutate(f.id)} disabled={cheer.isPending} className="press flex min-h-10 items-center gap-1.5 rounded-full border border-border px-3 text-xs"><Heart className="size-3.5"/>Cheer</button></div>)}</div></section>
  </div></AppShell>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div><Eyebrow>{label}</Eyebrow><p className="numeric mt-1.5 text-lg font-medium">{value}</p></div>}
