import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Camera, Footprints, HeartPulse, MessageSquare, Moon, Music, RefreshCw, Wallet } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/wk/shell";
import { Action, DataRow, Metric, Panel, PageHeader, ProgressIndicator, SectionHeader, StatusIndicator, Timeline } from "@/components/wk/ui";
import { apiFetch, apiStatsToday, apiStatsWeekly, todayISO, type TodayStats, type WeeklyPoint } from "@/lib/api";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "WK Health — Daily Overview" }, { name: "description", content: "Live WK Health daily overview." }] }), component: Overview });
type Json=Record<string,unknown>;
function Ring({value,label,subtone="ink"}:{value:number;label:string;subtone?:"ink"|"signal"}){const r=39,c=2*Math.PI*r,p=Math.min(100,Math.max(0,value));return <div className="relative size-28 shrink-0"><svg viewBox="0 0 100 100" className="size-full -rotate-90"><circle cx="50" cy="50" r={r} fill="none" stroke="currentColor" strokeOpacity=".08" strokeWidth="7"/><circle cx="50" cy="50" r={r} fill="none" stroke="currentColor" strokeWidth="7" strokeDasharray={`${(p/100)*c} ${c}`} strokeLinecap="butt" className={subtone==="signal"?"text-signal":"text-foreground"}/></svg><div className="absolute inset-0 grid place-items-center"><span className="num text-lg">{Math.round(p)}%</span></div><span className="label-xs absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap">{label}</span></div>}
function Overview(){const[stats,setStats]=useState<TodayStats|null>(null),[week,setWeek]=useState<WeeklyPoint[]>([]),[diary,setDiary]=useState<Json[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{const[s,w,d]=await Promise.all([apiStatsToday(),apiStatsWeekly(),apiFetch<Json>(`/api/diary?date=${encodeURIComponent(todayISO())}`)]);setStats(s);setWeek(w);const list=d.entries??d.items??d.data??[];setDiary(Array.isArray(list)?list.filter(x=>x&&typeof x==="object") as Json[]:[])}catch(e){setError(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const goal=stats?.goal??0,eaten=stats?.eaten??0,steps=stats?.steps??0,stepGoal=stats?.stepGoal??10000,proteinPct=stats?.proteinGoal?((stats.protein??0)/stats.proteinGoal)*100:0,waterPct=stats?.waterGoal?((stats.water??0)/stats.waterGoal)*100:0,energyPct=goal?(eaten/goal)*100:0;const time=(x:Json)=>String(x.created_at??x.createdAt??x.time??"").slice(11,16)||"—";
return <AppShell title="Overview"><PageHeader eyebrow={new Date().toLocaleDateString("en-GB",{weekday:"long",day:"2-digit",month:"long"})} title="A steady day, held together." description="ภาพรวมสุขภาพของคุณจากข้อมูลจริงใน WK Health" actions={<div className="flex items-center gap-3"><StatusIndicator label={loading?"Syncing":"Synced"} state={loading?"live":"idle"}/><Action icon={RefreshCw} size="sm" onClick={()=>void load()} disabled={loading}/></div>}/>
<section className="hairline-b grid grid-cols-2 gap-y-10 py-10 sm:grid-cols-4"><Metric label="Steps" value={loading?"—":steps.toLocaleString("th-TH")} unit={`/ ${stepGoal.toLocaleString("th-TH")}`} size="lg" delta={steps>=stepGoal?"Goal":"Today"}/><Metric label="Energy" value={loading?"—":eaten.toLocaleString("th-TH")} unit="kcal" size="lg"/><Metric label="Resting HR" value={loading?"—":String(stats?.restingHr??"—")} unit="bpm" size="lg"/><Metric label="Sleep" value={loading?"—":String(stats?.sleep??"—")} unit="hrs" size="lg" delta={stats?.sleepDelta?String(stats.sleepDelta):undefined}/></section>
<div className="grid gap-8 py-10 lg:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div className="space-y-9"><div><SectionHeader title="Day so far" meta={new Date().toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})} actions={<Link to="/diary" className="num flex items-center gap-1 text-[10px] uppercase text-muted-foreground">Diary <ArrowUpRight className="size-3"/></Link>}/><Panel bare className="px-6 py-7">{loading?<p className="py-8 text-sm text-muted-foreground">กำลังซิงก์ข้อมูล…</p>:error?<p className="py-8 text-sm text-destructive">{error}</p>:diary.length===0?<p className="py-8 text-sm text-muted-foreground">ยังไม่มีรายการวันนี้ — ใช้ Quick capture เพื่อเริ่มบันทึก</p>:<Timeline items={diary.slice(0,7).map((x,i)=>({time:time(x),title:String(x.food_name??x.foodName??x.name??x.title??`รายการ ${i+1}`),detail:`${Number(x.calories??x.kcal??0)} kcal`,state:i===0?"active":"done"}))}/>}</Panel></div>
<div><SectionHeader title="Targets" meta="4 active"/><Panel className="flex flex-wrap items-center justify-between gap-8"><div className="flex gap-10 pl-2 py-2"><Ring value={energyPct} label="Energy"/><Ring value={waterPct} label="Hydration" subtone="signal"/><Ring value={proteinPct} label="Protein"/></div><div className="min-w-[220px] flex-1 space-y-5"><ProgressIndicator label="Movement" right={`${Math.min(100,Math.round((steps/Math.max(stepGoal,1))*100))}%`} value={Math.min(100,(steps/Math.max(stepGoal,1))*100)}/><ProgressIndicator label="Protein" right={`${Math.min(100,Math.round(proteinPct))}%`} value={proteinPct}/><ProgressIndicator label="Hydration" right={`${Math.min(100,Math.round(waterPct))}%`} value={waterPct} tone="signal"/><ProgressIndicator label="Energy" right={`${Math.min(100,Math.round(energyPct))}%`} value={energyPct}/></div></Panel></div>
<div><SectionHeader title="Recent days" meta={`${week.length} days`}/><Panel bare className="px-5 py-2">{week.length===0?<p className="py-6 text-sm text-muted-foreground">ยังไม่มีสถิติรายสัปดาห์</p>:week.slice(-7).map((d,i)=><DataRow key={`${d.day}-${i}`} label={d.day} value={`${d.kcal.toLocaleString("th-TH")} kcal`} meta={`${d.steps.toLocaleString("th-TH")} steps · ${d.burn.toLocaleString("th-TH")} burn`}/>)}</Panel></div></div>
<aside className="space-y-7"><Panel title="Quick capture" bare><div className="grid grid-cols-2">{[{to:"/scan",label:"Scan meal",icon:Camera},{to:"/pedometer",label:"Movement",icon:Footprints},{to:"/mood",label:"Mood check",icon:HeartPulse},{to:"/sound-control",label:"Sound",icon:Music}].map(a=><Link key={a.to} to={a.to} className="group hairline-b flex min-h-28 flex-col justify-between border-r border-hairline p-5 last:border-r-0 hover:bg-accent/50"><a.icon className="size-4 text-muted-foreground" strokeWidth={1.5}/><span className="flex items-center justify-between text-[12px]">{a.label}<ArrowUpRight className="size-3 opacity-0 group-hover:opacity-60"/></span></Link>)}</div></Panel><Panel tone="ink" className="border-transparent"><p className="label-xs opacity-60">WK HEALTH / LIVE</p><p className="display mt-5 text-3xl">Connected, not cluttered.</p><p className="mt-3 text-sm leading-6 opacity-65">ทุกข้อมูลในหน้านี้ผูกกับบัญชีและ backend เดียวกับระบบหลัก</p><div className="mt-8 flex items-center justify-between border-t border-white/15 pt-4"><StatusIndicator label="Backend connected" state="live"/><Action icon={RefreshCw} size="sm" variant="ghost" className="text-white/70 hover:text-white" onClick={()=>void load()} disabled={loading}/></div></Panel><Panel title="Recovery" bare><div className="px-5 py-2"><DataRow label="Sleep debt" value={text(stats?.sleepDebt)} icon={Moon}/><DataRow label="HRV" value={text(stats?.hrv)} meta="today"/><DataRow label="Readiness" value={text(stats?.readiness)} meta="current"/></div></Panel><div className="grid grid-cols-2 gap-2"><Link to="/assistant" className="border border-border p-4 hover:bg-accent"><MessageSquare className="size-4 text-muted-foreground"/><p className="mt-5 text-xs">Ask assistant</p></Link><Link to="/budget" className="border border-border p-4 hover:bg-accent"><Wallet className="size-4 text-muted-foreground"/><p className="mt-5 text-xs">Health budget</p></Link></div></aside></div></AppShell>}
function text(v:unknown){return v===null||v===undefined||v===""?"—":String(v)}
