import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowUpRight, Droplets, Footprints, Flame, MessageSquareHeart, Plus, ScanLine, Target, UserRound } from "lucide-react";
import { ThemeToggle } from "@/components/app/theme-toggle";
import { ErrorState, Skeleton } from "@/components/app/states";
import { Chip, Eyebrow, Metric, Panel, SectionHeader, EmptyState } from "@/components/app/lovable-primitives";
import { useAuth } from "@/lib/auth";
import { apiCheckin, apiCheckinToday, apiDiary, apiPedometerToday, apiStatsToday, todayISO } from "@/lib/api";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "WK Health — Health OS" }, { name: "description", content: "Premium AI Health Operating System backed by live WK Health APIs." }] }), component: Home });

function Home() {
  const { user, logout, isAuthenticated } = useAuth();
  const qc = useQueryClient(); const date = todayISO();
  const stats = useQuery({ queryKey: ["stats", "today"], queryFn: apiStatsToday, enabled: isAuthenticated });
  const ped = useQuery({ queryKey: ["pedometer", "today"], queryFn: apiPedometerToday, enabled: isAuthenticated });
  const diary = useQuery({ queryKey: ["diary", date], queryFn: () => apiDiary(date), enabled: isAuthenticated });
  const checkin = useQuery({ queryKey: ["checkin", "today"], queryFn: apiCheckinToday, enabled: isAuthenticated });
  const doCheckin = useMutation({ mutationFn: apiCheckin, onSuccess: () => void qc.invalidateQueries({ queryKey: ["checkin"] }) });
  const s = stats.data; const remaining = s ? Math.max(0, s.goal - s.eaten + s.burned) : 0; const water = s?.water ?? 0; const waterGoal = s?.waterGoal ?? 8;

  return <div className="rise-in pb-10">
    <header className="flex items-end justify-between gap-4 border-b border-border py-7 sm:py-9"><div><Eyebrow>WK HEALTH · PERSONAL OS</Eyebrow><h1 className="display mt-2 text-3xl sm:text-4xl">สวัสดี, {user?.name ?? user?.email ?? "คุณ"}</h1><p className="mt-2 text-sm text-muted-foreground">ภาพรวมสุขภาพของคุณวันนี้</p></div><div className="flex shrink-0 items-center gap-2"><Link to="/profile" aria-label="Profile" className="press grid size-11 place-items-center rounded-full border border-border bg-surface"><UserRound className="size-4" /></Link><ThemeToggle /><button onClick={() => void logout()} aria-label="ออกจากระบบ" className="press hidden size-11 place-items-center rounded-full border border-border bg-surface sm:grid"><span className="text-xs font-mono">EXIT</span></button></div></header>

    {checkin.data && <button onClick={() => !checkin.data!.alreadyCheckedInToday && doCheckin.mutate()} disabled={checkin.data.alreadyCheckedInToday || doCheckin.isPending} className="press flex w-full items-center gap-3 border-b border-border py-4 text-left disabled:cursor-default"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-foreground text-background">+</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">Streak {checkin.data.streak} วัน</span><span className="block truncate text-xs text-muted-foreground">{checkin.data.greeting}</span></span><span className="text-xs font-semibold">{checkin.data.alreadyCheckedInToday ? "เช็คอินแล้ว" : "เช็คอิน →"}</span></button>}

    {stats.isLoading ? <Skeleton className="h-[360px] rounded-[2rem]" /> : stats.isError || !s ? <div className="py-6"><ErrorState error={stats.error} onRetry={() => void stats.refetch()} /></div> : <section className="grid gap-6 py-7 sm:py-9 lg:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]"><Panel className="grain flex flex-col justify-between gap-10 lg:p-8"><div className="flex flex-wrap items-center gap-2"><Chip tone="signal">All systems nominal</Chip><Chip>Synced now</Chip></div><div><Eyebrow>Energy remaining</Eyebrow><div className="mt-3 flex items-end gap-3"><span className="numeric text-[5.5rem] leading-[.85] font-medium sm:text-[7.5rem]">{Math.round(remaining)}</span><span className="pb-3 text-sm text-muted-foreground">kcal</span></div><p className="mt-6 max-w-lg text-sm leading-6 text-muted-foreground">WK keeps the day readable: food in, movement out, and your target in one calm view.</p></div><Link to="/assistant" className="press inline-flex w-fit items-center gap-2 rounded-full bg-foreground px-5 py-3 text-sm font-medium text-background">Ask WK about today<ArrowUpRight className="size-4" /></Link></Panel><div className="grid grid-cols-2 gap-6"><Panel><Metric label="Consumed" value={Math.round(s.eaten)} unit="kcal" /></Panel><Panel><Metric label="Burned" value={Math.round(s.burned)} unit="kcal" /></Panel><Panel><Metric label="Target" value={Math.round(s.goal)} unit="kcal" /></Panel><Panel><Metric label="Hydration" value={water} unit={`/ ${waterGoal} glasses`} /></Panel></div></section>}

    <section className="border-y border-border py-7 sm:py-9"><SectionHeader eyebrow="Today" title="Movement & nutrition" action={<Link to="/stats" className="text-sm underline underline-offset-4">Full health data</Link>} /><div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><Panel><div className="flex items-end justify-between gap-4"><div><Eyebrow>Steps</Eyebrow>{ped.isLoading ? <Skeleton className="mt-3 h-12 w-36"/> : ped.isError || !ped.data ? <div className="mt-3"><ErrorState error={ped.error} onRetry={() => void ped.refetch()}/></div> : <p className="numeric mt-2 text-5xl font-medium">{ped.data.steps.toLocaleString()}</p>}</div><Footprints className="size-5 text-muted-foreground"/></div>{ped.data ? <p className="mt-4 text-xs text-muted-foreground">{ped.data.distanceKm} km · {ped.data.kcal} kcal · เป้า {ped.data.goal.toLocaleString()} ก้าว</p> : null}</Panel><Panel><div className="flex items-end justify-between gap-4"><div><Eyebrow>Hydration</Eyebrow><p className="numeric mt-2 text-5xl font-medium">{water}</p></div><Droplets className="size-5"/></div><div className="mt-5 flex gap-1.5">{Array.from({length:waterGoal}).map((_,i)=><span key={i} className={`h-1.5 flex-1 rounded-full ${i<water?"bg-foreground":"bg-surface-2"}`}/>)}</div></Panel></div></section>

    <section className="py-7"><SectionHeader eyebrow="Recent" title="Meals" action={<Link to="/diary" className="text-sm underline underline-offset-4">View diary</Link>}/>{diary.isLoading?<div className="mt-4 space-y-2"><Skeleton className="h-16 rounded-2xl"/><Skeleton className="h-16 rounded-2xl"/></div>:diary.isError?<div className="mt-4"><ErrorState error={diary.error} onRetry={()=>void diary.refetch()}/></div>:diary.data?.length?<div className="mt-4 divide-y divide-border border-y border-border">{diary.data.slice(-5).reverse().map(m=><div key={m.id} className="flex items-center gap-3 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-surface-2 text-xl">{m.emoji}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{m.name}</p><p className="text-xs text-muted-foreground">{m.slot} · {m.time}</p></div><span className="numeric text-sm">{m.kcal} kcal</span></div>)}</div>:<div className="mt-4"><EmptyState title="ยังไม่มีมื้ออาหาร" body="เริ่มจากสแกนอาหารหรือเพิ่มมื้อด้วยตัวเอง"/></div>}</section>

    <section className="border-t border-border py-7"><SectionHeader eyebrow="Quick access" title="Your tools"/><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Link to="/scan" className="press rounded-2xl border border-border bg-surface p-4"><ScanLine className="size-4"/><p className="mt-4 text-sm font-medium">Scan food</p><p className="mt-1 text-xs text-muted-foreground">AI nutrition</p></Link><Link to="/pedometer" className="press rounded-2xl border border-border bg-surface p-4"><Footprints className="size-4"/><p className="mt-4 text-sm font-medium">Activity</p><p className="mt-1 text-xs text-muted-foreground">Steps + GPS</p></Link><Link to="/assistant" className="press rounded-2xl border border-border bg-surface p-4"><MessageSquareHeart className="size-4"/><p className="mt-4 text-sm font-medium">WK AI</p><p className="mt-1 text-xs text-muted-foreground">Ask anything</p></Link><Link to="/workout" className="press rounded-2xl border border-border bg-surface p-4"><Target className="size-4"/><p className="mt-4 text-sm font-medium">Workout</p><p className="mt-1 text-xs text-muted-foreground">AI plan</p></Link></div></section>
  </div>;
}
