import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { ErrorState, LoadingState, Skeleton } from "@/components/app/states";
import { useAuth } from "@/lib/auth";
import { apiMoodList, apiMoodRecommend } from "@/lib/api";

export const Route = createFileRoute("/mood")({ head: () => ({ meta: [{ title: "Mood Intelligence — WK Health" }, { name: "description", content: "อาหารที่เหมาะกับอารมณ์และเป้าหมายสุขภาพของคุณ" }] }), component: MoodPage });

function MoodPage() {
  const { isAuthenticated } = useAuth(); const [moodKey, setMoodKey] = useState(""); const [meal, setMeal] = useState<"breakfast" | "main">("main");
  const moodsQ = useQuery({ queryKey: ["mood", "list"], queryFn: apiMoodList, enabled: isAuthenticated });
  useEffect(() => { if (!moodKey && moodsQ.data?.length) setMoodKey(moodsQ.data[0]!.key); }, [moodsQ.data, moodKey]);
  const recQ = useQuery({ queryKey: ["mood", "recommend", moodKey, meal], queryFn: () => apiMoodRecommend(moodKey, meal), enabled: isAuthenticated && Boolean(moodKey) });
  const mood = moodsQ.data?.find(m => m.key === moodKey);
  return <div className="rise-in pb-10"><header className="border-b border-hairline py-7 sm:py-9"><p className="label-editorial mb-2">MIND · BODY · NUTRITION</p><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-display text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Mood intelligence</h1><p className="mt-2 text-sm text-muted-foreground">เลือกความรู้สึก แล้วให้ WK เชื่อมมันเข้ากับมื้อถัดไป</p></div><div className="text-left sm:text-right"><p className="font-display text-5xl font-semibold tracking-[-0.08em]">{mood?.emoji ?? "—"}</p><p className="label-editorial mt-1">CURRENT STATE</p></div></div></header>
  {moodsQ.isLoading ? <LoadingState label="กำลังอ่านอารมณ์…"/> : moodsQ.isError ? <ErrorState error={moodsQ.error} onRetry={()=>void moodsQ.refetch()}/> : <section className="border-b border-hairline py-6"><p className="label-editorial mb-3">HOW ARE YOU FEELING?</p><div className="flex gap-2 overflow-x-auto pb-1">{moodsQ.data!.map(m=><button key={m.key} onClick={()=>setMoodKey(m.key)} className={`press min-h-14 shrink-0 rounded-2xl border px-4 text-sm ${m.key===moodKey?"border-foreground bg-foreground text-background":"border-hairline bg-surface-1 text-muted-foreground"}`}><span className="mr-2 text-xl">{m.emoji}</span>{m.label}</button>)}</div>{mood&&<div className="mt-5 border-l-2 border-foreground pl-4"><p className="font-display text-lg font-semibold">{mood.label}</p>{mood.hint&&<p className="mt-1 text-sm leading-6 text-muted-foreground">{mood.hint}</p>}</div>}</section>}
  <section className="border-b border-hairline py-5"><div className="flex gap-2"><button onClick={()=>setMeal("breakfast")} className={`press min-h-11 rounded-full border px-4 text-xs ${meal==="breakfast"?"border-foreground bg-foreground text-background":"border-hairline bg-surface-1 text-muted-foreground"}`}>มื้อเช้า</button><button onClick={()=>setMeal("main")} className={`press min-h-11 rounded-full border px-4 text-xs ${meal==="main"?"border-foreground bg-foreground text-background":"border-hairline bg-surface-1 text-muted-foreground"}`}>มื้อหลัก</button></div></section>
  <section className="py-7"><div className="mb-5 flex items-end justify-between"><div><p className="label-editorial mb-1">WK RECOMMENDS</p><h2 className="font-display text-xl font-semibold">สิ่งที่เหมาะกับคุณตอนนี้</h2></div><Sparkles className="size-4"/></div>{recQ.isLoading?<div className="space-y-2"><Skeleton className="h-20 rounded-2xl"/><Skeleton className="h-20 rounded-2xl"/></div>:recQ.isError?<ErrorState error={recQ.error} onRetry={()=>void recQ.refetch()}/>:!(recQ.data?.length)?<div className="border-y border-hairline py-12 text-center text-sm text-muted-foreground">ยังไม่มีคำแนะนำสำหรับอารมณ์นี้</div>:<div className="divide-y divide-hairline border-y border-hairline">{recQ.data.map((item,i)=><div key={`${item.name}-${i}`} className="flex items-center gap-4 py-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-surface-2 text-2xl">{item.emoji}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{item.name}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.why}</p></div><p className="font-display text-lg font-semibold tabular-nums">{item.kcal}<span className="ml-1 text-[10px] font-normal text-muted-foreground">kcal</span></p></div>)}</div>}</section></div>;
}
