import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link2, Loader2, Music2, Pause, Play, Plus, Trash2, History } from "lucide-react";
import { ErrorState, LoadingState } from "@/components/app/states";
import { useAuth } from "@/lib/auth";
import { useMusic } from "@/lib/music";
import { apiMusicAdd, apiMusicDelete, apiMusicHistory, apiMusicLibrary, parseYouTubeId } from "@/lib/api";

export const Route = createFileRoute("/music")({ head: () => ({ meta: [{ title: "Music OS — WK Health" }, { name: "description", content: "เพลงที่เล่นต่อเนื่องระหว่างประสบการณ์สุขภาพของคุณ" }] }), component: MusicPage });
function MusicPage() {
  const { isAuthenticated } = useAuth(); const qc = useQueryClient(); const { current, isPlaying, play, toggle } = useMusic();
  const [url,setUrl]=useState(""); const [title,setTitle]=useState("");
  const lib=useQuery({queryKey:["music","library"],queryFn:apiMusicLibrary,enabled:isAuthenticated}); const history=useQuery({queryKey:["music","history"],queryFn:apiMusicHistory,enabled:isAuthenticated});
  const add=useMutation({mutationFn:()=>{const ytId=parseYouTubeId(url);return apiMusicAdd({url:url.trim(),title:title.trim()||url.trim(),type:ytId?"youtube":"audio",...(ytId?{ytId}:{})})},onSuccess:()=>{setUrl("");setTitle("");void qc.invalidateQueries({queryKey:["music"]})}});
  const del=useMutation({mutationFn:(id:string)=>apiMusicDelete(id),onSuccess:()=>void qc.invalidateQueries({queryKey:["music","library"]])}); const tracks=lib.data??[];
  return <div className="rise-in pb-10"><header className="border-b border-hairline py-7 sm:py-9"><p className="label-editorial mb-2">MEDIA OS</p><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-display text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Music</h1><p className="mt-2 text-sm text-muted-foreground">เสียงที่เดินทางไปกับคุณทุกหน้า</p></div><div className="text-left sm:text-right"><p className="font-display text-xl font-semibold">{current?.title ?? "พร้อมเล่น"}</p><p className="label-editorial mt-1">{isPlaying ? "NOW PLAYING" : "PLAYER READY"}</p></div></div></header>
    <section className="border-b border-hairline py-7"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="label-editorial mb-3">ADD TO LIBRARY</p><div className="space-y-2"><label className="flex items-center gap-3 rounded-2xl border border-hairline bg-surface-1 px-4"><Link2 className="size-4 text-muted-foreground"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="YouTube หรือไฟล์เสียง" className="min-h-12 min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><div className="flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="ชื่อเพลง (ไม่บังคับ)" className="min-h-12 min-w-0 flex-1 rounded-2xl border border-hairline bg-surface-1 px-4 text-sm outline-none"/><button onClick={()=>url.trim()&&add.mutate()} disabled={add.isPending||!url.trim()} className="press min-h-12 rounded-2xl bg-foreground px-5 text-sm font-medium text-background disabled:opacity-50">{add.isPending?<Loader2 className="size-4 animate-spin"/>:<Plus className="size-4"/>}</button></div>{add.isError&&<p className="text-sm text-destructive">{add.error instanceof Error?add.error.message:"เพิ่มเพลงไม่สำเร็จ"}</p>}</div></div>{current&&<button onClick={()=>toggle()} className="press flex min-h-16 items-center gap-3 rounded-2xl border border-hairline bg-foreground px-4 text-background"><span className="grid size-10 place-items-center rounded-xl bg-background/10">{isPlaying?<Pause className="size-4"/>:<Play className="size-4"/>}</span><span className="text-left"><span className="block text-xs opacity-60">{isPlaying?"PLAYING":"PAUSED"}</span><span className="block max-w-44 truncate text-sm font-medium">{current.title}</span></span></button>}</div></section>
    <section className="border-b border-hairline py-7"><p className="label-editorial mb-4">YOUR LIBRARY</p>{lib.isLoading?<LoadingState label="กำลังโหลดคลังเพลง…"/>:lib.isError?<ErrorState error={lib.error} onRetry={()=>void lib.refetch()}/>:tracks.length===0?<p className="border-y border-hairline py-8 text-center text-sm text-muted-foreground">ยังไม่มีเพลง — เพิ่มเพลงแรกจากด้านบน</p>:<div className="divide-y divide-hairline border-y border-hairline">{tracks.map(t=>{const active=current?.id===t.id;return <div key={t.id} className={`flex items-center gap-3 py-3 ${active?"bg-surface-1":""}`}><button onClick={()=>active?toggle():play(t,tracks)} aria-label={active&&isPlaying?"หยุดชั่วคราว":`เล่น ${t.title}`} className="press grid size-11 shrink-0 place-items-center rounded-xl bg-foreground text-background">{active&&isPlaying?<Pause className="size-4"/>:<Play className="size-4"/>}</button><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{t.title}</p><p className="text-xs text-muted-foreground">{t.type==="youtube"?"YouTube":"Audio"}</p></div><button onClick={()=>del.mutate(t.id)} aria-label={`ลบ ${t.title}`} className="press grid size-10 shrink-0 place-items-center rounded-xl text-muted-foreground hover:text-destructive"><Trash2 className="size-4"/></button></div>})}</div>}</section>
    <section className="py-7"><div className="mb-4 flex items-center gap-2"><History className="size-4"/><p className="font-semibold">Listening history</p></div>{history.isLoading?<p className="text-sm text-muted-foreground">กำลังโหลด…</p>:history.data?.length?<div className="divide-y divide-hairline border-y border-hairline">{history.data.map((h,i)=><div key={`${h.id}-${i}`} className="flex items-center gap-3 py-3"><Music2 className="size-4 text-muted-foreground"/><span className="min-w-0 flex-1 truncate text-sm">{h.title}</span><span className="text-xs text-muted-foreground">{h.playedAt}</span></div>)}</div>:<p className="border-y border-hairline py-8 text-center text-sm text-muted-foreground">ยังไม่มีประวัติการฟัง</p>}</section>
  </div>;
}