import { createFileRoute } from "@tanstack/react-router";
import { Navigation, Volume2 } from "lucide-react";
import { AppShell } from "@/components/wk/app-shell";
import { MobileNavigate } from "@/components/wk/mobile-pages";
import { Chip, Eyebrow, Panel, SectionHeader } from "@/components/wk/primitives";
import { routeStops } from "@/lib/wk-data";
export const Route=createFileRoute("/navigate")({component:()=> <><div className="hidden lg:block"><NavigatePage/></div><MobileNavigate/></>});
function MapCanvas(){return <div className="grain relative overflow-hidden rounded-2xl border border-border bg-surface-2"><svg viewBox="0 0 800 520" className="h-full w-full"><path d="M0 380 C140 340 200 260 320 250 S520 300 620 210 L800 150" fill="none" stroke="currentColor" strokeWidth="18" className="text-border"/><path d="M0 380 C140 340 200 260 320 250 S520 300 620 210 L800 150" fill="none" stroke="currentColor" strokeWidth="3" strokeDasharray="10 8"/></svg><div className="absolute inset-x-4 top-4 flex gap-2"><Chip tone="solid">Riverside loop</Chip><Chip tone="signal">AQI 24</Chip><Chip>Shaded 78%</Chip></div><div className="absolute inset-x-4 bottom-4 grid grid-cols-[auto_minmax(0,1fr)] items-center gap-4 rounded-2xl border border-border bg-surface/95 p-4"><span className="grid size-12 place-items-center rounded-xl bg-foreground text-background"><Navigation className="size-5"/></span><div><Eyebrow>In 240 m</Eyebrow><p className="display text-2xl">Bear left onto river path</p></div></div></div>}
function NavigatePage(){return <AppShell eyebrow="Guidance" title="Navigate"><div className="grid gap-6 lg:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]"><div className="min-h-[560px]"><MapCanvas/></div><aside className="flex flex-col gap-6"><Panel className="flex items-center justify-between"><div><Eyebrow>Remaining</Eyebrow><p className="numeric mt-2 text-5xl">6.2</p><p className="eyebrow">kilometres</p></div><div className="text-right"><Eyebrow>ETA</Eyebrow><p className="numeric mt-2 text-5xl">31</p><p className="eyebrow">minutes</p></div></Panel><Panel className="flex items-center gap-4"><Volume2 className="size-4"/><div><p className="text-sm font-medium">Voice guidance</p><p className="text-xs text-muted-foreground">Ducking music at each cue</p></div></Panel><div><SectionHeader eyebrow="Itinerary" title="Turn list"/><ol className="divide-y divide-border">{routeStops.map((s,i)=><li key={s.id} className="grid grid-cols-[2rem_1fr_auto] gap-4 py-4"><span className="numeric text-xs">{String(i+1).padStart(2,"0")}</span><div><p className="text-sm font-medium">{s.label}</p><p className="eyebrow">{s.detail}</p></div><span className="numeric text-xs">{s.meta}</span></li>)}</ol></div></aside></div></AppShell>}
