import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import { Activity, Mic, MicOff, Pause, Play, RefreshCw, Volume2 } from 'lucide-react';
import { AppShell } from '@/components/wk/shell';
import { Action, Metric, Panel, PageHeader, StatusIndicator } from '@/components/wk/ui';

export const Route=createFileRoute('/sound-control')({component:SoundControl});

export function SoundControl(){
 const [enabled,setEnabled]=useState(false); const [level,setLevel]=useState(0); const [status,setStatus]=useState('IDLE'); const [error,setError]=useState('');
 const streamRef=useRef<MediaStream|null>(null); const ctxRef=useRef<AudioContext|null>(null); const rafRef=useRef<number|null>(null);
 useEffect(()=>()=>{if(rafRef.current)cancelAnimationFrame(rafRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());void ctxRef.current?.close()},[]);
 async function toggle(){
  setError('');
  if(enabled){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null; if(ctxRef.current){await ctxRef.current.close();ctxRef.current=null} if(rafRef.current)cancelAnimationFrame(rafRef.current);setLevel(0);setEnabled(false);setStatus('IDLE');return}
  if(!navigator.mediaDevices?.getUserMedia){setError('เบราว์เซอร์นี้ไม่รองรับการอ่านระดับเสียงจากไมโครโฟน');return}
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const Ctx=window.AudioContext||((window as unknown as {webkitAudioContext?:typeof AudioContext}).webkitAudioContext);if(!Ctx)throw new Error('Web Audio ไม่พร้อมใช้งาน');const ctx=new Ctx();ctxRef.current=ctx;const source=ctx.createMediaStreamSource(stream);const analyser=ctx.createAnalyser();analyser.fftSize=256;source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{analyser.getByteFrequencyData(data);let sum=0;for(const n of data)sum+=n*n;setLevel(Math.min(100,Math.round(Math.sqrt(sum/data.length)/255*160)));rafRef.current=requestAnimationFrame(tick)};tick();setEnabled(true);setStatus('LISTENING')}catch(e){setError(e instanceof Error?e.message:'ไม่สามารถเปิดไมโครโฟนได้');setEnabled(false);setStatus('BLOCKED')}
 }
 const bars=Array.from({length:28},(_,i)=>Math.max(4,Math.round(level*(0.35+0.65*Math.abs(Math.sin(i*1.17)))/4)));
 return <AppShell title="Sound Control"><PageHeader eyebrow="ENVIRONMENT / SOUND" title="Control your audio environment." description="หน้าควบคุมเสียงแบบมีชีวิต อ่านระดับเสียงจากไมโครโฟนจริงเมื่อคุณอนุญาต" actions={<div className="flex items-center gap-2"><StatusIndicator label={status} state={enabled?'live':'warn'}/><Action icon={RefreshCw} size="sm" onClick={()=>setLevel(0)}/></div>}/><section className="hairline-b grid grid-cols-2 gap-6 py-8 lg:grid-cols-4"><Metric label="Input level" value={String(level)} unit="%" size="lg"/><Metric label="State" value={status} size="sm"/><Metric label="Source" value="MIC" size="sm"/><Metric label="Permission" value={enabled?'ON':'OFF'} size="sm"/></section><div className="grid gap-8 py-8 lg:grid-cols-[1.35fr_.65fr]"><Panel className="min-h-[390px]"><div className="flex items-center justify-between"><div><p className="label-xs">LIVE MONITOR</p><h2 className="display mt-2 text-3xl">Sound field</h2></div><button onClick={()=>void toggle()} className="grid size-14 place-items-center rounded-full bg-foreground text-background">{enabled?<MicOff size={18}/>:<Mic size={18}/>}</button></div><div className="mt-20 flex h-36 items-center gap-1 border-y border-border px-3">{bars.map((h,i)=><i key={i} className="flex-1 bg-foreground transition-[height] duration-75" style={{height:`${h}%`}}/>)}</div><div className="mt-6 flex items-end justify-between"><span className="numeric text-5xl">{level}</span><span className="label-xs">PERCENT INPUT</span></div>{error?<p className="mt-5 text-xs text-destructive">{error}</p>:<p className="mt-5 text-xs text-muted-foreground">{enabled?'กำลังอ่านระดับเสียงจากไมโครโฟนของอุปกรณ์':'กดปุ่มไมโครโฟนเพื่อเริ่มการตรวจวัด'}</p>}</Panel><aside className="space-y-6"><Panel title="Playback"><div className="flex items-center gap-3"><button className="grid size-11 place-items-center rounded-full bg-foreground text-background"><Play size={15}/></button><div><p className="text-sm">Ambient focus</p><p className="text-xs text-muted-foreground">WK Health · environment</p></div></div><div className="mt-7 h-1 bg-border"><div className="h-full w-[42%] bg-foreground"/></div></Panel><Panel title="Listening state"><div className="space-y-4"><div className="flex items-center gap-3"><Activity size={16}/><span className="text-sm">Live input</span></div><div className="flex items-center gap-3"><Volume2 size={16}/><span className="text-sm">Adaptive volume</span></div><div className="flex items-center gap-3"><Pause size={16}/><span className="text-sm">Auto pause</span></div></div></Panel></aside></div></AppShell>
}
