import { Link } from '@tanstack/react-router';
import { Camera, Music2 } from 'lucide-react';
import type { ReactNode } from 'react';
import { AppShell } from '@/components/wk/app-shell';
import { Chip, Eyebrow, Metric, Panel, ProgressRing, SectionHeader, StackedBar } from '@/components/wk/primitives';
import { activityWeek, insights, rings, sleep, vitals, notifications } from '@/lib/wk-data';
import './wk-design.css';

export function Brand(){return <div className="wk-brand"><div className="wk-mark">WK</div><div><b>WK Health</b><span>HEALTH OS</span></div></div>}

/** Stable compatibility wrapper used by live feature screens. */
export function Shell({children,eyebrow='WK Health',title=''}:{children:ReactNode;eyebrow?:string;title?:string}){return <AppShell eyebrow={eyebrow} title={title}>{children}</AppShell>}

export function Health(){return <AppShell eyebrow="Wednesday · 19 August" title="Health overview"><div className="grid gap-6 lg:grid-cols-[1.35fr_1fr]"><Panel className="grain"><div className="flex gap-2"><Chip tone="signal">All systems nominal</Chip><Chip>Synced 2 min ago</Chip></div><Eyebrow>Readiness index</Eyebrow><div className="numeric mt-3 text-8xl">87 <small className="text-sm">/100</small></div><p className="mt-5 max-w-lg text-sm text-muted-foreground">Recovery is ahead of load for the third day running. Your body is prepared for intensity — WK suggests a threshold block before 18:00.</p><Link to="/assistant" className="mt-6 inline-flex rounded-full bg-foreground px-5 py-3 text-sm text-background">Ask WK about today ↗</Link></Panel><div className="grid grid-cols-2 gap-6">{vitals.map(v=><Panel key={v.id}><Metric label={v.label} value={v.value} unit={v.unit} delta={v.delta} trend={v.trend}/></Panel>)}</div></div><section className="mt-14"><SectionHeader eyebrow="Today" title="Movement rings"/><div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel className="flex justify-around">{rings.map(r=><ProgressRing key={r.id} {...r} size={120}/>)}</Panel><Panel><Eyebrow>Active minutes · this week</Eyebrow><p className="numeric mt-2 text-4xl">411</p><div className="mt-8"><div className="flex items-end gap-2">{activityWeek.map(x=><i key={x.day} className="flex-1 bg-foreground" style={{height:`${x.value}%`}}/>)}</div></div></Panel></div></section><section className="mt-14 grid gap-6 lg:grid-cols-2"><Panel><Eyebrow>Sleep · last night</Eyebrow><p className="numeric mt-2 text-4xl">{sleep.score}</p><div className="mt-6"><StackedBar segments={sleep.stages}/></div></Panel><div><SectionHeader eyebrow="Signals" title="What WK noticed"/><div className="divide-y divide-border">{insights.map(i=><div key={i.id} className="py-5"><Eyebrow>{i.tag}</Eyebrow><h3 className="display mt-2 text-xl">{i.title}</h3><p className="mt-2 text-sm text-muted-foreground">{i.body}</p></div>)}</div></div></section></AppShell>}
export function Assistant(){return <AppShell eyebrow="Conversation" title="WK Assistant"><div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Panel className="grain"><Chip tone="solid">Context on</Chip><p className="eyebrow mt-8">You</p><div className="ml-auto mt-2 max-w-sm rounded-2xl bg-foreground px-4 py-3 text-sm text-background">Should I run intervals today or keep it easy?</div><p className="eyebrow mt-8">WK</p><p className="display mt-2 text-2xl">Readiness is 87 and HRV is at a 30-day high, so intervals are supported. I'd cap the session at 6 × 3 min at threshold with 90 s float.</p><div className="mt-6 flex gap-2"><Chip>HRV 68 ms</Chip><Chip>Sleep 91</Chip><Chip>Load 612</Chip></div></Panel><Panel><Eyebrow>Voice · listening</Eyebrow><h2 className="display mt-2 text-3xl">Listening</h2><p className="mt-2 text-sm text-muted-foreground">Speak naturally — pause to send</p><SectionHeader eyebrow="Starters" title="Try asking" className="mt-8"/><div className="divide-y divide-border">{['Plan my week around Saturday’s race','Why did my sleep score drop on Tuesday?','Summarise my last 30 days in three lines','Build a 20-minute mobility block'].map(x=><p key={x} className="py-4 text-sm">{x} ↗</p>)}</div></Panel></div></AppShell>}
export function Notifications(){return <AppShell eyebrow="Timeline" title="Notifications"><div className="flex gap-2 flex-wrap">{['All','Insight','Coach','Social','System'].map((x,i)=><button key={x} className={i===0?'rounded-full bg-foreground px-4 py-2 text-sm text-background':'rounded-full border border-border px-4 py-2 text-sm'}>{x}</button>)}</div><div className="mt-8 divide-y divide-border">{notifications.map(n=><div key={n.id} className="grid grid-cols-[auto_1fr_auto] gap-4 py-5"><i className={`mt-2 size-2 rounded-full ${n.unread?'bg-foreground':'border border-border'}`}/><div><Eyebrow>{n.kind}</Eyebrow><h3 className="display mt-1 text-xl">{n.title}</h3><p className="mt-1 text-sm text-muted-foreground">{n.body}</p></div><span className="numeric text-xs text-muted-foreground">{n.time}</span></div>)}</div></AppShell>}
export function Scan(){return <AppShell eyebrow="Capture" title="Point, hold, resolve."><Panel className="grain"><div className="grid min-h-[420px] place-items-center rounded-2xl border border-border bg-surface-2"><Camera size={48} strokeWidth={1}/></div><div className="mt-5 flex justify-between"><Chip>Library</Chip><button className="rounded-full bg-foreground px-5 py-3 text-sm text-background">Capture</button><Chip>Barcode</Chip></div></Panel></AppShell>}
export function Music(){return <AppShell eyebrow="Sound" title="Tempo, matched to effort."><div className="grid gap-6 lg:grid-cols-2"><Panel className="grain"><div className="grid aspect-square place-items-center bg-surface-2"><Music2 size={52} strokeWidth={1}/></div><Eyebrow className="mt-6">Now playing · focus</Eyebrow><h2 className="display mt-2 text-3xl">Slow Interior</h2><p className="text-sm text-muted-foreground">Kaya Reeve · Ambient Studies, Vol. II</p><button className="mx-auto mt-6 grid size-12 place-items-center rounded-full bg-foreground text-background">Ⅱ</button></Panel><Panel><SectionHeader eyebrow="Queue" title="6 tracks"/>{['Slow Interior','Grey Light Runner','Hold The Line','Longform','Second Wind','Cooldown Study'].map(x=><div key={x} className="flex justify-between border-b border-border py-4 text-sm"><span>{x}</span><span className="numeric text-xs">5:38</span></div>)}</Panel></div></AppShell>}
export function Stats(){return <AppShell eyebrow="Analysis · 12 weeks" title="The long line, not the spike."><div className="grid grid-cols-2 gap-6">{[['MOVEMENT · AVG DAILY STEPS','9,140'],['ACTIVE MINUTES','412'],['AVG RESTING HR','57'],['SLEEP','7:12']].map(x=><Panel key={x[0]}><Eyebrow>{x[0]}</Eyebrow><strong className="numeric mt-4 block text-5xl">{x[1]}</strong></Panel>)}</div></AppShell>}
export function SignIn(){return <div className="min-h-screen grid lg:grid-cols-2"><div className="bg-foreground p-8 text-background lg:p-16"><Brand/><div className="mt-32 max-w-lg"><h1 className="display text-6xl">Health, recorded with the patience of a notebook.</h1></div></div><div className="grid place-items-center p-8"><div className="w-full max-w-md"><Eyebrow>Sign in</Eyebrow><h1 className="display mt-2 text-5xl">Welcome back.</h1><input className="mt-8 w-full rounded-md border border-border bg-transparent p-3" placeholder="Email"/><input className="mt-3 w-full rounded-md border border-border bg-transparent p-3" placeholder="Password" type="password"/><button className="mt-4 w-full rounded-md bg-foreground p-3 text-sm text-background">Continue ↗</button></div></div></div>}
export function StateLibrary(){return <AppShell eyebrow="Design system" title="One system, every state"><Panel className="grain"><Eyebrow>WK HEALTH VISION · V1</Eyebrow><h1 className="display mt-2 text-5xl">One system, every state</h1></Panel></AppShell>}
export function Vision(){return <AppShell eyebrow="Vision UI" title="A calm, monochrome editorial surface for daily health."><div className="grid grid-cols-2 gap-6 lg:grid-cols-4">{[['8,412','steps'],['1,860','kcal'],['58','bpm'],['7:12','sleep']].map(x=><Panel key={x[1]}><strong className="numeric text-4xl">{x[0]}</strong><Eyebrow>{x[1]}</Eyebrow></Panel>)}</div></AppShell>}
