import { Link, useLocation } from "@tanstack/react-router";
import { Bell, Camera, Check, ChevronRight, CircleUserRound, Grid2X2, Headphones, HeartPulse, Home, MessageSquare, Music2, Settings, Sparkles, UsersRound, Activity, ScanLine, BarChart3, LogIn, Circle } from "lucide-react";
import type { ReactNode } from "react";
import "./wk-design.css";

const nav=[
 {to:"/",label:"Overview",icon:Home},
 {to:"/scan",label:"Scan",icon:Camera},
 {to:"/music",label:"Music",icon:Music2},
 {to:"/assistant",label:"Assistant",icon:Sparkles},
 {to:"/stats",label:"Stats",icon:BarChart3},
 {to:"/notifications",label:"Notifications",icon:Bell},
];
const utility=[{to:"/state-library",label:"State library",icon:Grid2X2},{to:"/vision",label:"Vision UI",icon:HeartPulse}];

export function Brand(){return <div className="wk-brand"><div className="wk-mark">WK</div><div><b>WK Health</b><span>HEALTH OS</span></div></div>}
export function DesktopSidebar(){const {pathname}=useLocation();return <aside className="wk-sidebar"><Brand/><div className="wk-nav"><div className="wk-nav-label">TODAY</div>{nav.map(n=><Link key={n.to} to={n.to} className={pathname===n.to?"active":""}><n.icon size={15}/><span>{n.label}</span></Link>)}<div className="wk-rule"/><div className="wk-nav-label">REFERENCE</div>{utility.map(n=><Link key={n.to} to={n.to} className={pathname===n.to?"active":""}><n.icon size={15}/><span>{n.label}</span></Link>)}</div><div className="wk-side-bottom"><div className="wk-mini-player"><div className="wk-art"><BarChart3 size={17}/></div><div className="wk-mini-copy"><b>Nocturne Drift</b><span>Aoi Field · Long Format</span></div><button>Ⅱ</button></div><div className="wk-user"><CircleUserRound size={20}/><div><b>Kasideth Yunpen</b><span>WK HEALTH · OPERATOR</span></div></div><small>• PROTOTYPE · STATIC DATA</small></div></aside>}
export function Topbar({section="OVERVIEW",mobile=false}:{section?:string;mobile?:boolean}){return <header className="wk-topbar"><div className="wk-top-title"><span>{section}</span>{mobile&&<Brand/>}</div><div className="wk-top-right"><span>08:31 · Thu</span><button className="wk-icon"><Bell size={16}/><i/></button><button className="wk-avatar">WK</button></div></header>}
export function MobileHeader(){return <header className="wk-mobile-header"><Brand/><div><button className="wk-icon"><Bell size={20}/><i/></button><button className="wk-icon"><Settings size={20}/></button></div></header>}
export function MobileDock({active="Overview"}:{active?:string}){return <nav className="wk-mobile-dock">{nav.map(n=><Link key={n.label} to={n.to} className={active===n.label?"active":""}><n.icon size={17}/><span>{n.label}</span></Link>)}</nav>}
export function Shell({children,section="OVERVIEW",mobile=false,active}:{children:ReactNode;section?:string;mobile?:boolean;active?:string}){return <div className="wk-app">{mobile?<MobileHeader/>:<DesktopSidebar/>}<main className={mobile?"wk-main wk-mobile-main":"wk-main"}>{!mobile&&<Topbar section={section}/>} {children}</main>{mobile&&<MobileDock active={active}/>}</div>}

const LineChart=({bars=false}:{bars?:boolean})=><div className={bars?"wk-bars":"wk-spark"}>{bars?[20,34,16,43,31,50,26].map((h,i)=><i key={i} style={{height:`${h}%`}}/>):<svg viewBox="0 0 140 48" preserveAspectRatio="none"><path d="M2 34 C18 27 26 38 40 31 S60 37 74 26 S95 31 111 18 S128 15 138 7" fill="none" stroke="currentColor" strokeWidth="1.4"/></svg>}</div>;
const Card=({children,className=""}:{children:ReactNode;className?:string})=><section className={`wk-card ${className}`}>{children}</section>;

export function Health({alt=false}:{alt?:boolean}){return <Shell section="OVERVIEW"><div className="wk-page"><div className="wk-heading"><span>WEDNESDAY · 19 AUGUST</span><h1>Health overview</h1></div><div className="wk-health-grid"><Card className="readiness"><div className="pills"><b>● ALL SYSTEMS NOMINAL</b><span>SYNCED 2 MIN AGO</span></div><label>READINESS INDEX</label><div className="big-number">87 <small>/100</small></div><p>Recovery is ahead of load for the third day running. Your body is prepared for intensity — WK suggests a threshold block before 18:00.</p><button className="black-btn">Ask WK about today ↗</button></Card><div className="metric-grid">{[["READINESS","87","%"],["RESTING HR","54","bpm"],["HRV","68","ms"],["SPO₂","98","%"]].map((m,i)=><Card key={m[0]}><label>{m[0]} <em>{i===0?"+4":i===1?"-2":i===2?"+9":"0"}</em></label><div className="metric-number">{m[1]}<small>{m[2]}</small></div><LineChart/></Card>)}</div></div><div className="wk-section-head"><div><span>TODAY</span><h2>Movement rings</h2></div><a>Full activity</a></div><div className="wk-two-col"><Card className="rings"><div className="rings-row">{[["742","/ 900","Move","KCAL"],["46","/ 60","Exercise","MIN"],["11","/ 12","Stand","HR"]].map(r=><div className="ring" key={r[2]}><div><b>{r[0]}</b><small>{r[1]}</small></div><strong>{r[2]}</strong><span>{r[3]}</span></div>)}</div></Card><Card className="active-min"><label>ACTIVE MINUTES · THIS WEEK</label><div className="active-number">411 <small>+18% VS LAST WEEK</small></div><LineChart bars/><div className="days">MON TUE WED THU FRI SAT SUN</div></Card></div><div className="wk-two-col lower"><Card className="sleep"><label>SLEEP · LAST NIGHT</label><div className="sleep-num">91 <small>7h 42m</small></div><div className="sleep-bar"><i/><i/><i/><i/></div><div className="legend">● Deep 96m　● REM 108m　● Light 232m　● Awake 26m</div></Card><Card className="signals"><label>SIGNALS</label><h2>What WK noticed</h2>{[["RECOVERY","Your nervous system is trending up","HRV rose 9 ms over the last three nights while resting heart rate fell. A hard session today is well supported."],["LOAD","Aerobic base is under-served","82% of last week's minutes were high intensity. Two zone-2 blocks would rebalance the week."],["ENVIRONMENT","Air quality is good on your usual route","AQI 24 along the riverside loop until 19:00. Ideal window for the long run."]].map(x=><div className="signal" key={x[0]}><label>{x[0]}</label><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</Card></div></div></Shell>}

export function Assistant(){return <Shell section="CONVERSATION"><div className="wk-page assistant-page"><div className="assistant-grid"><Card className="conversation"><div className="chat-pills"><b>CONTEXT ON</b><span>SLEEP · HRV · LOAD · CALENDAR</span></div><div className="chat-label">YOU</div><div className="bubble user">Should I run intervals today or keep it easy?</div><div className="chat-label">WK</div><p className="serif-chat">Readiness is 87 and HRV is at a 30-day high, so intervals are supported. I'd cap the session at 6 × 3 min at threshold with 90 s float — that keeps tomorrow's long ride intact.</p><div className="chips"><span>HRV 68 MS</span><span>SLEEP 91</span><span>LOAD 612</span></div><div className="bubble user second">Route it somewhere flat and shaded.</div><div className="chat-label">WK</div><div className="route-card"><span>◔ READING YOUR ROUTE HISTORY</span><i/><i/></div><div className="chat-input">Ask about recovery, training, sleep... <button>↑</button></div></Card><div className="assistant-side"><Card className="listening"><label>VOICE · LISTENING</label><div className="listen-row"><button>□</button><div><h2>Listening</h2><p>Speak naturally — pause to send</p><div className="wave">▂▅▇▂▆▇▃▆▇▂▅▇▃</div></div></div></Card><div className="starter"><label>STARTERS</label><h2>Try asking</h2>{["Plan my week around Saturday's race","Why did my sleep score drop on Tuesday?","Summarise my last 30 days in three lines","Build a 20-minute mobility block"].map(t=><div key={t}>{t}<span>↗</span></div>)}</div><Card className="accepted"><b>✓　Plan accepted</b><p>6 × 3 min threshold added to today at 17:30 with a shaded route.</p></Card></div></div></div></Shell>}

export function Notifications(){return <Shell mobile active="Notifications"><div className="wk-page mobile-notif"><div className="wk-heading"><span>TIMELINE</span><h1>Notifications</h1></div><div className="filters">{["All","Insight","Coach","Social","System"].map((x,i)=><button className={i===0?"selected":""} key={x}>{x}</button>)}</div><div className="timeline">{[["INSIGHT","12m","Recovery window open","Two consecutive nights above baseline HRV.",Sparkles],["SOCIAL","1h","Mina S. set a 5K best","20:41 — 34 seconds faster than her last.",UsersRound],["SYSTEM","5h","Watch firmware updated","Sensor sampling improved for night HRV.",Bell]].map(([a,b,c,d,I],i)=>{const Icon=I as typeof Bell;return <div className="timeline-item" key={String(c)}><div className={`timeline-icon ${i<2?"dark":""}`}><Icon size={17}/></div><div><label>{a}　{b} {i<2&&<i>●</i>}</label><h3>{c}</h3><p>{d}</p></div></div>})}</div></div></Shell>}

export function Scan(){return <Shell section="SCAN"><div className="wk-page"><div className="wk-heading"><span>CAPTURE</span><h1>Point, hold, resolve.</h1><p>A camera surface designed for one-handed capture. Recognition results are static examples.</p></div><div className="scan-grid"><div><Card className="viewfinder"><b>VIEWFINDER　<span>1x · 4:3</span></b><div className="camera-box"><i/><i/><i/><i/><em>⌗</em></div><div className="camera-meta">● AUTO EXPOSURE　 f/1.8 · ISO 200 <span>ϟ Flash　↔ Flip</span></div><div className="scan-actions"><button>▧ Library</button><button>▥ Barcode</button><button className="black-btn">▣ Capture</button></div></Card><Card className="recognition"><b>RECOGNITION　<small>Confidence</small></b>{[["Grilled salmon fillet","Protein source","96%"],["Quinoa, cooked","Grain","88%"],["Broccoli florets","Vegetable","81%"],["Olive oil drizzle","Fat · estimated","54%"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[2]}</span><small>{x[1]}</small></div>)}</Card></div><div className="scan-side"><Card><b>ESTIMATED PLATE　<small>Lunch</small></b><div className="plate-energy"><label>TOTAL ENERGY</label><strong>612<small> kcal</small></strong><p>Portion estimated from plate geometry.</p></div>{[["PROTEIN 46 G","38%"],["CARBS 51 G","34%"],["FAT 19 G","28%"]].map(x=><div className="macro" key={x[0]}><label>{x[0]}<span>{x[1]}</span></label><i/></div>)}</Card><Card className="recent"><b>RECENT CAPTURES</b><div className="capture-grid">{[1,2,3,4,5,6].map(i=><div key={i}><Circle size={20}/><span>{i===1?"07:45":i===2?"YEST 19:10":i===3?"YEST 13:02":i===4?"YEST 08:20":i===5?"TUE 20:40":"TUE 12:55"}</span></div>)}</div></Card><Card className="analysing"><b>ANALYSING</b><div><Loader/><h3>Resolving portions</h3><p>Preparing the presentation layer. No data is being fetched in this prototype.</p></div></Card><Card className="confirm"><b>CONFIRM</b><p>Saving writes to the visual diary timeline only.</p><button>✓ Add to diary</button></Card></div></div></div></Shell>}
function Loader(){return <span className="loader">◔</span>}

export function Music(){return <Shell section="MUSIC"><div className="wk-page"><div className="wk-heading"><span>SOUND</span><h1>Tempo, matched to effort.</h1><p>Transport controls, queue and tempo mapping — all presentational, with no audio pipeline attached.</p></div><div className="music-grid"><div><Card className="now-playing"><div className="album-art">◯</div><div><label>NOW PLAYING · FOCUS</label><h2>Slow Interior</h2><p>Kaya Reeve · Ambient Studies, Vol. II</p><span>72 BPM　 Key F#m　 Lossless · 24/96</span></div><div className="bars-wide">{Array.from({length:38},(_,i)=><i key={i} style={{height:`${20+((i*17)%70)}%`}}/>)}</div><div className="controls">⤨　|◀　<button>Ⅱ</button>　▶|　↻ <span>🔊 ━━━━━</span></div></Card><Card className="queue"><b>QUEUE <small>6 tracks</small></b>{[["Slow Interior","Kaya Reeve · 72 BPM","5:38"],["Grey Light Runner","Aselin · 148 BPM","4:02"],["Hold The Line","Noir · 132 BPM","3:44"],["Longform","Ives Palmer · 96 BPM","7:21"],["Second Wind","Delta Mono · 160 BPM","3:12"],["Cooldown Study","Kaya Reeve · 64 BPM","6:05"]].map((x,i)=><div key={x[0]}><b>{x[0]}</b><small>{x[1]}</small><span>{x[2]} {i===0&&"● LIVE"}</span></div>)}</Card></div><div><Card className="tempo"><b>TEMPO MAP <small>Session</small></b><label>TARGET CADENCE</label><strong>164<small> spm</small></strong>{[["WARM-UP · 96 BPM","12 min"],["BUILD · 132 BPM","18 min"],["PEAK · 160 BPM","9 min"],["COOL DOWN · 64 BPM","8 min"]].map((x,i)=><div key={x[0]}><label>{x[0]}<span>{x[1]}</span></label><i className={i===2?"orange":""}/></div>)}</Card><Card><b>LISTENING TODAY</b><p>Total time <strong>2h 06m</strong></p><p>Avg BPM while active <strong>139</strong></p><p>Sessions <strong>4</strong></p></Card><Card className="collections"><b>COLLECTIONS</b><div>{["LONG RUN","STRENGTH","RECOVERY","SLEEP"].map(x=><span key={x}>◯<small>{x}</small></span>)}</div></Card></div></div></div></Shell>}

export function Stats({chart=false}){return <Shell section="STATS"><div className="wk-page"><div className="wk-heading"><span>ANALYSIS · 12 WEEKS</span><h1>The long line, not the spike.</h1><p>Comparative readings across movement, nutrition and recovery. All figures are illustrative.</p></div><div className="stats-tabs"><button className="active">This quarter</button><button>Export</button></div><div className="stats-metrics">{[["MOVEMENT · AVG DAILY STEPS","9,140","+6%"],["ACTIVE MINUTES","412","+11%"],["AVG RESTING HR","57","-3"],["SLEEP","7:12","+18m"]].map(x=><div key={x[0]}><label>{x[0]}</label><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="stats-grid"><Card className="chart-card"><b>WEEKLY MOVEMENT</b>{chart?<LineChart bars/>:<LineChart/>}<div className="chart-axis">W1　W2　W3　W4　W5　W6　W7　W8　W9　W10　W11　W12</div></Card><Card><b>RECOVERY</b>{[["Readiness","78"],["HRV","64 ms"],["Resting HR","57 bpm"],["Sleep","7h 12m"]].map(x=><p key={x[0]}>{x[0]} <strong>{x[1]}</strong></p>)}</Card><Card><b>COMPARATIVE SIGNALS</b>{["Movement consistency","Sleep debt","Training load","Hydration"].map((x,i)=><p key={x}>{x}<i style={{width:`${42+i*12}%`}}/></p>)}</Card><Card className="small-stats"><div><strong>18</strong><span>sessions</span></div><div><strong>64</strong><span>avg HRV</span></div></Card></div></div></Shell>}

export function SignIn(){return <div className="signin"><div className="signin-black"><Brand/><div><h1>Health, recorded with the patience of a notebook.</h1><p>One continuous record of movement, meals, mood and sound — kept in a restrained typographic system.</p></div><small>128k　　43m　　99.9</small></div><div className="signin-form"><div className="form-box"><label>SIGN IN</label><h1>Welcome back.</h1><p>Continue to your WK Health workspace.</p><input placeholder="Email"/><input placeholder="Password" type="password"/><button>Continue　↗</button><div className="or">or</div><button className="outline">Continue with Google</button><button className="outline">Continue with Apple</button><a>Forgot password?</a></div></div></div>}

export function StateLibrary(){return <Shell section="DESIGN SYSTEM"><div className="wk-page state-page"><div className="wk-heading"><span>WK HEALTH VISION · V1</span><h1>One system, every state</h1><p>The canonical reference for tokens, primitives and interface states. Every production screen in WK Health composes from this page — nothing here is decorative.</p><b className="live-ref">● LIVE REFERENCE</b></div><div className="wk-section-head"><div><span>FOUNDATION</span><h2>Tokens</h2></div></div><div className="token-grid"><Card><label>SURFACES & INK</label><div className="swatches">{["BACKGROUND","SURFACE","SURFACE-2","ACCENT","MUTED-FG","FOREGROUND","SIGNAL","DESTRUCTIVE"].map(x=><div key={x}><i className={x.toLowerCase().replace("-","")}/><span>{x}</span></div>)}</div></Card><Card><label>TYPE SCALE</label><p className="mono">EYEBROW · IBM PLEX MONO</p><h2>Display · Instrument Serif</h2><b>Title · Archivo Semibold</b><p>Body · Archivo Regular, generous leading for long-form guidance.</p><strong className="sample-number">87.4</strong></Card></div><div className="wk-section-head"><div><span>CONTROLS</span><h2>Interactive states</h2></div></div></div></Shell>}

export function Vision({mobile=false}:{mobile?:boolean}){if(mobile)return <Shell mobile active="Overview"><div className="vision-mobile"><label>PRESENTATION PROTOTYPE</label><h1>Vision UI</h1><p>A calm, monochrome editorial surface for daily health.</p><div className="vision-stats"><strong>8,412</strong><strong>1,860</strong><strong>58</strong><strong>7:12</strong></div><Card><label>KEY STATES</label>{["Wake up","Morning walk","Breakfast scanned","Strength session","Evening recovery"].map(x=><p key={x}>○　{x}</p>)}</Card><Card><label>TARGETS</label><p>Movement　──────── 84%</p><p>Protein　───────── 61%</p><p>Hydration　──────── 45%</p></Card></div></Shell>;
return <Shell section="VISION UI"><div className="wk-page"><div className="wk-heading"><span>VISION UI</span><h1>A calm, monochrome editorial surface for daily health.</h1><p>Presentation prototype. The same visual language scales from phone to desktop.</p></div><div className="vision-metrics">{[["8,412","steps"],["1,860","kcal"],["58","bpm"],["7:12","sleep"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><div className="vision-grid"><Card><b>TODAY</b>{["Wake up","Morning walk","Breakfast scanned","Focus block","Strength session"].map((x,i)=><p key={x}><span>{i===3?"●":"○"}</span>{x}<small>{["06:40","07:05","07:45","08:30","18:00"][i]}</small></p>)}</Card><Card><b>QUICK CAPTURE</b><div className="quick-grid">{["Scan meal","Movement","Mood check","Sound"].map(x=><button key={x}>{x}</button>)}</div><div className="dark-player"><label>NOW PLAYING · Focus</label><h2>Slow Interior</h2><p>Kaya Reeve · Ambient</p></div></Card></div></div></Shell>}
