import { useEffect, useMemo, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { AppShell } from '@/components/wk/app-shell';
import { Chip, Eyebrow, Metric, Panel, ProgressRing, SectionHeader, StackedBar } from '@/components/wk/primitives';
import { activityWeek as fallbackWeek, insights, rings as fallbackRings, sleep, vitals as fallbackVitals } from '@/lib/wk-data';
import { apiFetch } from '@/lib/api';
import './live-design.css';

type AnyRecord = Record<string, any>;
const n = (value: any, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const pick = (obj: AnyRecord | null | undefined, ...keys: string[]) => {
  for (const key of keys) if (obj?.[key] !== undefined && obj?.[key] !== null) return obj[key];
  return null;
};

export function LiveHealthOverview() {
  const [today, setToday] = useState<AnyRecord | null>(null);
  const [weekly, setWeekly] = useState<AnyRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let cancelled=false; (async()=>{ try { const [a,b]=await Promise.all([apiFetch('/api/stats/today'),apiFetch('/api/stats/weekly')]); if(cancelled)return; setToday((a?.totals??a?.data??a??{}) as AnyRecord); setWeekly(Array.isArray(b?.days)?b.days:Array.isArray(b)?b:[]); } catch(e){ if(!cancelled)setError(e instanceof Error?e.message:'Live health data unavailable'); } finally { if(!cancelled)setLoading(false); } })(); return ()=>{cancelled=true}; },[]);
  const liveVitals=useMemo(()=>{const calories=n(pick(today,'calories','eaten'),0),protein=n(pick(today,'protein','totalProtein'),0),burned=n(pick(today,'burned'),0); return fallbackVitals.map((v,i)=>i===0?{...v,value:calories||'—',unit:'kcal',delta:error?'OFFLINE':'LIVE'}:i===2?{...v,value:protein||'—',unit:'g',delta:error?'OFFLINE':'LIVE'}:i===3?{...v,value:burned||'—',unit:'kcal',delta:error?'OFFLINE':'LIVE'}:{...v,value:'—',delta:error?'OFFLINE':'LIVE'});},[today,error]);
  const bars=useMemo(()=>{if(!weekly.length)return []; const values=weekly.map(r=>n(pick(r,'calories','kcal','burn','steps'))),max=Math.max(...values,1); return weekly.slice(-7).map((r,i)=>({day:String(r.day??i+1).slice(-5),value:Math.max(0,Math.round(n(pick(r,'calories','kcal','burn','steps'))/max*100))}));},[weekly]);
  return <AppShell eyebrow="TODAY / HEALTH" title="Health overview"><div className="grid gap-6 lg:grid-cols-[1.35fr_1fr]"><Panel className="grain"><div className="flex gap-2"><Chip tone="signal">{loading?'Syncing…':error?'Offline':'Live systems nominal'}</Chip><Chip>{error?'Service unavailable':'Backend synced'}</Chip></div><Eyebrow>Readiness index</Eyebrow><div className="numeric mt-3 text-8xl">{today?(n(pick(today,'readiness','readinessScore'),0)||'—'):'—'} <small className="text-sm">/100</small></div><p className="mt-5 max-w-lg text-sm text-muted-foreground">Recovery, nutrition and activity totals are loaded from the authenticated WK Health account.</p><Link to="/assistant" className="mt-6 inline-flex rounded-full bg-foreground px-5 py-3 text-sm text-background">Ask WK about today ↗</Link></Panel><div className="grid grid-cols-2 gap-6">{liveVitals.map(v=><Panel key={v.id}><Metric label={v.label} value={v.value} unit={v.unit} delta={v.delta} trend={[]}/></Panel>)}</div></div><section className="mt-14"><SectionHeader eyebrow="Today" title="Movement rings"/><div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel className="flex justify-around">{fallbackRings.map(r=><ProgressRing key={r.id} {...r} value={0} goal={r.goal} size={120}/>)}</Panel><Panel><Eyebrow>Activity · this week</Eyebrow><p className="numeric mt-2 text-4xl">{weekly.length?Math.round(weekly.reduce((s,r)=>s+n(pick(r,'steps','burn','calories','kcal')),0)):'—'}</p><div className="mt-8"><div className="flex h-36 items-end gap-2">{bars.map(x=><i key={x.day} title={x.day} className="flex-1 bg-foreground" style={{height:`${x.value}%`}}/>)}</div></div></Panel></div></section><section className="mt-14 grid gap-6 lg:grid-cols-2"><Panel><Eyebrow>Sleep · last night</Eyebrow><p className="numeric mt-2 text-4xl">—</p><div className="mt-6"><StackedBar segments={[]}/></div></Panel><div><SectionHeader eyebrow="Signals" title="What WK noticed"/><div className="divide-y divide-border">{insights.map(i=><div key={i.id} className="py-5"><Eyebrow>{i.tag}</Eyebrow><h3 className="display mt-2 text-xl">{i.title}</h3><p className="mt-2 text-sm text-muted-foreground">{i.body}</p></div>)}</div></div></section></AppShell>;
}

export function LiveStatsDesign(){const[rows,setRows]=useState<AnyRecord[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{void apiFetch('/api/stats/weekly').then((r:AnyRecord)=>setRows(Array.isArray(r?.days)?r.days:[])).catch(()=>setRows([])).finally(()=>setLoading(false));},[]);const values=rows.length?rows.slice(-12).map(r=>n(pick(r,'calories','kcal','burn','steps'))):[],max=Math.max(...values,1);return <AppShell eyebrow="Analysis · 12 weeks" title="The long line, not the spike."><div className="grid grid-cols-2 gap-6"><Panel><Eyebrow>ACTIVITY · LIVE</Eyebrow><strong className="numeric mt-4 block text-5xl">{loading?'…':rows.length||'—'}</strong><span className="text-xs text-muted-foreground">days returned</span></Panel><Panel><Eyebrow>DATA SOURCE</Eyebrow><strong className="numeric mt-4 block text-5xl">API</strong><span className="text-xs text-muted-foreground">authenticated account</span></Panel></div><Panel className="mt-6"><SectionHeader eyebrow="Live weekly trend" title="Active load"/><div className="mt-8 flex h-48 items-end gap-3">{values.length?values.map((v,i)=><i key={i} className="flex-1 bg-foreground" style={{height:`${Math.max(5,v/max*100)}%`}} title={String(v)}/>):<div className="w-full self-end border-b border-dashed border-border pb-3 text-xs text-muted-foreground">No trend data yet.</div>}</div></Panel></AppShell>}
