import { useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import { ArrowUp, Mic, Paperclip, Sparkles } from "lucide-react";
import { assistantHistory, chat } from "@/lib/wk-api";
import { AppShell } from "@/components/wk/app-shell";

type Msg = { role: "user" | "assistant"; content: string };
type SpeechRecognitionLike = { lang:string; interimResults:boolean; continuous:boolean; start:()=>void; stop:()=>void; onresult:((event:any)=>void)|null; onerror:(()=>void)|null; onend:(()=>void)|null };

export function LiveAssistant(){
 const [messages,setMessages]=useState<Msg[]>([]); const [text,setText]=useState(""); const [busy,setBusy]=useState(false); const [listening,setListening]=useState(false); const [error,setError]=useState("");
 const inputRef=useRef<HTMLInputElement>(null); const recognitionRef=useRef<SpeechRecognitionLike|null>(null);
 useEffect(()=>{void assistantHistory().then(r=>{if(r.success)setMessages(r.data.messages.map(m=>({role:m.role==='user'?'user':'assistant',content:m.content})));});},[]);
 async function send(e?:FormEvent,forced?:string){e?.preventDefault();const message=(forced??text).trim();if(!message||busy)return;setText("");setError("");setMessages(m=>[...m,{role:'user',content:message}]);setBusy(true);const r=await chat(message);if(r.success){setMessages(m=>[...m,{role:'assistant',content:r.data.reply}]);if(typeof window!=="undefined"&&'speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(r.data.reply);u.lang=/[ก-๙]/.test(r.data.reply)?'th-TH':'en-US';window.speechSynthesis.speak(u);}}else{setError(r.error);setMessages(m=>[...m,{role:'assistant',content:'ตอนนี้ WK เชื่อมต่อโค้ชไม่ได้ ลองอีกครั้งเมื่อ backend พร้อมครับ'}]);}setBusy(false);}
 function toggleVoice(){if(listening){recognitionRef.current?.stop();setListening(false);return;}const Ctor=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Ctor){setError('เบราว์เซอร์นี้ไม่รองรับเสียงพูด กรุณาพิมพ์แทน');return;}const r=new Ctor() as SpeechRecognitionLike;r.lang='th-TH';r.interimResults=false;r.continuous=false;r.onresult=event=>{const spoken=event.results?.[0]?.[0]?.transcript??'';setText(spoken);void send(undefined,spoken);};r.onerror=()=>{setListening(false);setError('รับเสียงไม่สำเร็จ กรุณาลองใหม่');};r.onend=()=>setListening(false);recognitionRef.current=r;setListening(true);setError('');r.start();}
 return <AppShell eyebrow="Conversation" title="WK Assistant"><div className="wk-page assistant-page"><div className="assistant-grid"><section className="wk-card conversation"><div className="chat-pills"><b>CONTEXT ON</b><span>SLEEP · HRV · LOAD · CALENDAR</span></div><div className="min-h-[460px] space-y-6 overflow-auto pr-2">{messages.length===0&&<div className="py-16 text-center"><Sparkles className="mx-auto mb-4" size={22}/><p className="eyebrow">WK</p><p className="serif-chat">Ask about recovery, training, sleep, food or today.</p></div>}{messages.map((m,i)=><div key={`${i}-${m.content}`}><div className="chat-label">{m.role==='user'?'YOU':'WK'}</div>{m.role==='user'?<div className="bubble user">{m.content}</div>:<p className="serif-chat">{m.content}</p>}</div>)}{busy&&<div><div className="chat-label">WK</div><p className="serif-chat opacity-60">Thinking…</p></div>}</div><form onSubmit={e=>void send(e)} className="chat-input"><button type="button" onClick={()=>inputRef.current?.click()} aria-label="Attach"><Paperclip size={15}/></button><input ref={inputRef} value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about recovery, training, sleep..."/><button type="submit" disabled={busy||!text.trim()} className="grid size-9 place-items-center rounded-full bg-foreground text-background disabled:opacity-40"><ArrowUp size={15}/></button></form>{error&&<p className="mt-2 text-[10px] text-muted-foreground">{error}</p>}</section><aside className="assistant-side"><section className="wk-card listening"><label>VOICE · {listening?'LISTENING':'READY'}</label><div className="listen-row"><button type="button" onClick={toggleVoice} className={listening?'ring-2 ring-foreground':''}><Mic size={20}/></button><div><h2>{listening?'Listening':'Voice input'}</h2><p>{listening?'Speak naturally — pause to send':'Tap the microphone to ask WK out loud.'}</p><div className="wave">▂▅▇▂▆▇▃▆▇▂▅▇▃</div></div></div></section><div className="starter"><label>STARTERS</label><h2>Try asking</h2>{['How should I train today?','Why did my sleep change?','Summarise my last 30 days','Build a 20-minute mobility block'].map(t=><button type="button" key={t} onClick={()=>void send(undefined,t)}>{t}<span>↗</span></button>)}</div></aside></div></div></AppShell>;
}
