import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AppShell } from './shell';
import { Action, EmptyState, ErrorState, LoadingState, Panel, PageHeader, StatusIndicator } from './ui';
import { apiFetch, todayISO } from '@/lib/api';
import '../wk-design.css';

type Page='budget'|'diary'|'export'|'friends'|'home'|'mood'|'music'|'nlp'|'notifications'|'pedometer'|'profile'|'stats'|'vision'|'workout';
type Config={eyebrow:string;title:string;sub:string;primary:string;secondary:string[];chart:string};
const config:Record<Page,Config>={
 home:{eyebrow:'TODAY / HEALTH',title:'A steady day, held together.',sub:'Your health record, assembled from the signals that are actually available.',primary:'Today',secondary:['Movement','Nutrition','Recovery'],chart:'Daily signals'},
 diary:{eyebrow:'DIARY / TODAY',title:'Today, written down.',sub:'Food and nutrition entries saved to your account.',primary:'Meals',secondary:['Energy','Macros','Timing'],chart:'Calories by entry'},
 budget:{eyebrow:'BUDGET / MONTH TO DATE',title:'What health costs, plainly.',sub:'Plan nutrition spending from your saved health preferences.',primary:'Budget',secondary:['Monthly plan','Categories','Remaining'],chart:'Plan distribution'},
 export:{eyebrow:'EXPORT / DATA',title:'A study of your health, not a screenshot.',sub:'Create a downloadable export from your real account data.',primary:'Export',secondary:['Range','Records','Format'],chart:'Export history'},
 friends:{eyebrow:'FRIENDS / SOCIAL',title:'Company, not competition.',sub:'People and shared activity connected to your account.',primary:'Network',secondary:['Friends','Activity','Invites'],chart:'Shared activity'},
 mood:{eyebrow:'MOOD / CHECK-IN',title:'How does today feel?',sub:'Save a check-in and let the backend build the trend.',primary:'Check-in',secondary:['Today','Trend','Notes'],chart:'Mood history'},
 music:{eyebrow:'MUSIC / LIBRARY',title:'Tempo, matched to effort.',sub:'Your saved audio links and playback history.',primary:'Library',secondary:['Tracks','Played','Focus'],chart:'Listening history'},
 nlp:{eyebrow:'LANGUAGE / INPUT',title:'Say it plainly, see it structured.',sub:'Send natural language to the nutrition analysis API.',primary:'Analysis',secondary:['Input','Parsed','Result'],chart:'Parsed records'},
 notifications:{eyebrow:'NOTIFICATIONS / TIMELINE',title:'Only what needs saying.',sub:'Server-backed alerts and notification settings.',primary:'Timeline',secondary:['Unread','Settings','System'],chart:'Notification volume'},
 pedometer:{eyebrow:'PEDOMETER / ACTIVITY',title:'The long line, not the spike.',sub:'Daily movement recorded from your account.',primary:'Steps',secondary:['Steps','Distance','Active'],chart:'Daily steps'},
 profile:{eyebrow:'PROFILE / ACCOUNT',title:'Your record, kept current.',sub:'Account information loaded from the authentication service.',primary:'Profile',secondary:['Identity','Body','Goal'],chart:'Account metrics'},
 stats:{eyebrow:'STATS / 12 WEEKS',title:'The long line, not the spike.',sub:'Trend views generated from stored health records.',primary:'Trend',secondary:['Movement','Recovery','Sleep'],chart:'Activity trend'},
 vision:{eyebrow:'VISION / INSIGHT',title:'See the signal, then act.',sub:'Insights returned by the live health service.',primary:'Signals',secondary:['Insight','Metrics','Actions'],chart:'Insight history'},
 workout:{eyebrow:'WORKOUT / TRAINING',title:'Training, recorded properly.',sub:'Planned and completed sessions stored in your account.',primary:'Sessions',secondary:['Load','Duration','Status'],chart:'Training load'},
};
const num=(v:any,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const list=(r:any):any[]=>Array.isArray(r)?r:(r?.items??r?.data??r?.days??r?.sessions??r?.tracks??r?.notifications??r?.friends??r?.records??[]);
const pick=(o:any,...keys:string[])=>{for(const k of keys){if(o?.[k]!==undefined&&o?.[k]!==null)return o[k]}return null};
const valueFor=(x:any)=>num(pick(x,'calories','kcal','steps','value','durationMin','duration','load','activeMinutes','amount','count','score','distanceKm'),0);

function ChartBars({values}:{values:number[]}){const max=Math.max(...values,1);return <div className="wk-bars">{Array.from({length:12},(_,i)=>{const v=values[i]??0;return <i key={i} style={{height:`${values.length?Math.max(v/max*100,2):2}%`}}/>})}</div>}

export function LiveDataPage({page}:{page:Page}){
 const c=config[page]; const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [data,setData]=useState<any>(null); const [input,setInput]=useState(''); const [budget,setBudget]=useState(''); const [range,setRange]=useState('30d'); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);setError('');try{let r:any;switch(page){case'home':r=await apiFetch('/api/stats/today');break;case'diary':r=await apiFetch(`/api/diary?date=${todayISO()}`);break;case'mood':r=await apiFetch('/api/mood/history');break;case'music':r=await apiFetch('/api/music/library');break;case'notifications':r=await apiFetch('/api/notifications');break;case'pedometer':r=await apiFetch('/api/pedometer/today');break;case'profile':r=await apiFetch('/api/auth/me');break;case'stats':r=await apiFetch('/api/stats/weekly');break;case'workout':r=await apiFetch('/api/workout/history');break;case'friends':r=await apiFetch('/api/friends');break;case'vision':r=await apiFetch('/api/insight/weekly');break;case'export':r=await apiFetch('/api/export/history');break;case'budget':r=null;break;case'nlp':r=null;break}setData(r)}catch(e){setError(e instanceof Error?e.message:'Unable to load the live service')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[page]);
 const records=useMemo(()=>list(data),[data]);
 const values=useMemo(()=>records.map(valueFor).filter(x=>x>0).slice(-12),[records]);
 const root=data?.data??data?.totals??data??{};
 const metrics=useMemo(()=>{
   if(page==='home') return [['CALORIES',pick(root,'calories','eaten','totalCalories'),'kcal'],['PROTEIN',pick(root,'protein','totalProtein'),'g'],['BURNED',pick(root,'burned','burn'),'kcal'],['GOAL',pick(root,'goalKcal','goal'),'kcal']];
   if(page==='pedometer') return [['STEPS',pick(root,'steps'),'today'],['DISTANCE',pick(root,'distanceKm','distance_km'),'km'],['ACTIVE',pick(root,'activeMinutes','active_minutes'),'min'],['FLOORS',pick(root,'floors'),'']];
   if(page==='profile') return [['WEIGHT',pick(root,'weightKg','weight_kg'),'kg'],['HEIGHT',pick(root,'heightCm','height_cm'),'cm'],['GOAL',pick(root,'goalKcal','goal_kcal'),'kcal'],['STREAK',pick(root,'streak'),'days']];
   if(page==='stats') return [['RECORDS',records.length,'items'],['AVG',records.length?Math.round(records.reduce((s,r)=>s+num(pick(r,'calories','kcal')),0)/records.length):'—','kcal'],['PEAK',records.length?Math.max(...records.map(valueFor)):'—','value'],['STATUS',error?'OFF':'LIVE','server']];
   return [['RECORDS',records.length,'items'],['STATUS',error?'OFF':'LIVE','server'],['SYNC',loading?'…':'NOW','API'],['DATA',records.length?'READY':'EMPTY','state']];
 },[root,page,records,error,loading]);
 async function action(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{let r:any;if(page==='budget'){const amount=num(budget);if(amount<=0)throw new Error('Enter a valid monthly budget');r=await apiFetch('/api/budget/plan',{method:'POST',body:{monthlyBudget:amount,conditions:[],allergies:[],days:7}})}else if(page==='nlp'){if(!input.trim())throw new Error('Enter text to analyse');r=await apiFetch('/api/nlp/analyze',{method:'POST',body:{text:input}})}else if(page==='diary'){if(!input.trim())throw new Error('Enter food name');r=await apiFetch('/api/diary',{method:'POST',body:{date:todayISO(),foodName:input.trim(),calories:0,mealType:'snack'}})}else if(page==='mood'){if(!input.trim())throw new Error('Enter a mood');r=await apiFetch('/api/mood/checkin',{method:'POST',body:{mood:input.trim(),date:todayISO()}})}else if(page==='workout'){r=await apiFetch('/api/workout',{method:'POST',body:{title:input.trim()||'Workout',durationMin:0,status:'planned'}})}else if(page==='friends'){r=await apiFetch('/api/friends/add',{method:'POST',body:{code:input.trim()}})}else if(page==='export'){r=await apiFetch('/api/export',{method:'POST',body:{format:'csv',range}})}else if(page==='notifications'){r=await apiFetch('/api/notifications/settings',{method:'PATCH',body:{smartTiming:true}})}else if(page==='profile'){r=await apiFetch('/api/auth/me',{method:'PATCH',body:{displayName:input.trim()}})}else if(page==='pedometer'){const steps=num(input);if(steps<0)throw new Error('Invalid steps');r=await apiFetch('/api/pedometer',{method:'POST',body:{date:todayISO(),steps}})}else if(page==='music'){if(!input.trim())throw new Error('Paste an audio URL');r=await apiFetch('/api/music',{method:'POST',body:{url:input.trim(),title:input.trim(),type:'audio'}})}else{await load();r=data}setNotice('Saved to the live service');setInput('');if(r!==undefined)setData(r);if(page!=='nlp'&&page!=='music')void load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 const placeholder=page==='nlp'?'Describe your meal or action…':page==='friends'?'Invite code…':page==='diary'?'Food name…':page==='mood'?'Mood…':page==='music'?'Audio URL…':page==='profile'?'Display name…':page==='pedometer'?'Steps today…':page==='workout'?'Session title…':'Value…';
 return <AppShell title={c.title} wide><div className="wk-page"><PageHeader eyebrow={c.eyebrow} title={c.title} description={c.sub} actions={<div className="pills"><b>{loading?'SYNCING':error?'OFFLINE':'LIVE API'}</b><span>ACCOUNT</span></div>}/>
 <div className="reference-kpis">{metrics.map(([label,val,unit])=><div className="reference-kpi" key={label}><span className="eyebrow">{label}</span><strong>{val===null||val===undefined?'—':String(val)}</strong><span className="numeric text-[9px] text-muted-foreground">{unit}</span></div>)}</div>
 <div className="reference-grid mt-6"><main className="space-y-6">
  <section className="reference-chart"><div className="wk-section-head pt-0"><div><Eyebrow>{c.primary}</Eyebrow><h2>{c.chart}</h2></div><span>{records.length?'LIVE':'EMPTY'}</span></div>{loading?<LoadingState label="Loading your real records…"/>:error?<ErrorState label="Live service unavailable" body={error}/>:<>{values.length?<ChartBars values={values}/>:<EmptyState label="No records yet" body="The chart is wired to the backend. It will populate when real account data exists."/>}</>}</section>
  <div className="wk-two-col"><Panel className="wk-card"><Eyebrow>{c.secondary[0]}</Eyebrow><div className="active-number">{records.length?String(values.reduce((s,v)=>s+v,0)):'—'} <small>LIVE</small></div><p className="text-xs text-muted-foreground">Derived only from records returned by the authenticated API.</p></Panel><Panel className="wk-card"><Eyebrow>{c.secondary[1]}</Eyebrow><div className="reference-list">{records.slice(0,5).map((x,i)=><div key={String(x.id??i)}><span className="time">{String(pick(x,'createdAt','created_at','day','date')??'—').slice(-8)}</span><span>{String(pick(x,'name','title','food_name','track','message','mood','exercise_name','exerciseName')??'Record')}</span><span className="numeric">{valueFor(x)||'—'}</span></div>)}{!records.length&&<div className="reference-empty">No saved records.</div>}</div></Panel></div>
 </main><aside className="reference-side"><Panel className="wk-card"><Eyebrow>{c.primary} / ACTION</Eyebrow><h2 className="display mt-2 text-3xl">Write to the system.</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Every action here writes through the live API and is scoped to the signed-in account.</p><form onSubmit={action} className="reference-form mt-5">{page==='budget'&&<input value={budget} onChange={e=>setBudget(e.target.value)} type="number" min="1" placeholder="Monthly budget"/>}{page==='export'&&<select value={range} onChange={e=>setRange(e.target.value)}><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option><option value="all">All records</option></select>}{!['budget','export','notifications'].includes(page)&&<input value={input} onChange={e=>setInput(e.target.value)} placeholder={placeholder}/>}<button type="submit" disabled={busy}>{busy?'Saving…':page==='export'?'Create export':'Save'}</button></form>{notice&&<p className="mt-3 text-xs">{notice}</p>}</Panel><Panel className="wk-card"><Eyebrow>{c.secondary[2]}</Eyebrow><div className="reference-list mt-3"><div><span className="time">01</span><span>API connection</span><span>✓</span></div><div><span className="time">02</span><span>Account scope</span><span>✓</span></div><div><span className="time">03</span><span>Server persistence</span><span>✓</span></div></div></Panel></aside></div></div></AppShell>;
}
