import { FormEvent, useState } from "react";
import { login, register } from "@/lib/wk-api";

export function LiveAuth(){
  const [mode,setMode]=useState<"login"|"register">("login");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [done,setDone]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const r=mode==="login"?await login(email,password):await register(email,password,name);if(r.success){setDone(true);setTimeout(()=>location.assign("/"),350);}else setError(r.error);setBusy(false);}
  return <div className="signin"><div className="signin-black"><div className="wk-brand"><div className="wk-mark">WK</div><div><b>WK Health</b><span>HEALTH OS</span></div></div><div><h1>Health, recorded with the patience of a notebook.</h1><p>One continuous record of movement, meals, mood and sound — connected to the live WK Health system.</p></div><small>LIVE　·　SECURE SESSION　·　HEALTH OS</small></div><div className="signin-form"><form onSubmit={submit} className="form-box"><label>{mode === "login" ? "SIGN IN" : "CREATE ACCOUNT"}</label><h1>{mode === "login" ? "Welcome back." : "Start your WK workspace."}</h1><p>{mode === "login" ? "Continue to your WK Health workspace." : "Create an account to sync your scans, diary and assistant."}</p>{mode === "register"&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Name" required/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email" required/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password · 8+ characters" type="password" minLength={8} required/><button disabled={busy}>{busy?"Connecting…":mode === "login"?"Continue　↗":"Create account　↗"}</button>{error&&<p className="text-xs text-muted-foreground">{error}</p>}{done&&<p className="text-xs">Session ready. Opening WK…</p>}<div className="or">or</div><button type="button" className="outline" onClick={()=>setMode(m=>m==="login"?"register":"login")}>{mode === "login"?"Create a new account":"I already have an account"}</button></form></div></div>
}
