import { useEffect, useState } from 'react';
import { Bluetooth, Check, Loader2, RefreshCw, Smartphone, Unplug } from 'lucide-react';
import { AppShell } from './shell';
import { Action, ErrorState, Metric, Panel, PageHeader, StatusIndicator } from './ui';
import { listDevices, removeDevice, saveDevice, syncDevice, type LiveDevice } from '@/lib/live-api';
type BluetoothNavigator=Navigator & { bluetooth?: { requestDevice(options:{acceptAllDevices:boolean}):Promise<{name?:string;id?:string}> } };
const bluetoothReady=()=>typeof navigator!=='undefined'&&Boolean((navigator as BluetoothNavigator).bluetooth);
export function LiveDeviceConnect(){const [device,setDevice]=useState<LiveDevice|null>(null);const [devices,setDevices]=useState<LiveDevice[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=async()=>{try{setDevices(await listDevices())}catch(e){setError(e instanceof Error?e.message:'โหลดอุปกรณ์ไม่สำเร็จ')}};
 useEffect(()=>{void load()},[]);
 async function connect(){setBusy(true);setError('');try{const b=(navigator as BluetoothNavigator).bluetooth;if(!b)throw new Error('เบราว์เซอร์นี้ไม่รองรับ Web Bluetooth');const d=await b.requestDevice({acceptAllDevices:true});const saved=await saveDevice({name:d.name,deviceUid:d.id,deviceType:'bluetooth'});setDevice(saved);await load()}catch(e){setError(e instanceof Error?e.message:'ไม่สามารถเชื่อมต่ออุปกรณ์ได้')}finally{setBusy(false)}}
 async function disconnect(id:string){setBusy(true);try{await removeDevice(id);setDevice(null);await load()}catch(e){setError(e instanceof Error?e.message:'ตัดการเชื่อมต่อไม่สำเร็จ')}finally{setBusy(false)}}
 async function sync(id:string){setBusy(true);try{await syncDevice(id);await load()}catch(e){setError(e instanceof Error?e.message:'sync ไม่สำเร็จ')}finally{setBusy(false)}}
 return <AppShell title="Device Connect"><PageHeader eyebrow="INTELLIGENCE / DEVICES" title="Pairing, without the noise." description="เชื่อมต่ออุปกรณ์จริงและบันทึกสถานะไว้ในบัญชี WK Health" actions={<div className="flex items-center gap-2"><StatusIndicator label={busy?'SYNCING':device?'CONNECTED':'READY'} state={device?'live':'warn'}/><Action icon={RefreshCw} size="sm" onClick={()=>void load()} disabled={busy}/></div>}/><section className="hairline-b grid grid-cols-2 gap-6 py-8 lg:grid-cols-4"><Metric label="Connected" value={String(devices.filter(d=>d.status==='connected').length)} size="lg"/><Metric label="State" value={device?'PAIRED':'IDLE'} size="sm"/><Metric label="Protocol" value="BLE" size="sm"/><Metric label="Browser" value={bluetoothReady()?'READY':'LIMITED'} size="sm"/></section><div className="grid gap-8 py-8 lg:grid-cols-[1.25fr_.75fr]"><Panel className="min-h-[340px]"><div className="flex h-full flex-col justify-between"><div className="flex justify-between"><Bluetooth className="size-6" strokeWidth={1.2}/><span className="label-xs">LIVE DISCOVERY</span></div><div><h2 className="display text-4xl">Bring every signal together.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">อุปกรณ์ที่เลือกจาก Bluetooth จะถูกบันทึกใน backend และใช้เป็นจุดเชื่อมต่อสำหรับการ sync ในอนาคต</p><Action className="mt-7" icon={busy?Loader2:Bluetooth} variant="solid" onClick={()=>void connect()} disabled={busy}>{busy?'กำลังค้นหา…':'ค้นหาอุปกรณ์'}</Action></div></div></Panel><aside className="space-y-6"><Panel title="Saved connections">{devices.length?devices.map(d=><div key={d.id} className="border-b border-border py-4 last:border-0"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-foreground text-background"><Check size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm">{d.name||'Unnamed device'}</p><p className="text-xs text-muted-foreground">{d.deviceType} · {d.status}</p></div></div><div className="mt-3 flex gap-3"><button onClick={()=>void sync(d.id)} className="text-xs underline">Sync now</button><button onClick={()=>void disconnect(d.id)} className="inline-flex items-center gap-1 text-xs underline"><Unplug size={12}/>Disconnect</button></div></div>):<div className="flex items-center gap-3 text-muted-foreground"><Smartphone size={17}/><span className="text-xs">No device paired</span></div>}</Panel>{error?<ErrorState label="Device connection" body={error}/>:null}</aside></div></AppShell>}
