import { useEffect, useState } from 'react';
import { Mic, RefreshCw, Volume2 } from 'lucide-react';
import { AppShell } from './shell';
import { Action, ErrorState, Metric, Panel, PageHeader, StatusIndicator } from './ui';
import { getSoundSettings, saveSoundSettings, type SoundSettings } from '@/lib/live-api';
export function LiveSoundControl(){const[s,setS]=useState<SoundSettings>({volume:68,mode:'Ambient',voiceEnabled:true,outputDevice:null,inputDevice:null});const[busy,setBusy]=useState(true);const[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{setS(await getSoundSettings())}catch(e){setError(e instanceof Error?e.message:'โหลด sound settings ไม่สำเร็จ')}finally{setBusy(false)}};useEffect(()=>{void load()},[]);
 async function update(p:Partial<SoundSettings>){setBusy(true);try{setS(await saveSoundSettings(p))}catch(e){setError(e instanceof Error?e.message:'บันทึก sound settings ไม่สำเร็จ')}finally{setBusy(false)}}
 return <AppShell title="Sound Control"><PageHeader eyebrow="SOUND / ENVIRONMENT" title="Your audio environment." description="การตั้งค่าเสียงถูกบันทึกในบัญชีและซิงก์กลับจาก backend จริง" actions={<div className="flex items-center gap-2"><StatusIndicator label={busy?'SYNCING':'LIVE'} state={error?'warn':'live'}/><Action icon={RefreshCw} size="sm" onClick={()=>void load()} disabled={busy}/></div>}/><section className="hairline-b grid grid-cols-2 gap-6 py-8 lg:grid-cols-4"><Metric label="Volume" value={`${s.volume}%`} size="lg"/><Metric label="Mode" value={s.mode} size="sm"/><Metric label="Voice" value={s.voiceEnabled?'ON':'OFF'} size="sm"/><Metric label="Output" value={s.outputDevice||'SYSTEM'} size="sm"/></section><div className="grid gap-8 py-8 lg:grid-cols-[1.2fr_.8fr]"><Panel className="min-h-[340px]"><div className="flex items-start justify-between"><Volume2 size={24} strokeWidth={1.2}/><span className="label-xs">PERSISTED SESSION</span></div><div className="mt-14"><div className="flex items-end justify-between"><h2 className="display text-4xl">Master volume</h2><span className="numeric text-4xl">{s.volume}</span></div><input aria-label="Master volume" type="range" min="0" max="100" value={s.volume} onChange={e=>setS({...s,volume:Number(e.target.value)})} onMouseUp={()=>void update({volume:s.volume})} onTouchEnd={()=>void update({volume:s.volume})} className="mt-8 w-full"/><div className="mt-2 flex justify-between text-[9px] text-muted-foreground"><span>0</span><span>50</span><span>100</span></div></div></Panel><aside className="space-y-6"><Panel title="Audio mode"><div className="grid grid-cols-2 gap-2">{['Focus','Ambient','Voice','Silent'].map(mode=><button key={mode} onClick={()=>void update({mode})} className={`border p-4 text-left ${s.mode===mode?'bg-foreground text-background':''}`}><b className="text-xs">{mode}</b><p className="mt-1 text-[9px] opacity-70">{mode==='Focus'?'low distraction':mode==='Ambient'?'environmental':mode==='Voice'?'speech clarity':'quietest'}</p></button>)}</div></Panel><Panel title="Voice assistant"><button onClick={()=>void update({voiceEnabled:!s.voiceEnabled})} className="flex w-full items-center justify-between"><span className="flex items-center gap-3 text-xs"><Mic size={16}/>{s.voiceEnabled?'Enabled':'Disabled'}</span><span className={`h-5 w-9 rounded-full p-1 ${s.voiceEnabled?'bg-foreground':'bg-border'}`}><i className="block size-3 rounded-full bg-background" style={{marginLeft:s.voiceEnabled?16:0}}/></span></button></Panel>{error?<ErrorState label="Sound control" body={error}/>:null}</aside></div></AppShell>}
