import { ReactNode, useState } from 'react';
import { Link, useLocation } from '@tanstack/react-router';
import { Bell, BookOpen, Footprints, Headphones, HeartPulse, Menu, Music2, ScanLine, Sparkles, UserRound, X, Dumbbell, BarChart3, Navigation, Users, Languages, Settings, Download, Grid2X2, Wallet } from 'lucide-react';
const bottom=[['/','TODAY',HeartPulse],['/scan','SCAN',ScanLine],['/stats','STATS',BarChart3],['/music','MUSIC',Music2],['/profile','YOU',UserRound]] as const;
const groups=[
 ['TODAY',[['/','Overview',HeartPulse],['/scan','Scan',ScanLine],['/diary','Diary',BookOpen],['/mood','Mood',HeartPulse]]],
 ['MOVEMENT',[['/pedometer','Pedometer',Footprints],['/workout','Workout',Dumbbell],['/music','Music',Music2],['/sound','Sound',Headphones],['/stats','Stats',BarChart3],['/navigate','Navigate',Navigation]]],
 ['INTELLIGENCE',[['/assistant','Assistant',Sparkles],['/nlp','Language',Languages],['/device-connect','Devices',Settings]]],
 ['LIFE',[['/budget','Budget',Wallet],['/gallery','Gallery',Grid2X2],['/friends','Friends',Users],['/export','Export',Download]]],
 ['ACCOUNT',[['/profile','Profile',UserRound],['/notifications','Notifications',Bell],['/settings','Access',Settings]]],
] as const;
export function MobileShell({children,eyebrow='OVERVIEW',active='TODAY',player=true}:{children:ReactNode;eyebrow?:string;active?:string;player?:boolean}){const [open,setOpen]=useState(false);const {pathname}=useLocation();return <div className="min-h-screen bg-background text-foreground pb-[150px] lg:hidden"><header className="sticky top-0 z-40 flex h-[62px] items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur"><button onClick={()=>setOpen(v=>!v)} className="grid size-9 place-items-center" aria-label="Menu">{open?<X size={18}/>:<Menu size={18}/>}</button><Link to="/" className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-[5px] bg-foreground text-[9px] font-bold text-background">WK</span><span><b className="block text-[11px] leading-none">WK Health</b><span className="eyebrow block text-[7px] tracking-[.18em]">HEALTH OS</span></span></Link><div className="flex items-center gap-1"><Link to="/notifications" className="relative grid size-9 place-items-center"><Bell size={16}/><i className="absolute right-2 top-2 size-1.5 rounded-full bg-signal"/></Link><Link to="/profile" className="grid size-9 place-items-center text-[9px]">WK</Link></div></header>{open&&<><button className="fixed inset-0 z-40 bg-foreground/20" onClick={()=>setOpen(false)}/><aside className="fixed inset-y-[62px] left-0 z-50 w-[82%] max-w-[320px] overflow-y-auto border-r border-border bg-background px-4 py-5 shadow-2xl"><div className="mb-5 flex items-center gap-2 px-2"><span className="grid size-8 place-items-center rounded bg-foreground text-[9px] font-bold text-background">WK</span><div><b className="text-xs">WK Health</b><p className="eyebrow text-[7px]">VISION V1</p></div></div>{groups.map(([title,items])=><div key={title}><p className="eyebrow mt-4 px-2 pb-2">{title}</p>{items.map(([to,label,I])=><Link onClick={()=>setOpen(false)} key={label} to={to} className={`flex items-center gap-3 rounded-md px-2 py-2.5 text-sm ${pathname===to?'bg-surface-2':''}`}><I size={15}/>{label}</Link>)}</div>)}<p className="eyebrow mt-6 px-2">● LIVE · BACKEND CONNECTED</p></aside></>}{children}{player&&<MobilePlayer/>}<nav className="fixed bottom-0 left-0 right-0 z-30 grid grid-cols-5 border-t border-border bg-background/96 px-2 py-2 backdrop-blur">{bottom.map(([to,label,I])=><Link key={label} to={to} className={`flex min-h-[52px] flex-col items-center justify-center gap-1 ${active===label?'text-foreground':'text-muted-foreground'}`}><I size={16}/><span className="text-[9px] tracking-[.08em]">{label}</span></Link>)}</nav></div>}
function MobilePlayer(){const[playing,setPlaying]=useState(true);return <div className="fixed bottom-[66px] left-3 right-3 z-30 rounded-[18px] border border-border bg-background/97 p-3 shadow-float backdrop-blur"><div className="flex items-center gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-lg border border-border bg-surface-2"><Music2 size={16}/></div><div className="min-w-0 flex-1"><b className="block truncate text-sm">Nocturne Drift</b><span className="block truncate text-[10px] text-muted-foreground">Aoi Field · Long Format</span></div><button onClick={()=>setPlaying(p=>!p)} className="grid size-10 place-items-center rounded-full bg-foreground text-background">{playing?'Ⅱ':'▶'}</button></div><div className="mt-2 flex items-center gap-2"><span className="numeric text-[9px]">2:12</span><div className="h-[3px] flex-1 rounded-full bg-border"><div className="h-full w-[52%] rounded-full bg-foreground"/></div><span className="numeric text-[9px]">4:14</span></div></div>}
