import { useMemo, useRef, useState, type ReactNode } from 'react';
import { AppShell } from './shell';
import { apiExportRequest, apiFriendsAdd, apiFriendsCheer, apiNotificationUpdate } from '@/lib/api-new-features';
import { Camera, Download, Mic, Play, Plus, Search, Send, Upload, Volume2 } from 'lucide-react';

type PageKey = 'assistant'|'auth'|'budget'|'device-connect'|'diary'|'export'|'friends'|'gallery'|'home'|'mood'|'music'|'nlp'|'notifications'|'pedometer'|'profile'|'scan'|'sound-control'|'stats'|'vision'|'workout';

type Config={kicker:string;title:string;description:string;metrics?:[string,string,string][]};
const C:Record<PageKey,Config>={
 assistant:{kicker:'ASSISTANT · CONVERSATION',title:'A quiet second opinion.',description:'A restrained conversation surface for recovery, training, sleep, food and the week.',metrics:[['TODAY','4','messages'],['THREADS','9','active'],['VOICE','ON','ready']]},
 auth:{kicker:'AUTH · SINCE 2019',title:'Health, recorded with the patience of a notebook.',description:'One continuous record of movement, meals, mood and sound — kept in a single restrained typographic system.'},
 budget:{kicker:'BUDGET · AUGUST · MONTH TO DATE',title:'What health costs, plainly.',description:'A ledger view of food and wellbeing spend.',metrics:[['BUDGET','600.00','EUR'],['SPENT','412.60','EUR'],['REMAINING','187.40','EUR']]},
 'device-connect':{kicker:'DEVICES · CONNECTIONS',title:'Pairing, without the noise.',description:'Connected hardware, signal and sync status.',metrics:[['DEVICES','1','connected'],['SIGNAL','98','%'],['SYNC','2','min ago']]},
 diary:{kicker:'DIARY · THURSDAY, 20 AUGUST',title:'Today, written down.',description:'Entries are grouped by meal with a running energy ledger down the right column.',metrics:[['CALORIES','1,860','kcal'],['PROTEIN','96','g'],['MEALS','3','logged']]},
 export:{kicker:'EXPORT · YOUR DATA',title:'Take everything with you.',description:'Create a clean export of your health record and keep a local copy.',metrics:[['RANGE','30','days'],['FILES','18.4','MB'],['LAST','01','today']]},
 friends:{kicker:'FRIENDS · SOCIAL',title:'Company, not competition.',description:'A calm social layer for encouragement, streaks and shared progress.',metrics:[['FRIENDS','4','confirmed'],['STREAK','18.4','days'],['CHEERS','12','this week']]},
 gallery:{kicker:'GALLERY · MEDIA',title:'A contact sheet of the year.',description:'Photos and videos connected to meals, movement and daily notes.',metrics:[['MEDIA','412','items'],['PHOTOS','318','images'],['VIDEO','52','clips']]},
 home:{kicker:'TODAY · 20 AUGUST',title:'A steady day, held together.',description:'The daily overview for movement, energy, sleep and the next useful action.',metrics:[['STEPS','8,412','+1.2%'],['ENERGY','1,860','kcal'],['RESTING HR','58','bpm']]},
 mood:{kicker:'MOOD · TODAY',title:'How does today feel?',description:'Log a simple state and keep the signal beside the rest of your record.',metrics:[['MOOD','3.8','/ 5'],['SLEEP','7:12','hrs'],['STRESS','2.1','/ 5']]},
 music:{kicker:'MUSIC · FOCUS',title:'Tempo, matched to effort.',description:'Adaptive listening for movement, recovery and focus.',metrics:[['TEMPO','164','BPM'],['ENERGY','0.91','index'],['QUEUE','18','tracks']]},
 nlp:{kicker:'LANGUAGE · STRUCTURED',title:'Say it plainly, see it structured.',description:'Turn natural language into a clear, editable health action.',metrics:[['INTENT','0.91','confidence'],['FIELDS','7','extracted'],['STATUS','READY','parser']]},
 notifications:{kicker:'NOTIFICATIONS · TIMELINE',title:'Only what needs saying.',description:'A focused stream of insight, coach, social and system events.',metrics:[['UNREAD','4','items'],['INSIGHT','2','new'],['SYSTEM','1','update']]},
 pedometer:{kicker:'PEDOMETER · MOVEMENT',title:'Eight thousand, four hundred and twelve.',description:'A precise view of steps, pace and daily movement.',metrics:[['STEPS','8,412','today'],['DISTANCE','6.24','km'],['ACTIVE','1:48','hrs']]},
 profile:{kicker:'PROFILE · YOU',title:'When Kade',description:'Your record, preferences and personal health baseline.',metrics:[['AGE','34','years'],['WEIGHT','178','lb'],['HEIGHT','5\' 10','']]},
 scan:{kicker:'SCAN · FOOD',title:'Point, hold, resolve.',description:'Capture a meal and turn it into a structured food record.',metrics:[['CALORIES','612','kcal'],['PROTEIN','31','g'],['CONFIDENCE','92','%']]},
 'sound-control':{kicker:'SOUND · ENVIRONMENT',title:'Your audio environment.',description:'Monitor ambient sound and tune the listening environment.',metrics:[['AVERAGE','61','dB'],['PEAK','78','dB'],['FOCUS','ON','mode']]},
 stats:{kicker:'STATS · TRENDS',title:'The long line, not the spike.',description:'A longer view of the signals that actually matter.',metrics:[['STEPS','9,140','avg'],['WORKOUT','412','min'],['SLEEP','7:14','avg']]},
 vision:{kicker:'VISION UI · PROTOTYPE',title:'Vision UI',description:'The supplied Vision reference rendered as a living product surface.',metrics:[['STEPS','8,412','/ 10k'],['ENERGY','1,860','kcal'],['RESTING HR','58','bpm']]},
 workout:{kicker:'WORKOUT · STRENGTH',title:'Lower body, moderate load.',description:'A structured session with sets, effort and recovery.',metrics:[['LOAD','45','min'],['RPE','4.2','/ 10'],['SETS','17','completed']]}
};

const bars=[38,54,46,68,58,82,64,74,48,88,60,70,44,78];
const MiniBars=({tall=false}:{tall?:boolean})=><div className={`flex ${tall?'h-32':'h-16'} items-end gap-1`}>{bars.map((n,i)=><i key={i} className="flex-1 bg-foreground/75" style={{height:`${Math.max(8,n*(tall?1:0.72))}%`}}/>)}</div>;
const Line=({n=10}:{n?:number})=><div className="flex h-14 items-end gap-1 border-b border-border pb-1">{Array.from({length:n},(_,i)=><i key={i} className="flex-1 bg-foreground/15" style={{height:`${20+((i*17)%61)}%`}}/>)}</div>;
const Eyebrow=({children}:{children:ReactNode})=><p className="eyebrow text-[8px]">{children}</p>;
const Card=({children,className=''}:{children:ReactNode;className?:string})=><section className={`rounded-xl border border-border bg-card p-5 ${className}`}>{children}</section>;
const Button=({children,onClick,secondary=false,type='button'}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;type?:'button'|'submit'})=><button type={type} onClick={onClick} className={`inline-flex min-h-9 items-center justify-center gap-2 rounded-md px-4 text-[11px] ${secondary?'border border-border bg-background':'bg-foreground text-background'}`}>{children}</button>;
const MetricStrip=({items}:{items?:[string,string,string][]})=><div className="grid grid-cols-3 border-y border-border">{(items??[]).map(x=><div key={x[0]} className="border-r border-border px-4 py-5 last:border-0"><Eyebrow>{x[0]}</Eyebrow><div className="numeric mt-2 text-3xl">{x[1]}</div><p className="mt-1 text-[9px] text-muted-foreground">{x[2]}</p></div>)}</div>;
const SectionTitle=({children,right}:{children:ReactNode;right?:ReactNode})=><div className="mb-4 flex items-end justify-between border-b border-border pb-3"><h2 className="display text-2xl">{children}</h2>{right}</div>;

function LivingAction({label='Saved'}:{label?:string}){const[s,setS]=useState(false);return <Button onClick={()=>setS(v=>!v)}>{s?'✓ '+label:'Save'}</Button>}

function PageBody({page}:{page:PageKey}){
 const [notice,setNotice]=useState(''); const [query,setQuery]=useState(''); const [selected,setSelected]=useState(3); const [playing,setPlaying]=useState(false); const [media,setMedia]=useState<string[]>([]); const inputRef=useRef<HTMLInputElement>(null);
 const config=C[page];
 const submit=async()=>{if(page==='export'){const r=await apiExportRequest({format:'csv',range:'30d'});setNotice(r.success?'Export created':'Export could not be created');}else if(page==='friends'){const r=await apiFriendsAdd(query.trim());setNotice(r.success?'Friend added':'Invite code not accepted');}else if(page==='notifications'){const r=await apiNotificationUpdate({smartTiming:true});setNotice(r.success?'Notification preference saved':'Could not save preference');}else setNotice('Updated');};
 const onFiles=(files:FileList|null)=>{if(!files)return;setMedia(Array.from(files).map(f=>URL.createObjectURL(f)));setNotice(`${files.length} media item${files.length>1?'s':''} ready`)};
 if(page==='auth')return <AuthBody/>;
 if(page==='assistant')return <AssistantBody query={query} setQuery={setQuery} submit={submit} notice={notice} setNotice={setNotice}/>;
 return <>
  <div className="grid gap-7 lg:grid-cols-[1.35fr_.65fr]"><div><MetricStrip items={config.metrics}/><Card className="mt-6"><Eyebrow>{config.kicker}</Eyebrow><h2 className="display mt-2 text-4xl">{config.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{config.description}</p><div className="mt-6 flex flex-wrap gap-2"><LivingAction label="Updated"/>{page==='scan'&&<Button onClick={()=>inputRef.current?.click()}><Camera size={14}/>Capture</Button>}{page==='gallery'&&<Button onClick={()=>inputRef.current?.click()}><Upload size={14}/>Add media</Button>}{page==='music'&&<Button onClick={()=>setPlaying(v=>!v)}><Play size={13}/>{playing?'Pause':'Play'}</Button>}</div></Card></div><Card><Eyebrow>LIVE STATE</Eyebrow><div className="mt-5 space-y-4">{['Connected','Current record','Sync healthy','Actions enabled'].map((x,i)=><div key={x} className="flex items-center justify-between border-b border-border pb-3 last:border-0"><span className="text-xs">{x}</span><span className="numeric text-[9px]">{i===0?'● ON':'READY'}</span></div>)}</div><div className="mt-5"><Line/></div></Card></div>
  <div className="mt-7 grid gap-6 lg:grid-cols-[1.55fr_.75fr]">
   <div className="space-y-6">
    {page==='home'&&<HomeSections/>}
    {page==='budget'&&<BudgetSections/>}
    {page==='device-connect'&&<DeviceSections setNotice={setNotice}/>} 
    {page==='diary'&&<DiarySections/>}
    {page==='export'&&<ExportSections onExport={submit} notice={notice}/>} 
    {page==='friends'&&<FriendsSections query={query} setQuery={setQuery} submit={submit} notice={notice}/>} 
    {page==='gallery'&&<GallerySections media={media} onFiles={onFiles} inputRef={inputRef}/>} 
    {page==='mood'&&<MoodSections selected={selected} setSelected={setSelected}/>} 
    {page==='music'&&<MusicSections playing={playing} setPlaying={setPlaying}/>} 
    {page==='nlp'&&<NlpSections query={query} setQuery={setQuery}/>} 
    {page==='notifications'&&<NotificationSections/>}
    {page==='pedometer'&&<PedometerSections/>}
    {page==='profile'&&<ProfileSections/>}
    {page==='scan'&&<ScanSections inputRef={inputRef} onFiles={onFiles} media={media} setNotice={setNotice}/>} 
    {page==='sound-control'&&<SoundSections/>}
    {page==='stats'&&<StatsSections/>}
    {page==='vision'&&<VisionSections/>}
    {page==='workout'&&<WorkoutSections/>}
   </div>
   <aside className="space-y-6"><Card><Eyebrow>DETAILS</Eyebrow>{['Baseline','Today','Last 7 days','Long view'].map((x,i)=><div key={x} className="flex justify-between border-b border-border py-4 text-xs last:border-0"><span>{x}</span><span className="numeric">{['86','92','+18%','stable'][i]}</span></div>)}</Card><Card><Eyebrow>SIGNALS</Eyebrow><h3 className="display mt-2 text-2xl">What WK noticed</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">The product keeps the useful signal visible and the rest quiet. Every control on this surface changes local state immediately.</p><div className="mt-5"><MiniBars/></div></Card></aside>
  </div>
  {notice&&<div className="fixed bottom-5 right-5 z-50 rounded-md bg-foreground px-4 py-3 text-[11px] text-background shadow-lg">{notice}</div>}
 </>;
}

function HomeSections(){return <><Card><SectionTitle right={<span className="numeric text-[9px]">08:31</span>}>Movement rings</SectionTitle><div className="grid grid-cols-3 gap-4">{[['Move','742','/ 900'],['Exercise','46','/ 60'],['Stand','11','/ 12']].map(x=><div key={x[0]} className="rounded-lg border border-border p-5 text-center"><div className="mx-auto grid size-28 place-items-center rounded-full border-2 border-foreground"><span className="numeric text-xl">{x[1]}<small className="block text-[8px] text-muted-foreground">{x[2]}</small></span></div><p className="mt-3 text-xs">{x[0]}</p></div>)}</div></Card><Card><SectionTitle>Active minutes · this week</SectionTitle><MiniBars tall/></Card><Card><SectionTitle>Sleep · last night</SectionTitle><div className="numeric text-4xl">91</div><div className="mt-4 h-2 overflow-hidden rounded bg-surface-2"><div className="h-full w-[76%] bg-foreground"/></div><div className="mt-3 flex justify-between text-[9px] text-muted-foreground"><span>Deep 96m</span><span>REM 108m</span><span>Light 232m</span><span>Awake 26m</span></div></Card></>}
function BudgetSections(){return <><Card><SectionTitle>Allocation by category</SectionTitle>{[['Groceries','214.80','52%'],['Eating out','96.40','23%'],['Supplements','54.00','13%'],['Training','32.00','9%']].map(x=><div key={x[0]} className="border-b border-border py-4"><div className="flex justify-between text-xs"><span>{x[0]}</span><span className="numeric">{x[1]} EUR</span></div><div className="mt-2 h-1 bg-surface-2"><i className="block h-full bg-foreground" style={{width:x[2]}}/></div></div>)}</Card><Card><SectionTitle>Cumulative spend · 14 days</SectionTitle><MiniBars tall/></Card><Card><SectionTitle>Transactions</SectionTitle>{['Market — vegetables, fish','Studio drop-in class','Groceries','Protein powder, 1 kg','Café — lunch','Refund — cancelled class'].map((x,i)=><div key={x} className="flex justify-between border-b border-border py-3 text-xs"><span>{x}</span><span className="numeric">{i%2?'−16.00':'−24.80'} EUR</span></div>)}</Card></>}
function DeviceSections({setNotice}:{setNotice:(s:string)=>void}){const[connected,setConnected]=useState(true);return <><Card><SectionTitle right={<Button secondary onClick={()=>setNotice('Scan complete')}>Rescan</Button>}>Primary device</SectionTitle><div className="flex items-center justify-between border-b border-border py-5"><div><b className="text-sm">WK Band 03</b><p className="mt-1 text-xs text-muted-foreground">Firmware 4.18.2 · SN 8842-A</p></div><button onClick={()=>setConnected(v=>!v)} className="rounded-full border border-border px-3 py-1 text-[9px]">{connected?'CONNECTED':'DISCONNECTED'}</button></div><div className="grid grid-cols-3 gap-4 pt-5">{[['BATTERY','92%'],['SIGNAL','98%'],['LAST SYNC','2 min']].map(x=><div key={x[0]}><Eyebrow>{x[0]}</Eyebrow><div className="numeric mt-2 text-2xl">{x[1]}</div></div>)}</div></Card><Card><SectionTitle>Last 16 samples</SectionTitle><MiniBars/></Card></>}
function DiarySections(){return <><Card><SectionTitle>Breakfast · 07:45</SectionTitle>{[['Rolled oats, 60 g','Carbs 40 g · Protein 8 g'],['Kefir, 200 ml','Protein 7 g'],['Blueberries, 80 g','Carbs 11 g']].map(x=><div key={x[0]} className="flex justify-between border-b border-border py-4 text-xs"><span>{x[0]}<small className="mt-1 block text-muted-foreground">{x[1]}</small></span><span className="numeric">410 kcal</span></div>)}</Card><Card><SectionTitle>Lunch · 12:10</SectionTitle>{['Rice bowl','Chicken breast','Greens','Sparkling water'].map(x=><div key={x} className="flex justify-between border-b border-border py-3 text-xs last:border-0"><span>{x}</span><span className="text-muted-foreground">logged</span></div>)}</Card></>}
function ExportSections({onExport,notice}:{onExport:()=>void;notice:string}){return <><Card><SectionTitle>Create export</SectionTitle><div className="grid grid-cols-2 gap-3">{['7 days','30 days','90 days','All data'].map((x,i)=><button key={x} className={`rounded-md border p-4 text-left text-xs ${i===1?'bg-foreground text-background':'border-border'}`} onClick={onExport}>{x}<small className="mt-1 block opacity-60">CSV + PDF</small></button>)}</div>{notice&&<p className="mt-4 text-xs">{notice}</p>}</Card><Card><SectionTitle>Recent exports</SectionTitle>{['30 days · CSV','7 days · PDF','All data · CSV'].map(x=><div key={x} className="flex justify-between border-b border-border py-4 text-xs last:border-0"><span>{x}</span><Download size={14}/></div>)}</Card></>}
function FriendsSections({query,setQuery,submit,notice}:{query:string;setQuery:(v:string)=>void;submit:()=>void;notice:string}){return <><Card><SectionTitle>Add a friend</SectionTitle><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Invite code" className="min-h-9 flex-1 rounded-md border border-border bg-background px-3 text-xs"/><Button onClick={submit}>Add</Button></div>{notice&&<p className="mt-3 text-xs">{notice}</p>}</Card><Card><SectionTitle>People this week</SectionTitle>{['Mina S. · 18 day streak','Kade R. · 12 day streak','Nina P. · 8 day streak'].map((x,i)=><div key={x} className="flex items-center justify-between border-b border-border py-4 text-xs last:border-0"><span>{x}</span><Button secondary onClick={async()=>{const r=await apiFriendsCheer(String(i));setQuery(r.success?'Cheered':'')}}>Cheer</Button></div>)}</Card></>}
function GallerySections({media,onFiles,inputRef}:{media:string[];onFiles:(f:FileList|null)=>void;inputRef:React.RefObject<HTMLInputElement|null>}){return <><input ref={inputRef} type="file" accept="image/*,video/*" multiple className="hidden" onChange={e=>onFiles(e.target.files)}/><Card><SectionTitle right={<Button onClick={()=>inputRef.current?.click()}><Plus size={13}/>Add</Button>}>Media library</SectionTitle><div className="grid grid-cols-3 gap-3">{[...media,...Array.from({length:6})].map((src,i)=><div key={i} className="aspect-square overflow-hidden rounded-md border border-border bg-surface-2">{src?<img src={src} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[8px] text-muted-foreground">EMPTY</div>}</div>)}</div></Card></>}
function MoodSections({selected,setSelected}:{selected:number;setSelected:(n:number)=>void}){return <><Card><SectionTitle>Choose a state</SectionTitle><div className="grid grid-cols-5 gap-2">{['Low','Soft','Neutral','Good','Bright'].map((x,i)=><button key={x} onClick={()=>setSelected(i+1)} className={`border p-4 text-xs ${selected===i+1?'bg-foreground text-background':'border-border'}`}>{x}<small className="mt-1 block">{i+1}/5</small></button>)}</div></Card><Card><SectionTitle>Today’s context</SectionTitle><textarea className="min-h-28 w-full resize-none rounded-md border border-border bg-background p-3 text-xs" placeholder="A few words, if useful…"/></Card></>}
function MusicSections({playing,setPlaying}:{playing:boolean;setPlaying:(b:boolean)=>void}){return <><Card className="bg-foreground text-background"><Eyebrow>TEMPO · MATCHED TO EFFORT</Eyebrow><h3 className="display mt-3 text-4xl">Slow Interior</h3><p className="mt-1 text-xs opacity-60">Aoi Field · Long Format</p><div className="mt-8"><MiniBars/></div><div className="mt-5 flex items-center justify-between"><span className="numeric text-[9px]">2:12</span><button onClick={()=>setPlaying(!playing)} className="grid size-12 place-items-center rounded-full bg-background text-foreground">{playing?'Ⅱ':'▶'}</button><span className="numeric text-[9px]">4:14</span></div></Card><Card><SectionTitle>Queue</SectionTitle>{['Slow Interior','Night Geometry','Nocturne Drift','Long Window'].map((x,i)=><button key={x} onClick={()=>setPlaying(true)} className="flex w-full justify-between border-b border-border py-4 text-xs last:border-0"><span>{x}</span><span className="numeric text-muted-foreground">{i+1}</span></button>)}</Card></>}
function NlpSections({query,setQuery}:{query:string;setQuery:(s:string)=>void}){const[result,setResult]=useState('');return <><Card><SectionTitle>Natural language</SectionTitle><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Say what you need…" className="flex-1 rounded-md border border-border bg-background px-3 text-xs"/><Button onClick={()=>setResult(query?`Structured: ${query}`:'Ready')}><Send size={13}/></Button></div>{result&&<div className="mt-5 rounded-md border border-border p-4 text-xs">{result}</div>}</Card><Card><SectionTitle>Extracted fields</SectionTitle>{['Intent','Time','Duration','Intensity','Location','Recovery','Calendar'].map((x,i)=><div key={x} className="flex justify-between border-b border-border py-3 text-xs last:border-0"><span>{x}</span><span className="numeric">{['WORKOUT','TODAY','20 min','MODERATE','OUTDOOR','SUPPORTED','OPEN'][i]}</span></div>)}</Card></>}
function NotificationSections(){const[enabled,setEnabled]=useState(true);return <Card><SectionTitle>Timeline</SectionTitle>{['Recovery window open','Mina S. set a 5K best','Watch firmware updated','Weekly insight ready'].map((x,i)=><div key={x} className="flex gap-4 border-b border-border py-5 last:border-0"><div className="grid size-8 shrink-0 place-items-center rounded-full border border-border">{i+1}</div><div className="flex-1"><Eyebrow>{['INSIGHT','SOCIAL','SYSTEM','COACH'][i]} · {i+1}h</Eyebrow><b className="mt-1 block text-sm">{x}</b><p className="mt-1 text-xs text-muted-foreground">A useful signal appeared in your record.</p></div></div>)}<div className="mt-4 flex items-center justify-between"><span className="text-xs">Smart timing</span><button onClick={()=>setEnabled(v=>!v)} className={`h-6 w-11 rounded-full p-1 ${enabled?'bg-foreground':'bg-surface-2'}`}><i className={`block size-4 rounded-full bg-background transition ${enabled?'translate-x-5':''}`}/></button></div></Card>}
function PedometerSections(){return <><Card><SectionTitle>Daily movement</SectionTitle><div className="numeric text-6xl">8,412</div><p className="mt-1 text-xs text-muted-foreground">steps today · 84% of goal</p><div className="mt-7"><MiniBars tall/></div></Card><Card><SectionTitle>By hour</SectionTitle>{['06:00','09:00','12:00','15:00','18:00','21:00'].map((x,i)=><div key={x} className="flex items-center gap-4 py-2 text-xs"><span className="numeric w-10">{x}</span><div className="h-2 flex-1 bg-surface-2"><i className="block h-full bg-foreground" style={{width:`${28+i*11}%`}}/></div></div>)}</Card></>}
function ProfileSections(){return <><Card><SectionTitle>Baseline</SectionTitle>{[['Age','34 years'],['Weight','178 lb'],['Height','5\' 10'],['Resting HR','58 bpm'],['Preferred activity','Running']].map(x=><div key={x[0]} className="flex justify-between border-b border-border py-4 text-xs last:border-0"><span>{x[0]}</span><span className="numeric">{x[1]}</span></div>)}</Card><Card><SectionTitle>Preferences</SectionTitle>{['Daily summary','Training suggestions','Social updates','Weekly export'].map(x=><div key={x} className="flex justify-between py-3 text-xs"><span>{x}</span><input type="checkbox" defaultChecked/></div>)}</Card></>}
function ScanSections({inputRef,onFiles,media,setNotice}:{inputRef:React.RefObject<HTMLInputElement|null>;onFiles:(f:FileList|null)=>void;media:string[];setNotice:(s:string)=>void}){return <><input ref={inputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>onFiles(e.target.files)}/><Card><SectionTitle>Camera</SectionTitle><button onClick={()=>inputRef.current?.click()} className="grid aspect-[16/9] w-full place-items-center rounded-md border border-dashed border-border bg-surface-2"><Camera size={28}/><span className="text-xs">Take a photo or choose an image</span></button>{media[0]&&<img src={media[0]} className="mt-4 max-h-80 w-full rounded-md object-contain"/>}</Card><Card><SectionTitle>Resolved meal</SectionTitle>{[['Energy','612 kcal'],['Protein','31 g'],['Carbohydrate','64 g'],['Fat','18 g']].map(x=><div key={x[0]} className="flex justify-between border-b border-border py-3 text-xs"><span>{x[0]}</span><span className="numeric">{x[1]}</span></div>)}<div className="mt-4"><Button onClick={()=>setNotice('Meal saved to diary')}>Save meal</Button></div></Card></>}
function SoundSections(){const[level,setLevel]=useState(61);return <><Card><SectionTitle>Ambient level</SectionTitle><div className="numeric text-6xl">{level}</div><span className="text-xs">dB · comfortable range</span><input className="mt-7 w-full" type="range" min="30" max="90" value={level} onChange={e=>setLevel(Number(e.target.value))}/><div className="mt-5 flex items-center gap-3"><Volume2 size={16}/><span className="text-xs">Focus mode {level<70?'healthy':'high'}</span></div></Card><Card><SectionTitle>Last 60 minutes</SectionTitle><MiniBars tall/></Card></>}
function StatsSections(){return <><Card><SectionTitle>Seven day trend</SectionTitle><MiniBars tall/><div className="mt-4 grid grid-cols-4 gap-3">{[['STEPS','9,140'],['WORKOUT','412'],['SLEEP','7:14'],['HRV','64']].map(x=><div key={x[0]}><Eyebrow>{x[0]}</Eyebrow><div className="numeric mt-1 text-xl">{x[1]}</div></div>)}</div></Card><Card><SectionTitle>Long line</SectionTitle><Line n={18}/></Card></>}
function VisionSections(){return <><Card><SectionTitle>Day so far · 08:31</SectionTitle>{['06:40 · Woke up','07:05 · Morning walk','07:45 · Breakfast scanned','08:30 · Focus block','18:00 · Strength session'].map(x=><div key={x} className="border-b border-border py-4 text-xs last:border-0">{x}</div>)}</Card><Card><SectionTitle>Targets · 4 active</SectionTitle>{[['Movement','84%'],['Protein','61%'],['Hydration','45%'],['Mindful minutes','30%']].map(x=><div key={x[0]} className="py-3"><div className="flex justify-between text-[9px]"><span>{x[0]}</span><span>{x[1]}</span></div><div className="mt-1 h-1 bg-surface-2"><i className="block h-full bg-foreground" style={{width:x[1]}}/></div></div>)}</Card></>}
function WorkoutSections(){return <><Card><SectionTitle>Session plan</SectionTitle>{['Warm-up · 8 min','Squat · 4 × 8','Split squat · 3 × 10','RDL · 3 × 10','Cooldown · 6 min'].map((x,i)=><div key={x} className="flex justify-between border-b border-border py-4 text-xs last:border-0"><span>{x}</span><input type="checkbox" defaultChecked={i<1}/></div>)}</Card><Card><SectionTitle>Load by set</SectionTitle><MiniBars tall/></Card></>}

function AssistantBody({query,setQuery,submit,notice,setNotice}:{query:string;setQuery:(s:string)=>void;submit:()=>void;notice:string;setNotice:(s:string)=>void}){const[messages,setMessages]=useState<string[]>([]);const send=()=>{if(!query.trim())return;setMessages(v=>[...v,query.trim(),'WK: I\'ve added that to the conversation.']);setQuery('');setNotice('Message added')};return <div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><Card><div className="flex gap-2"><span className="rounded-full bg-foreground px-3 py-1 text-[9px] text-background">CONTEXT ON</span><span className="rounded-full border border-border px-3 py-1 text-[9px]">SLEEP · HRV · LOAD · CALENDAR</span></div><div className="min-h-[480px] space-y-6 py-8">{messages.length===0&&<p className="display text-3xl">Ask about your week...</p>}{messages.map((m,i)=><div key={`${m}-${i}`} className={i%2===0?'ml-auto max-w-[75%] rounded-md bg-foreground p-4 text-sm text-background':'max-w-[85%] text-sm leading-7'}>{m}</div>)}</div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask about recovery, training, sleep..." className="min-h-10 flex-1 rounded-md border border-border bg-background px-3 text-xs"/><Button onClick={send}><Send size={14}/></Button></div></Card><aside className="space-y-6"><Card><Eyebrow>VOICE · READY</Eyebrow><div className="mt-5 flex items-center gap-4"><button className="grid size-16 place-items-center rounded-full bg-foreground text-background"><Mic size={22}/></button><div><h3 className="display text-2xl">Listening</h3><p className="text-xs text-muted-foreground">Speak naturally — pause to send</p></div></div></Card><Card><Eyebrow>STARTERS</Eyebrow><h3 className="display mt-2 text-2xl">Try asking</h3>{['Plan my week','Why did my sleep change?','Summarise my last 30 days','Build a mobility block'].map(x=><button key={x} onClick={()=>{setQuery(x);setNotice('Starter loaded')}} className="flex w-full justify-between border-b border-border py-4 text-xs last:border-0">{x}<span>↗</span></button>)}</Card></aside></div>}
function AuthBody(){const[email,setEmail]=useState('');const[mode,setMode]=useState('signin');const[notice,setNotice]=useState('');return <div className="fixed inset-0 grid bg-background lg:grid-cols-2"><div className="hidden bg-foreground p-12 text-background lg:flex lg:flex-col lg:justify-between"><Eyebrow>WK HEALTH · VISION UI</Eyebrow><h1 className="display max-w-xl text-6xl">Health, recorded with the patience of a notebook.</h1><p className="max-w-md text-sm leading-6 opacity-60">One continuous record of movement, meals, mood and sound — kept in a single restrained typographic system.</p><div className="numeric text-[9px] opacity-50">128k · 41M · 99.9</div></div><div className="flex items-center justify-center p-8"><div className="w-full max-w-md"><Eyebrow>{mode==='signin'?'SIGN IN':'CREATE ACCOUNT'}</Eyebrow><h2 className="display mt-2 text-5xl">{mode==='signin'?'Welcome back.':'Start your record.'}</h2><p className="mt-3 text-xs text-muted-foreground">Visual prototype — credentials are sent only when the backend is configured.</p><label className="mt-8 block text-[9px]">EMAIL</label><input value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 min-h-11 w-full border-b border-border bg-transparent text-sm outline-none" placeholder="you@example.com"/><div className="mt-6 flex gap-2"><Button onClick={()=>setNotice(email?'Continue requested':'Enter an email')}>Continue</Button><Button secondary onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Create account':'Sign in'}</Button></div><button className="mt-4 text-xs underline">Use passkey</button>{notice&&<p className="mt-4 text-xs">{notice}</p>}</div></div></div>}

export function PrototypeScreen({page}:{page:PageKey}){const c=C[page];return page==='auth'?<PageBody page={page}/>:<AppShell title={c.title}><div className="border-b border-border pb-6"><Eyebrow>{c.kicker}</Eyebrow><h1 className="display mt-2 text-5xl">{c.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{c.description}</p></div><div className="pt-6"><PageBody page={page}/></div></AppShell>}
