import { Link, useRouterState } from "@tanstack/react-router";
import { Activity, BarChart3, Bell, BookOpen, Camera, Cpu, Dumbbell, Footprints, Images, LayoutDashboard, Menu, MessageSquare, Music, ShieldCheck, Sparkles, Upload, User, Users, Volume2, Wallet, type LucideIcon } from "lucide-react";
import { useState, type ReactNode } from "react";
import { cn } from "@/lib/utils";
import { StatusIndicator } from "./ui";
type NavItem={to:string;label:string;icon:LucideIcon};
const NAV:{group:string;items:NavItem[]}[]=[{group:"Today",items:[{to:"/",label:"Overview",icon:LayoutDashboard},{to:"/scan",label:"Scan",icon:Camera},{to:"/diary",label:"Diary",icon:BookOpen},{to:"/mood",label:"Mood",icon:Activity}]},{group:"Movement",items:[{to:"/pedometer",label:"Pedometer",icon:Footprints},{to:"/workout",label:"Workout",icon:Dumbbell},{to:"/music",label:"Music",icon:Music},{to:"/sound-control",label:"Sound",icon:Volume2},{to:"/stats",label:"Stats",icon:BarChart3}]},{group:"Intelligence",items:[{to:"/assistant",label:"Assistant",icon:MessageSquare},{to:"/nlp",label:"Language",icon:Sparkles},{to:"/device-connect",label:"Devices",icon:Cpu}]},{group:"Life",items:[{to:"/budget",label:"Budget",icon:Wallet},{to:"/gallery",label:"Gallery",icon:Images},{to:"/friends",label:"Friends",icon:Users},{to:"/export",label:"Export",icon:Upload}]},{group:"Account",items:[{to:"/profile",label:"Profile",icon:User},{to:"/notifications",label:"Notifications",icon:Bell},{to:"/auth",label:"Access",icon:ShieldCheck}]}];
const DOCK:NavItem[]=[{to:"/",label:"Today",icon:LayoutDashboard},{to:"/scan",label:"Scan",icon:Camera},{to:"/stats",label:"Stats",icon:BarChart3},{to:"/music",label:"Music",icon:Music},{to:"/profile",label:"You",icon:User}];
export function WKMark({className}:{className?:string}){return <span className={cn("num grid size-8 shrink-0 place-items-center border border-foreground/70 text-[11px] tracking-tight",className)}>WK</span>}
export function Sidebar(){const pathname=useRouterState({select:s=>s.location.pathname});return <nav className="flex h-full min-h-0 flex-col"><div className="hairline-b flex items-center gap-3 px-5 py-5"><WKMark/><div><p className="display text-lg leading-none">WK Health</p><p className="label-xs mt-1.5">Vision UI</p></div></div><div className="min-h-0 flex-1 overflow-y-auto px-3 py-5">{NAV.map(section=><div key={section.group} className="mb-6"><p className="label-xs px-2 pb-2.5">{section.group}</p><ul>{section.items.map(item=>{const active=pathname===item.to;return <li key={item.to}><Link to={item.to} className={cn("group relative flex items-center gap-3 rounded-[3px] px-2 py-2 text-[13px] transition-colors",active?"bg-accent text-foreground":"text-ink-soft hover:bg-accent/60 hover:text-foreground")}>{active&&<span className="absolute top-1.5 bottom-1.5 -left-3 w-[2px] bg-signal"/>}<item.icon className="size-4 shrink-0" strokeWidth={1.5}/><span>{item.label}</span></Link></li>})}</ul></div>)}</div><div className="hairline-t px-5 py-4"><StatusIndicator label="Prototype · static data" state="live"/></div></nav>}
export function TopBar({title}:{title?:string}){const[open,setOpen]=useState(false);return <><header className="hairline-b sticky top-0 z-30 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 bg-background/85 px-5 py-3 backdrop-blur-md lg:px-10"><div className="flex items-center gap-3"><button type="button" aria-label="Open navigation" onClick={()=>setOpen(v=>!v)} className="grid size-8 place-items-center border border-border lg:hidden"><Menu className="size-4"/></button><span className="lg:hidden"><WKMark className="size-7"/></span><p className="num text-[11px] tracking-[0.14em] text-muted-foreground uppercase">{title??"WK Health"}</p></div><div className="flex items-center gap-4"><span className="num hidden text-[11px] text-muted-foreground sm:inline">08:31 · Thu</span><Link to="/sound-control" aria-label="Sound control" className="grid size-8 place-items-center text-ink-soft hover:text-foreground"><Volume2 className="size-4" strokeWidth={1.5}/></Link><Link to="/notifications" aria-label="Notifications" className="relative grid size-8 place-items-center text-ink-soft hover:text-foreground"><Bell className="size-4"/><span className="absolute top-1.5 right-1.5 size-1.5 rounded-full bg-signal"/></Link><Link to="/profile" className="num grid size-8 place-items-center rounded-full border border-border bg-sunken text-[11px]">WK</Link></div></header>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-foreground/25" onClick={()=>setOpen(false)}/><div className="absolute inset-y-0 left-0 w-[17rem] border-r border-border bg-background"><Sidebar/></div></div>}</>}
export function MobileDock(){const pathname=useRouterState({select:s=>s.location.pathname});return <nav className="hairline-t fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 bg-background/95 backdrop-blur-md lg:hidden">{DOCK.map(item=>{const active=pathname===item.to;return <Link key={item.to} to={item.to} className={cn("flex flex-col items-center gap-1.5 py-2.5",active?"text-foreground":"text-muted-foreground")}><item.icon className="size-[18px]"/><span className="num text-[9px] uppercase">{item.label}</span><span className={cn("h-[2px] w-5",active?"bg-signal":"bg-transparent")}/></Link>})}</nav>}
export function AppShell({children,title,wide}:{children:ReactNode;title?:string;wide?:boolean}){return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 hidden w-[17rem] border-r border-border bg-card lg:block"><Sidebar/></aside><div className="lg:pl-[17rem]"><TopBar title={title}/><main className={cn("px-5 pt-8 pb-28 lg:px-10 lg:pt-12 lg:pb-16",wide?"max-w-none":"mx-auto max-w-6xl")}>{children}</main></div><MobileDock/></div>}
