import { Link, useRouterState } from '@tanstack/react-router';
import { Activity, Bell, BookOpen, Camera, Dumbbell, Footprints, HeartPulse, MessageSquare, Music, Download, Settings, User, Users, Grid2X2, Wallet, Languages, Volume2, type LucideIcon } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { cn } from '@/lib/utils';
type NavItem={to:string;label:string;icon:LucideIcon};
const GROUPS:{title:string;items:NavItem[]}[]=[
 {title:'Today',items:[{to:'/overview',label:'Overview',icon:Activity},{to:'/scan',label:'Scan',icon:Camera},{to:'/diary',label:'Diary',icon:BookOpen},{to:'/mood',label:'Mood',icon:HeartPulse},{to:'/vision',label:'Vision',icon:Grid2X2}]},
 {title:'Movement',items:[{to:'/pedometer',label:'Pedometer',icon:Footprints},{to:'/workout',label:'Workout',icon:Dumbbell},{to:'/music',label:'Music',icon:Music},{to:'/stats',label:'Stats',icon:Activity}]},
 {title:'Intelligence',items:[{to:'/assistant',label:'Assistant',icon:MessageSquare},{to:'/nlp',label:'Language',icon:Languages},{to:'/device-connect',label:'Devices',icon:Settings},{to:'/sound-control',label:'Sound Control',icon:Volume2}]},
 {title:'Life',items:[{to:'/budget',label:'Budget',icon:Wallet},{to:'/gallery',label:'Gallery',icon:Grid2X2},{to:'/friends',label:'Friends',icon:Users},{to:'/export',label:'Export',icon:Download}]},
 {title:'Account',items:[{to:'/profile',label:'Profile',icon:User},{to:'/notifications',label:'Notifications',icon:Bell},{to:'/settings',label:'Access',icon:Settings}]},
];
function active(item:NavItem,p:string){return p===item.to||p.startsWith(`${item.to}/`)}
function NavLink({item,p,onNavigate}:{item:NavItem;p:string;onNavigate?:()=>void}){return <Link to={item.to} onClick={onNavigate} className={cn('group relative flex min-h-9 items-center gap-3 rounded-md px-3 py-2 text-[12px]',active(item,p)?'bg-surface-2 text-foreground':'text-muted-foreground hover:bg-surface-2 hover:text-foreground')}><item.icon className="size-3.5 shrink-0" strokeWidth={1.4}/><span className="truncate">{item.label}</span></Link>}
export function WKMark({className}:{className?:string}){return <span className={cn('numeric grid size-8 shrink-0 place-items-center rounded-md bg-foreground text-[10px] font-bold text-background',className)}>WK</span>}
export function Sidebar({onNavigate}:{onNavigate?:()=>void}){const p=useRouterState({select:s=>s.location.pathname});return <nav className="flex h-full min-h-0 flex-col"><div className="flex shrink-0 items-center gap-3 border-b border-border px-5 py-5"><WKMark/><div><p className="display text-xl leading-none">WK Health</p><p className="eyebrow mt-1.5">Vision OS</p></div></div><div className="min-h-0 flex-1 overflow-y-auto px-3 py-4">{GROUPS.map(g=><div key={g.title} className="mb-5"><p className="eyebrow px-2 pb-1.5 text-[8px]">{g.title}</p>{g.items.map(x=><NavLink key={x.to} item={x} p={p} onNavigate={onNavigate}/>)}</div>)}<div className="border-t border-dashed border-border pt-4"><NavLink item={{to:'/state-library',label:'State library',icon:Grid2X2}} p={p} onNavigate={onNavigate}/></div></div></nav>}
export function TopBar({title}:{title?:string}){const[open,setOpen]=useState(false);return <><header className="sticky top-0 z-30 h-[68px] border-b border-border bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-full max-w-[1280px] items-center justify-between gap-4 px-4 sm:px-6 lg:px-10"><div className="flex items-center gap-3"><button type="button" aria-label="Open navigation" onClick={()=>setOpen(true)} className="grid size-9 place-items-center rounded-md border border-border lg:hidden">☰</button><WKMark className="lg:hidden"/><div><p className="eyebrow hidden sm:block">WK Health Vision</p><p className="numeric text-[10px] uppercase tracking-[.14em] text-muted-foreground">{title??'Overview'}</p></div></div><div className="flex gap-2"><Link to="/notifications" className="relative grid size-9 place-items-center rounded-full border border-border"><Bell className="size-4"/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-signal"/></Link><Link to="/profile" className="numeric grid size-9 place-items-center rounded-full bg-foreground text-[9px] text-background">KY</Link></div></div></header>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-foreground/25" aria-label="Close" onClick={()=>setOpen(false)}/><div className="absolute inset-y-0 left-0 w-[20rem] border-r border-border bg-card"><Sidebar onNavigate={()=>setOpen(false)}/></div></div>}</>}
export function MobileDock(){const p=useRouterState({select:s=>s.location.pathname});const items=[GROUPS[0].items[0],GROUPS[0].items[1],GROUPS[1].items[3],{to:'/music',label:'Music',icon:Music},{to:'/profile',label:'You',icon:User}];return <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-background/96 pb-[env(safe-area-inset-bottom)] backdrop-blur-xl lg:hidden"><div className="grid grid-cols-5">{items.map(x=><Link key={x.to} to={x.to} className={cn('flex min-h-14 flex-col items-center justify-center gap-1',active(x,p)?'text-foreground':'text-muted-foreground')}><x.icon className="size-[16px]" strokeWidth={1.5}/><span className="numeric text-[8px] uppercase tracking-[.12em]">{x.label}</span></Link>)}</div></nav>}
export function AppShell({children,title,wide}:{children:ReactNode;title?:string;wide?:boolean}){return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[218px_minmax(0,1fr)]"><aside className="sticky top-0 hidden h-screen min-h-0 border-r border-border bg-card lg:flex"><Sidebar/></aside><div className="flex min-h-screen min-w-0 flex-col"><TopBar title={title}/><main className={cn('mx-auto w-full min-w-0 px-4 pt-7 pb-24 sm:px-6 lg:px-10 lg:pt-8 lg:pb-14',wide?'max-w-none':'max-w-[1280px]')}>{children}</main></div><MobileDock/></div>}
