import { Link, useRouterState } from '@tanstack/react-router';
import { Bell, BarChart3, BookOpen, Camera, Dumbbell, Footprints, HeartPulse, Headphones, MessageSquare, Music, Navigation, ScanBarcode, Settings, Sparkles, User, Users, Grid2X2, LogIn, type LucideIcon } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { cn } from '@/lib/utils';
type NavItem={to:string;label:string;icon:LucideIcon};
const PRODUCT:NavItem[]=[{to:'/scan',label:'Scan',icon:Camera},{to:'/music',label:'Music',icon:Music},{to:'/stats',label:'Stats',icon:BarChart3},{to:'/you',label:'You',icon:User}];
const SOURCE:NavItem[]=[{to:'/assistant',label:'Assistant',icon:MessageSquare},{to:'/activity',label:'Activity',icon:HeartPulse},{to:'/navigate',label:'Navigate',icon:Navigation},{to:'/friends',label:'Friends',icon:Users},{to:'/notifications',label:'Notifications',icon:Bell},{to:'/diary',label:'Diary',icon:BookOpen},{to:'/mood',label:'Mood',icon:HeartPulse},{to:'/pedometer',label:'Pedometer',icon:Footprints},{to:'/workout',label:'Workout',icon:Dumbbell},{to:'/sound',label:'Sound',icon:Headphones},{to:'/profile',label:'Profile',icon:User},{to:'/settings',label:'Settings',icon:Settings},{to:'/state-library',label:'State library',icon:Grid2X2},{to:'/vision',label:'Vision UI',icon:Sparkles},{to:'/auth',label:'Sign in',icon:LogIn}];
function active(item:NavItem,p:string){return p===item.to||p.startsWith(`${item.to}/`)}
function NavLink({item,p,onNavigate}:{item:NavItem;p:string;onNavigate?:()=>void}){return <Link to={item.to} onClick={onNavigate} className={cn('group relative flex min-h-10 items-center gap-3 rounded-md px-3 py-2 text-[13px]',active(item,p)?'bg-foreground text-background':'text-muted-foreground hover:bg-accent hover:text-foreground')}><item.icon className="size-4 shrink-0" strokeWidth={1.5}/><span className="truncate">{item.label}</span></Link>}
export function WKMark({className}:{className?:string}){return <span className={cn('numeric grid size-8 shrink-0 place-items-center rounded-md bg-foreground text-[10px] font-bold text-background',className)}>WK</span>}
export function Sidebar({onNavigate}:{onNavigate?:()=>void}){const p=useRouterState({select:s=>s.location.pathname});return <nav className="flex h-full min-h-0 flex-col"><div className="flex shrink-0 items-center gap-3 border-b border-border px-5 py-5"><WKMark/><div><p className="display text-xl leading-none">WK Health</p><p className="eyebrow mt-1.5">Health OS · Live</p></div></div><div className="min-h-0 flex-1 overflow-y-auto px-3 py-4"><p className="eyebrow px-2 pb-2">Product · 4</p>{PRODUCT.map(x=><NavLink key={x.to} item={x} p={p} onNavigate={onNavigate}/>)}<p className="eyebrow px-2 pb-2 pt-7">Source pages</p>{SOURCE.map(x=><NavLink key={x.to} item={x} p={p} onNavigate={onNavigate}/>)}</div></nav>}
export function TopBar({title}:{title?:string}){const[open,setOpen]=useState(false);return <><header className="sticky top-0 z-30 h-[68px] border-b border-border bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-full max-w-[1280px] items-center justify-between gap-4 px-4 sm:px-6 lg:px-10"><div className="flex items-center gap-3"><button type="button" aria-label="Open navigation" onClick={()=>setOpen(true)} className="grid size-9 place-items-center rounded-md border border-border lg:hidden">☰</button><WKMark className="lg:hidden"/><div><p className="eyebrow hidden sm:block">WK Health</p><p className="numeric text-[10px] uppercase tracking-[.14em] text-muted-foreground">{title??'You'}</p></div></div><div className="flex gap-2"><Link to="/notifications" className="grid size-9 place-items-center rounded-md border border-border"><Bell className="size-4"/></Link><Link to="/you" className="numeric grid size-9 place-items-center rounded-md bg-foreground text-[9px] text-background">YOU</Link></div></div></header>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-foreground/25" aria-label="Close" onClick={()=>setOpen(false)}/><div className="absolute inset-y-0 left-0 w-[20rem] border-r border-border bg-card"><Sidebar onNavigate={()=>setOpen(false)}/></div></div>}</>}
export function MobileDock(){const p=useRouterState({select:s=>s.location.pathname});return <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-background/96 pb-[env(safe-area-inset-bottom)] backdrop-blur-xl lg:hidden"><div className="grid grid-cols-4">{PRODUCT.map(x=><Link key={x.to} to={x.to} className={cn('flex min-h-16 flex-col items-center justify-center gap-1',active(x,p)?'text-foreground':'text-muted-foreground')}><x.icon className="size-[17px]"/><span className="numeric text-[8px] uppercase tracking-[.12em]">{x.label}</span></Link>)}</div></nav>}
export function AppShell({children,title,wide}:{children:ReactNode;title?:string;wide?:boolean}){return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[272px_minmax(0,1fr)]"><aside className="sticky top-0 hidden h-screen min-h-0 border-r border-border bg-card lg:flex"><Sidebar/></aside><div className="flex min-h-screen min-w-0 flex-col"><TopBar title={title}/><main className={cn('mx-auto w-full min-w-0 px-4 pt-7 pb-28 sm:px-6 lg:px-10 lg:pt-10 lg:pb-16',wide?'max-w-none':'max-w-[1280px]')}>{children}</main></div><MobileDock/></div>}
