import { cn } from "@/lib/utils";
import { AlertTriangle, Check, Inbox, Loader2, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) {
  return <header className="hairline-b grid grid-cols-[minmax(0,1fr)_auto] items-end gap-6 pb-8 sm:flex sm:flex-wrap sm:justify-between"><div className="min-w-0 max-w-2xl">{eyebrow ? <p className="label-xs mb-4">{eyebrow}</p> : null}<h1 className="display text-4xl sm:text-5xl">{title}</h1>{description ? <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{description}</p> : null}</div>{actions ? <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div> : null}</header>;
}
export function SectionHeader({ title, meta, actions }: { title: string; meta?: string; actions?: ReactNode }) {
  return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-baseline gap-4 pb-3"><div className="flex min-w-0 items-baseline gap-3"><h2 className="truncate text-[12px] font-semibold tracking-[0.13em] uppercase">{title}</h2>{meta ? <span className="num shrink-0 text-[11px] text-muted-foreground">{meta}</span> : null}</div>{actions ? <div className="flex shrink-0 items-center gap-2">{actions}</div> : null}</div>;
}
export function Panel({ title, meta, actions, children, className, bare, tone = "default" }: { title?: string; meta?: string; actions?: ReactNode; children?: ReactNode; className?: string; bare?: boolean; tone?: "default" | "sunken" | "ink" }) {
  return <section className={cn("border border-border", tone === "default" && "bg-card shadow-panel", tone === "sunken" && "bg-sunken", tone === "ink" && "bg-primary text-primary-foreground", className)}>{title || actions ? <div className="hairline-b grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-5 py-3.5"><div className="flex min-w-0 items-baseline gap-3"><h3 className="truncate text-[12px] font-semibold tracking-[0.13em] uppercase">{title}</h3>{meta ? <span className="num shrink-0 text-[11px] opacity-60">{meta}</span> : null}</div>{actions ? <div className="flex shrink-0 items-center gap-2">{actions}</div> : null}</div> : null}<div className={cn(!bare && "p-5")}>{children}</div></section>;
}
export function Metric({ label, value, unit, delta, size = "md", footnote, className }: { label: string; value: string; unit?: string; delta?: string; size?: "sm" | "md" | "lg" | "xl"; footnote?: string; className?: string }) {
  const sizes = { sm: "text-2xl", md: "text-3xl sm:text-4xl", lg: "text-4xl sm:text-5xl", xl: "text-6xl sm:text-7xl" } as const;
  return <div className={cn("min-w-0", className)}><p className="label-xs">{label}</p><div className="mt-3 flex flex-wrap items-baseline gap-x-2 gap-y-1"><span className={cn("num leading-none", sizes[size])}>{value}</span>{unit ? <span className="num text-xs whitespace-nowrap text-muted-foreground">{unit}</span> : null}{delta ? <span className="num text-[11px] whitespace-nowrap text-signal">{delta}</span> : null}</div>{footnote ? <p className="mt-2 text-xs leading-relaxed text-muted-foreground">{footnote}</p> : null}</div>;
}
export function DataRow({ label, value, meta, icon: Icon, right, className }: { label: string; value?: string; meta?: string; icon?: LucideIcon; right?: ReactNode; className?: string }) {
  return <div className={cn("hairline-b grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 py-3 last:border-b-0", className)}><div className="flex min-w-0 items-center gap-3">{Icon ? <Icon className="size-4 shrink-0 text-muted-foreground" strokeWidth={1.5} /> : null}<div className="min-w-0"><p className="truncate text-sm">{label}</p>{meta ? <p className="num mt-0.5 text-[11px] text-muted-foreground">{meta}</p> : null}</div></div><div className="flex shrink-0 items-center gap-3">{value ? <span className="num text-sm">{value}</span> : null}{right}</div></div>;
}
export function Timeline({ items }: { items: { time: string; title: string; detail?: string; state?: "done" | "active" | "idle" }[] }) {
  return <ol className="relative">{items.map((item, i) => <li key={i} className="grid grid-cols-[68px_20px_minmax(0,1fr)] gap-3 pb-6 last:pb-0"><span className="num pt-0.5 text-[11px] text-muted-foreground">{item.time}</span><span className="relative flex justify-center"><span className={cn("z-10 mt-1.5 size-2 shrink-0 rounded-full", item.state === "active" ? "bg-signal" : item.state === "done" ? "bg-foreground" : "border border-border bg-background")} />{i < items.length - 1 ? <span className="absolute top-3 bottom-[-1.5rem] w-px bg-hairline" /> : null}</span><div className="min-w-0"><p className="text-sm leading-snug">{item.title}</p>{item.detail ? <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{item.detail}</p> : null}</div></li>)}</ol>;
}
export function Action({ children, icon: Icon, variant = "ghost", size = "md", className, ...rest }: React.ButtonHTMLAttributes<HTMLButtonElement> & { icon?: LucideIcon; variant?: "ghost" | "solid" | "outline" | "signal"; size?: "sm" | "md" | "lg" }) {
  return <button type="button" className={cn("inline-flex items-center justify-center gap-2 rounded-[3px] font-medium tracking-tight whitespace-nowrap transition-colors", size === "sm" && "h-7 px-2.5 text-[11px]", size === "md" && "h-9 px-3.5 text-[12px]", size === "lg" && "h-11 px-5 text-sm", variant === "ghost" && "text-ink-soft hover:bg-accent hover:text-foreground", variant === "outline" && "border border-border hover:bg-accent", variant === "solid" && "bg-primary text-primary-foreground hover:bg-primary/90", variant === "signal" && "bg-signal text-signal-foreground hover:bg-signal/90", className)} {...rest}>{Icon ? <Icon className="size-3.5 shrink-0" strokeWidth={1.75} /> : null}{children}</button>;
}
export function StatusIndicator({ label, state = "idle", className }: { label: string; state?: "live" | "idle" | "warn" | "off"; className?: string }) {
  return <span className={cn("inline-flex items-center gap-2 whitespace-nowrap", className)}><span className="relative flex size-2 items-center justify-center"><span className={cn("size-2 rounded-full", state === "live" && "bg-signal", state === "idle" && "bg-foreground/45", state === "warn" && "bg-destructive", state === "off" && "border border-border bg-transparent")} />{state === "live" ? <span className="absolute size-2 animate-ping rounded-full bg-signal/60" /> : null}</span><span className="label-xs">{label}</span></span>;
}
function StateFrame({ icon, title, body, action }: { icon: ReactNode; title: string; body?: string; action?: ReactNode }) { return <div className="flex flex-col items-center justify-center px-6 py-12 text-center"><div className="mb-5 grid size-10 shrink-0 place-items-center border border-border text-muted-foreground">{icon}</div><p className="display text-2xl">{title}</p>{body ? <p className="mt-2 max-w-sm text-xs leading-relaxed text-muted-foreground">{body}</p> : null}{action ? <div className="mt-6">{action}</div> : null}</div>; }
export function LoadingState({ label = "Loading" }: { label?: string }) { return <StateFrame icon={<Loader2 className="size-4 animate-spin" strokeWidth={1.5} />} title={label} body="Preparing the presentation layer. No data is being fetched in this prototype." />; }
export function ErrorState({ label = "Something interrupted", body = "This is a visual error state. Retrying is presentational only." }: { label?: string; body?: string }) { return <StateFrame icon={<AlertTriangle className="size-4" strokeWidth={1.5} />} title={label} body={body} action={<Action variant="outline">Try again</Action>} />; }
export function EmptyState({ label = "Nothing here yet", body = "Entries you record will appear in this space.", action }: { label?: string; body?: string; action?: ReactNode }) { return <StateFrame icon={<Inbox className="size-4" strokeWidth={1.5} />} title={label} body={body} action={action} />; }
export function SuccessState({ label = "Saved", body = "Your entry has been recorded in the visual timeline." }: { label?: string; body?: string }) { return <StateFrame icon={<Check className="size-4 text-signal" strokeWidth={1.5} />} title={label} body={body} />; }
export function ImagePlaceholder({ label, ratio = "4/3", className, mark }: { label?: string; ratio?: string; className?: string; mark?: ReactNode }) { return <div style={{ aspectRatio: ratio }} className={cn("relative w-full overflow-hidden border border-border bg-sunken", className)}><div className="absolute inset-0 opacity-[0.5]" style={{ backgroundImage: "repeating-linear-gradient(135deg, var(--hairline) 0 1px, transparent 1px 9px)" }} /><div className="absolute inset-0 grid place-items-center">{mark ?? <span className="size-6 border border-foreground/25 rounded-full" />}</div>{label ? <span className="label-xs absolute bottom-2.5 left-3">{label}</span> : null}</div>; }
export function AudioWaveform({ bars = 64, active = 0.55, height = 64, seed = 3, className }: { bars?: number; active?: number; height?: number; seed?: number; className?: string }) {
  const values = Array.from({ length: bars }, (_, i) => { const v = Math.abs(Math.sin((i + seed) * 1.7) * 0.55 + Math.sin((i + seed) * 0.41) * 0.45); return 0.14 + v * 0.86; });
  return <div className={cn("flex items-end gap-[2px]", className)} style={{ height }} aria-hidden="true">{values.map((v, i) => <span key={i} className={cn("flex-1 rounded-[1px]", i / bars <= active ? "bg-foreground" : "bg-foreground/18")} style={{ height: `${Math.round(v * 100)}%` }} />)}</div>;
}
export function ProgressIndicator({ value, label, right, tone = "ink" }: { value: number; label?: string; right?: string; tone?: "ink" | "signal" }) { return <div className="min-w-0">{label || right ? <div className="mb-2.5 flex items-baseline justify-between gap-3">{label ? <span className="label-xs truncate">{label}</span> : null}{right ? <span className="num text-[11px]">{right}</span> : null}</div> : null}<div className="h-[3px] w-full bg-foreground/10"><div className={cn("h-full", tone === "signal" ? "bg-signal" : "bg-foreground")} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div></div>; }
export function Mono({ children, className }: { children: ReactNode; className?: string }) { return <span className={cn("num text-[11px] text-muted-foreground", className)}>{children}</span>; }
export function Initials({ name, className }: { name: string; className?: string }) { const initials = name.split(" ").map((n) => n[0]).slice(0, 2).join(""); return <span className={cn("num grid size-8 shrink-0 place-items-center rounded-full border border-border bg-sunken text-[11px]", className)}>{initials}</span>; }
export function Grid({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("grid gap-6", className)}>{children}</div>; }
