import { useCallback, useEffect, useMemo, useState, type ComponentType } from "react";
import { Activity, Bell, BookOpen, Check, Download, Footprints, HeartPulse, Images, Loader2, MessageSquare, Music, RefreshCw, Search, Send, ShieldCheck, Smartphone, Sparkles, Users, Wallet, Dumbbell } from "lucide-react";
import { AppShell } from "@/components/wk/shell";
import { Action, DataRow, EmptyState, ErrorState, LoadingState, Metric, Panel, PageHeader, ProgressIndicator, SectionHeader, StatusIndicator } from "@/components/wk/ui";
import { apiFetch, apiNlpAnalyze, apiUpdateMe, todayISO, type ApiUser } from "@/lib/api";

type Json=Record<string,unknown>; type Icon=ComponentType<{className?:string;strokeWidth?:number}>;
type Config={eyebrow:string;title:string;description:string;icon:Icon;get:string;action?:"chat"|"nlp"|"profile"|"export"|"friend"|"notify"|"checkin"|"record";label:string};
const configs:Record<string,Config>={
 mood:{eyebrow:"Mind / Mood",title:"Check in with yourself.",description:"บันทึกอารมณ์และรับคำแนะนำจากบัญชีจริง",icon:HeartPulse,get:"/api/mood/list",action:"checkin",label:"อารมณ์"},
 music:{eyebrow:"Environment / Sound",title:"Sound for the moment.",description:"ข้อมูลเสียงและประวัติการฟังของคุณ",icon:Music,get:"/api/music",action:"record",label:"เพลง"},
 workout:{eyebrow:"Movement / Training",title:"Train with intention.",description:"แผนและประวัติการออกกำลังกาย",icon:Dumbbell,get:"/api/workout",action:"record",label:"การออกกำลัง"},
 budget:{eyebrow:"Life / Budget",title:"Health spending, made simple.",description:"ข้อมูลแผนงบประมาณและค่าใช้จ่ายสุขภาพ",icon:Wallet,get:"/api/budget",action:"record",label:"งบประมาณ"},
 "device-connect":{eyebrow:"Intelligence / Devices",title:"Bring every signal together.",description:"ตรวจสอบข้อมูลจากอุปกรณ์ที่เชื่อมต่อ",icon:Smartphone,get:"/api/body",action:"record",label:"อุปกรณ์"},
 assistant:{eyebrow:"Intelligence / Assistant",title:"Your health, with an assistant.",description:"ถามระบบโดยใช้บริบทสุขภาพของบัญชี",icon:MessageSquare,get:"/api/assistant/history?limit=50",action:"chat",label:"AI"},
 nlp:{eyebrow:"Intelligence / Language",title:"Turn words into health data.",description:"แปลงข้อความอาหารเป็นข้อมูลโภชนาการ",icon:Sparkles,get:"/api/nlp",action:"nlp",label:"ภาษา"},
 pedometer:{eyebrow:"Movement / Pedometer",title:"Every step counts.",description:"ก้าว ระยะทาง และการเคลื่อนไหว",icon:Footprints,get:"/api/pedometer",action:"record",label:"ก้าว"},
 gallery:{eyebrow:"Life / Gallery",title:"Your health memories.",description:"ข้อมูลแกลเลอรีและบันทึกภาพของคุณ",icon:Images,get:"/api/gallery",action:"record",label:"แกลเลอรี"},
 friends:{eyebrow:"Life / Friends",title:"Stay healthy together.",description:"เพื่อน รหัสเชิญ และกิจกรรมร่วมกัน",icon:Users,get:"/api/friends",action:"friend",label:"เพื่อน"},
 export:{eyebrow:"Account / Export",title:"Your data belongs to you.",description:"สร้างและตรวจสอบประวัติการส่งออกข้อมูล",icon:Download,get:"/api/export/history",action:"export",label:"ส่งออก"},
 profile:{eyebrow:"Account / Profile",title:"Make the system yours.",description:"ข้อมูลส่วนตัวและเป้าหมายของบัญชี",icon:ShieldCheck,get:"/api/auth/me",action:"profile",label:"โปรไฟล์"},
 notifications:{eyebrow:"Account / Notifications",title:"Only what matters.",description:"ตั้งค่าการแจ้งเตือนและช่วงเวลาเงียบ",icon:Bell,get:"/api/notifications/settings",action:"notify",label:"แจ้งเตือน"},
 diary:{eyebrow:"Today / Diary",title:"Your day, recorded clearly.",description:"อาหารของวันนี้จากบัญชีจริง",icon:BookOpen,get:"/api/diary?date=",action:"record",label:"Diary"}
};
function asRows(v:unknown):Json[]{if(Array.isArray(v))return v.filter((x):x is Json=>!!x&&typeof x==="object");if(v&&typeof v==="object"){const o=v as Json;for(const k of ["items","data","entries","rows","history","messages","friends","records","notifications","moods"]){if(Array.isArray(o[k]))return asRows(o[k]);}return [o]}return []}
const str=(v:unknown)=>v==null||v===""?"—":typeof v==="object"?"ข้อมูล":String(v);
const rowName=(r:Json,i:number)=>str(r.name??r.title??r.food_name??r.foodName??r.label??r.type??`รายการ ${i+1}`);
const rowValue=(r:Json)=>str(r.value??r.status??r.calories??r.kcal??r.steps??r.created_at??r.createdAt??r.date??"บันทึกแล้ว");

export function VisionPage({page}:{page:string}){
 const c=configs[page]??{eyebrow:"WK Health",title:"Health workspace.",description:"ข้อมูลจากระบบ WK Health",icon:Activity,get:"/api/stats/today",label:"ระบบ"};
 const Icon=c.icon; const[data,setData]=useState<unknown>(); const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[q,setQ]=useState(""); const[input,setInput]=useState(""); const[reply,setReply]=useState(""); const[busy,setBusy]=useState(false); const[form,setForm]=useState<Json>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const ep=c.get.endsWith("=")?c.get+encodeURIComponent(todayISO()):c.get;const d=await apiFetch(ep);setData(d);if(page==="profile"){const u=((d as Json)?.user??(d as Json)?.profile??d) as Json;setForm({name:u.name??u.displayName??"",weightKg:u.weightKg??u.weight_kg??"",heightCm:u.heightCm??u.height_cm??"",goalKcal:u.goalKcal??u.goal_kcal??""});}}catch(e){setError(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setLoading(false)}},[c.get,page]);
 useEffect(()=>{void load()},[load]);
 const list=useMemo(()=>asRows(data).filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[data,q]);
 async function submit(){if(!input.trim())return;setBusy(true);setError("");try{if(c.action==="chat"){const r=await apiFetch<Json>("/api/assistant/chat",{method:"POST",body:{message:input.trim()}});setReply(str(r.reply??r.message??r.data));}else if(c.action==="nlp"){const r=await apiNlpAnalyze(input.trim());setReply(r.length?`พบ ${r.length} รายการ · ${r.map(x=>`${x.name} ${x.kcal} kcal`).join(" · ")}`:"ไม่พบรายการที่ชัดเจน");}else if(c.action==="checkin"){const r=await apiFetch<Json>("/api/mood/checkin",{method:"POST",body:{mood:input.trim(),date:todayISO()}});setReply(str(r.message??r.result??"เช็กอินสำเร็จ"));await load();}else if(c.action==="friend"){const r=await apiFetch<Json>("/api/friends/add",{method:"POST",body:{code:input.trim()}});setReply(str(r.message??"เพิ่มเพื่อนสำเร็จ"));await load();}else{const r=await apiFetch<Json>(c.get,{method:"POST",body:{text:input.trim(),date:todayISO()}});setReply(str(r.message??r.result??"บันทึกสำเร็จ"));await load();}setInput("")}catch(e){setError(e instanceof Error?e.message:"ดำเนินการไม่สำเร็จ")}finally{setBusy(false)}}
 async function saveProfile(){setBusy(true);setError("");try{await apiUpdateMe({name:String(form.name??""),weightKg:Number(form.weightKg)||undefined,heightCm:Number(form.heightCm)||undefined,goalKcal:Number(form.goalKcal)||undefined});setReply("บันทึกโปรไฟล์แล้ว");await load()}catch(e){setError(e instanceof Error?e.message:"บันทึกโปรไฟล์ไม่สำเร็จ")}finally{setBusy(false)}}
 async function exportData(){setBusy(true);setError("");try{const r=await apiFetch<Json>("/api/export",{method:"POST",body:{format:"csv",range:"30d"}});setReply(str(r.downloadUrl??r.message??"สร้างไฟล์แล้ว"));await load()}catch(e){setError(e instanceof Error?e.message:"สร้างไฟล์ไม่สำเร็จ")}finally{setBusy(false)}}
 async function notify(patch:Json){setBusy(true);setError("");try{await apiFetch("/api/notifications/settings",{method:"PATCH",body:patch});setReply("บันทึกการตั้งค่าแล้ว");await load()}catch(e){setError(e instanceof Error?e.message:"บันทึกการแจ้งเตือนไม่สำเร็จ")}finally{setBusy(false)}}
 const connection=error?0:100;
 return <AppShell title={c.label}><PageHeader eyebrow={c.eyebrow} title={c.title} description={c.description} actions={<div className="flex items-center gap-2"><StatusIndicator label={loading?"SYNCING":"LIVE"} state={loading?"live":error?"warn":"live"}/><Action icon={RefreshCw} size="sm" onClick={()=>void load()} disabled={loading}/></div>}/>
 <section className="hairline-b grid grid-cols-2 gap-y-8 py-9 lg:grid-cols-4"><Metric label="Records" value={loading?"—":String(list.length)} size="lg"/><Metric label="Backend" value={`${connection}%`} unit="connected" size="lg"/><Metric label="Today" value={todayISO()} size="sm"/><Metric label="Module" value={c.label} size="sm"/></section>
 <div className="grid gap-8 py-9 lg:grid-cols-[1.4fr_.6fr]"><main className="space-y-8"><Panel tone="ink" className="min-h-[190px] border-transparent"><div className="flex h-full flex-col justify-between gap-10"><div className="flex justify-between"><Icon className="size-5" strokeWidth={1.4}/><span className="num text-[10px] opacity-60">{c.label.toUpperCase()} / LIVE</span></div><div><p className="display text-3xl sm:text-4xl">ระบบ {c.label} พร้อมทำงาน.</p><p className="mt-3 max-w-2xl text-sm leading-6 opacity-65">สถานะและข้อมูลด้านล่างมาจาก backend ของบัญชีปัจจุบัน</p></div></div></Panel>
 {c.action==="profile"?<Panel title="ข้อมูลโปรไฟล์"><div className="grid gap-5 sm:grid-cols-2">{[["name","ชื่อ"],["weightKg","น้ำหนัก kg"],["heightCm","ส่วนสูง cm"],["goalKcal","เป้าหมาย kcal"]].map(([k,l])=><label key={k} className="text-xs"><span className="label-xs mb-2 block">{l}</span><input value={String(form[k]??"")} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))} className="w-full border-b border-border bg-transparent py-2 outline-none"/></label>)}</div><div className="mt-6"><Action variant="solid" icon={Check} onClick={()=>void saveProfile()} disabled={busy}>บันทึกโปรไฟล์</Action></div></Panel>:c.action==="notify"?<Panel title="การแจ้งเตือน"><div className="grid gap-1">{[["mealReminder","เตือนมื้ออาหาร"],["waterReminder","เตือนดื่มน้ำ"],["streakRisk","เตือน streak"],["weeklyInsight","Weekly insight"],["smartTiming","Smart timing"]].map(([k,l])=>{const current=Boolean((data as Json)?.[k]);return <button key={k} onClick={()=>void notify({[k]:!current})} className="hairline-b flex items-center justify-between py-4 text-left"><span className="text-sm">{l}</span><span className={`size-4 rounded-full border ${current?"border-signal bg-signal":"border-border"}`}/></button>})}</div></Panel>:c.action==="export"?<Panel title="Export"><div className="flex flex-wrap gap-2"><Action icon={Download} variant="solid" onClick={()=>void exportData()} disabled={busy}>สร้าง CSV 30 วัน</Action><Action icon={RefreshCw} onClick={()=>void load()} disabled={busy}>รีเฟรชประวัติ</Action></div>{reply?<p className="mt-4 break-all text-xs text-muted-foreground">{reply}</p>:null}</Panel>:c.action?<Panel title={c.action==="chat"?"ถาม WK Health":c.action==="nlp"?"วิเคราะห์ข้อความ":c.action==="friend"?"เพิ่มเพื่อนด้วยรหัส":c.action==="checkin"?"เช็กอินอารมณ์":"บันทึกข้อมูล"}><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void submit()}} placeholder={c.action==="friend"?"ใส่ invite code…":c.action==="checkin"?"เช่น happy / stressed / tired…":c.action==="nlp"?"เช่น ข้าว 1 จาน ไข่ 2 ฟอง…":"พิมพ์ข้อมูลที่ต้องการส่งเข้าสู่ระบบ…"} className="min-w-0 flex-1 border-b border-border bg-transparent py-3 text-sm outline-none"/><Action icon={busy?Loader2:Send} variant="solid" onClick={()=>void submit()} disabled={busy||!input.trim()}>ส่ง</Action></div>{reply?<div className="mt-5 border-l-2 border-signal pl-4 text-sm leading-6 break-words">{reply}</div>:null}</Panel>:null}
 {error?<ErrorState label="เชื่อมต่อระบบไม่สำเร็จ" body={error}/>:loading?<LoadingState label="กำลังซิงก์"/>:list.length===0?<EmptyState label="ยังไม่มีข้อมูล" body="ข้อมูลจากบัญชีจะปรากฏที่นี่เมื่อมีการใช้งาน"/>:<div><SectionHeader title="ข้อมูลล่าสุด" meta={`${list.length} รายการ`} actions={<div className="relative"><Search className="absolute left-2 top-2.5 size-3.5 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา" className="w-36 border-b border-border bg-transparent py-2 pl-7 text-xs outline-none"/></div>}/><Panel bare className="px-5 py-2">{list.slice(0,30).map((r,i)=><DataRow key={i} label={rowName(r,i)} value={rowValue(r)} meta={str(r.date??r.time??r.created_at??r.createdAt)} icon={i===0?<Check/>:undefined}/>)}</Panel></div>}</main>
 <aside className="space-y-8"><Panel title="Health signal"><Metric label="Connection" value={`${connection}%`} size="xl"/><div className="mt-6"><ProgressIndicator label="Backend" right={error?"Offline":"Connected"} value={connection} tone="signal"/></div></Panel><Panel title="Quick actions"><div className="grid grid-cols-2">{[["/","Overview",Activity],["/scan","Scan",Sparkles],["/stats","Stats",Activity],["/diary","Diary",BookOpen]].map(([to,label,I])=>{const Q=I as Icon;return <a key={String(to)} href={String(to)} className="hairline-b flex flex-col gap-4 border-r border-hairline p-4 text-sm hover:bg-accent"><Q className="size-4 text-muted-foreground"/><span>{String(label)}</span></a>})}</div></Panel></aside></div></AppShell>;
}
