import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { AppShell } from './shell';
import { apiFetch, ApiError } from '@/lib/api';
const Panel=({children,className='' }:{children:ReactNode;className?:string})=><section className={`panel p-5 ${className}`}>{children}</section>;
const Eyebrow=({children}:{children:ReactNode})=><p className="eyebrow text-[8px]">{children}</p>;
const n=(v:unknown,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d};
const pick=(o:any,...keys:string[])=>{for(const k of keys){if(o?.[k]!==undefined&&o?.[k]!==null)return o[k]}return null};
const fallbackMood='Live health data is not available right now.';
function fmtHrsMin(totalMin:number){const h=Math.floor(totalMin/60);const m=Math.round(totalMin%60);return `${h}:${String(m).padStart(2,'0')}`;}
export function VisionOverview(){
 const [today,setToday]=useState<any>(null); const [diary,setDiary]=useState<any[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;(async()=>{setLoading(true);setError('');try{const date=new Date().toISOString().slice(0,10);const [statsRes,diaryRes]=await Promise.allSettled([apiFetch('/api/stats/today'),apiFetch(`/api/diary?date=${date}`)]);if(cancelled)return;if(statsRes.status==='fulfilled')setToday((statsRes.value as any)?.data??statsRes.value);else setError(statsRes.reason instanceof ApiError?statsRes.reason.message:'Live health data unavailable');if(diaryRes.status==='fulfilled'){const d=diaryRes.value as any;setDiary(Array.isArray(d)?d:Array.isArray(d?.items)?d.items:Array.isArray(d?.entries)?d.entries:[]);}}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
 const metrics=useMemo(()=>{const steps=pick(today,'steps','activitySteps');const calories=pick(today,'calories','eaten','totalCalories');const restingHr=pick(today,'restingHr','resting_hr');const sleepMin=pick(today,'sleepMinutes','sleep_minutes');return [['STEPS',steps!=null?Number(steps).toLocaleString():'—',steps!=null?'today':'not available'],['ENERGY',calories!=null?Math.round(n(calories)).toLocaleString():'—',calories!=null?'kcal · live':'not available'],['RESTING HR',restingHr!=null?String(Math.round(n(restingHr))):'—',restingHr!=null?'bpm · live':'not available'],['SLEEP',sleepMin!=null?fmtHrsMin(n(sleepMin)):'—',sleepMin!=null?'hrs · live':'not available']];},[today]);
 const timeline=useMemo(()=>{if(!diary.length)return null;return diary.slice(0,5).map((m:any,i:number)=>({time:pick(m,'time','loggedAt','createdAt')?String(pick(m,'time','loggedAt','createdAt')).slice(11,16):`0${i}:00`.slice(-5),title:String(pick(m,'foodName','food_name','title')??'Meal logged'),detail:`${pick(m,'mealType','meal_type')??'meal'} · ${Math.round(n(pick(m,'calories'),0))} kcal`}));},[diary]);
 return <AppShell title="Overview"><div className="border-b border-border pb-7"><div className="flex items-center justify-between gap-4"><Eyebrow>{new Date().toLocaleDateString('en-US',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase()}</Eyebrow><span className="numeric text-[9px] uppercase tracking-[.12em] text-muted-foreground">{loading?'Syncing…':error?'Backend unavailable':'Synced with WK Health backend'}</span></div><h1 className="display mt-2 text-5xl">A steady day, held together.</h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">{error?fallbackMood:'Live totals from your WK Health account, laid out the way the original design intended.'}</p></div>
 <div className="grid grid-cols-2 border-b border-border py-7 sm:grid-cols-4">{metrics.map(x=><div key={x[0]}><Eyebrow>{x[0]}</Eyebrow><div className="numeric mt-2 text-4xl">{x[1]} <small className="text-[9px] text-muted-foreground">{x[2]}</small></div></div>)}</div>
 <div className="mt-7 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div><Panel><Eyebrow>DAY SO FAR</Eyebrow>{(timeline??[]).map((x,i)=><div key={`${x.time}-${i}`} className="grid grid-cols-[65px_1fr] gap-5 border-b border-border py-5 last:border-0"><span className="numeric text-[10px] text-muted-foreground">{x.time}</span><div><b className="text-sm">{x.title}</b><p className="mt-1 text-xs text-muted-foreground">{x.detail}</p></div></div>)}{!timeline&&<p className="mt-4 text-[10px] text-muted-foreground">No diary entries yet today.</p>}</Panel><Panel className="mt-5"><Eyebrow>TARGETS · 4 ACTIVE</Eyebrow>{[['MOVEMENT','—'],['PROTEIN','—'],['HYDRATION','—'],['MINDFUL MINUTES','—']].map(x=><div key={x[0]} className="mt-4"><div className="flex justify-between text-[10px]"><span>{x[0]}</span><span>{x[1]}</span></div><div className="mt-1 h-[3px] bg-border"><i className="block h-full bg-foreground" style={{width:x[1] === '—' ? '0%' : x[1]}}/></div></div>)}</Panel></div><aside className="space-y-5"><Panel><Eyebrow>QUICK CAPTURE</Eyebrow><div className="mt-4 grid grid-cols-2"><a href="/scan" className="border-b border-r border-border p-5 text-sm">Scan meal</a><a href="/pedometer" className="border-b border-border p-5 text-sm">Movement</a><a href="/mood" className="border-r border-border p-5 text-sm">Mood check</a><a href="/music" className="p-5 text-sm">Sound</a></div></Panel><Panel className="bg-foreground text-background"><Eyebrow>NOW PLAYING · FOCUS</Eyebrow><h2 className="display mt-3 text-3xl">Now Playing</h2><p className="mt-1 text-xs opacity-60">No active track</p><div className="mt-8 flex h-14 items-end gap-1">{[18,32,25,44,38,52,26,48,35,55,22,40].map((h,i)=><i key={i} className="flex-1 bg-background opacity-25" style={{height:h}}/>)}</div></Panel><Panel><Eyebrow>RECOVERY</Eyebrow>{[['Sleep debt','—'],['HRV','—'],['Readiness','—']].map(x=><div key={x[0]} className="flex justify-between border-b border-border py-4 text-xs last:border-0"><span>{x[0]}</span><span className="numeric">{x[1]}</span></div>)}</Panel></aside></div></AppShell>}
