import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, BookOpen, Camera, Check, Clock3, Dumbbell, Footprints, HeartPulse, Images, Loader2, MessageSquare, Music, RefreshCw, Send, ShieldCheck, Sparkles, Users, Wallet, Download, Plus, Search, Bell, Smartphone } from "lucide-react";
import { AppShell } from "@/components/wk/shell";
import { Action, DataRow, Metric, Panel, PageHeader, ProgressIndicator, SectionHeader, StatusIndicator } from "@/components/wk/ui";
import { apiFetch, apiNlpAnalyze, apiMoodList, apiStatsToday, todayISO } from "@/lib/api";

type Json=Record<string,unknown>;
type PageConfig={eyebrow:string;title:string;description:string;icon:any;endpoint:string;accent:string;action?:string};
const config:Record<string,PageConfig>={
 diary:{eyebrow:"Today / Diary",title:"Your day, recorded clearly.",description:"อาหารและกิจกรรมของวันนี้จากบัญชีจริงของคุณ",icon:BookOpen,endpoint:"/api/diary?date=",accent:"อาหาร",action:"เพิ่มรายการ"},
 mood:{eyebrow:"Mind / Mood",title:"Check in with yourself.",description:"บันทึกอารมณ์และคำแนะนำที่เหมาะกับคุณ",icon:HeartPulse,endpoint:"/api/mood",accent:"อารมณ์",action:"เช็กอิน"},
 music:{eyebrow:"Environment / Sound",title:"Sound for the moment.",description:"เพลงและประวัติการฟังที่เชื่อมกับระบบสุขภาพ",icon:Music,endpoint:"/api/music",accent:"เพลง",action:"เล่นเพลง"},
 workout:{eyebrow:"Movement / Training",title:"Train with intention.",description:"แผนและประวัติการออกกำลังกายของคุณ",icon:Dumbbell,endpoint:"/api/workout",accent:"การออกกำลัง",action:"บันทึกการออกกำลัง"},
 budget:{eyebrow:"Life / Budget",title:"Health spending, made simple.",description:"ติดตามงบประมาณและค่าใช้จ่ายด้านสุขภาพ",icon:Wallet,endpoint:"/api/budget",accent:"งบประมาณ",action:"เพิ่มรายการ"},
 "device-connect":{eyebrow:"Intelligence / Devices",title:"Bring every signal together.",description:"อุปกรณ์และข้อมูลสุขภาพที่เชื่อมต่อกับ WK Health",icon:Smartphone,endpoint:"/api/body",accent:"อุปกรณ์",action:"เชื่อมต่ออุปกรณ์"},
 assistant:{eyebrow:"Intelligence / Assistant",title:"Your health, with an assistant.",description:"ถามเกี่ยวกับข้อมูลสุขภาพของคุณโดยใช้บริบทจากบัญชี",icon:MessageSquare,endpoint:"/api/assistant/history?limit=50",accent:"AI"},
 nlp:{eyebrow:"Intelligence / Language",title:"Turn words into health data.",description:"พิมพ์สิ่งที่กินหรือทำ แล้วให้ระบบแปลงเป็นข้อมูล",icon:Sparkles,endpoint:"/api/nlp",accent:"ภาษา",action:"วิเคราะห์"},
 pedometer:{eyebrow:"Movement / Pedometer",title:"Every step counts.",description:"ก้าว ระยะทาง และเวลาการเคลื่อนไหวของคุณ",icon:Footprints,endpoint:"/api/pedometer",accent:"ก้าว",action:"บันทึกก้าว"},
 gallery:{eyebrow:"Life / Gallery",title:"Your health memories.",description:"ภาพและบันทึกที่เก็บไว้ในบัญชีของคุณ",icon:Images,endpoint:"/api/gallery",accent:"แกลเลอรี",action:"อัปโหลด"},
 friends:{eyebrow:"Life / Friends",title:"Stay healthy together.",description:"เพื่อนและกิจกรรมทางสังคมในระบบสุขภาพ",icon:Users,endpoint:"/api/friends",accent:"เพื่อน",action:"เพิ่มเพื่อน"},
 export:{eyebrow:"Account / Export",title:"Your data belongs to you.",description:"จัดการการส่งออกข้อมูลสุขภาพของคุณ",icon:Download,endpoint:"/api/export",accent:"ส่งออก",action:"สร้างไฟล์"},
 profile:{eyebrow:"Account / Profile",title:"Make the system yours.",description:"ข้อมูลส่วนตัว เป้าหมาย และค่าตั้งต้นของบัญชี",icon:ShieldCheck,endpoint:"/api/auth/me",accent:"โปรไฟล์",action:"แก้ไขโปรไฟล์"},
 notifications:{eyebrow:"Account / Notifications",title:"Only what matters.",description:"การแจ้งเตือนและกิจกรรมล่าสุดของบัญชี",icon:Bell,endpoint:"/api/notifications",accent:"แจ้งเตือน",action:"ทำเครื่องหมายอ่านแล้ว"},
};
function rows(value:unknown):Json[]{if(Array.isArray(value))return value.filter((x):x is Json=>!!x&&typeof x==="object");if(value&&typeof value==="object"){const o=value as Json;for(const k of ["items","data","rows","entries","messages","notifications","friends","workouts","records","results","history"]){if(Array.isArray(o[k]))return rows(o[k]);}return [o];}return []}
function text(v:unknown){if(v===null||v===undefined||v==="")return "—";if(typeof v==="string"||typeof v==="number"||typeof v==="boolean")return String(v);return "ข้อมูล"}
function label(r:Json,i:number){return text(r.name??r.title??r.food_name??r.foodName??r.label??r.type??r.role??`รายการ ${i+1}`)}
function value(r:Json){return text(r.value??r.status??r.calories??r.kcal??r.steps??r.created_at??r.createdAt??r.date??"บันทึกแล้ว")}

export function VisionPage({page}:{page:string}){
 const c=config[page]??{eyebrow:"WK Health",title:"Your health workspace.",description:"ข้อมูลจากระบบ WK Health",icon:Activity,endpoint:"/api/stats/today",accent:"ระบบ"};
 const [data,setData]=useState<unknown>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[input,setInput]=useState("");const[reply,setReply]=useState("");const[sending,setSending]=useState(false);const[query,setQuery]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const ep=c.endpoint.endsWith("=")?`${c.endpoint}${encodeURIComponent(todayISO())}`:c.endpoint;setData(await apiFetch(ep));}catch(e){setError(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ");setData(null)}finally{setLoading(false)}},[c.endpoint]);
 useEffect(()=>{void load()},[load]);
 const list=useMemo(()=>rows(data).filter(r=>{const q=query.trim().toLowerCase();return !q||JSON.stringify(r).toLowerCase().includes(q)}),[data,query]);
 const icon=c.icon;
 async function send(){if(!input.trim())return;setSending(true);setError("");try{if(page==="assistant"){const r=await apiFetch<Json>("/api/assistant/chat",{method:"POST",body:{message:input.trim()}});setReply(text(r.reply??r.message??r.data));await load()}else if(page==="nlp"){const r=await apiNlpAnalyze(input.trim());setReply(r.length?`พบ ${r.length} รายการ: ${r.map(x=>`${x.name} ${x.kcal} kcal`).join(" · ")}`:"ไม่พบรายการที่ชัดเจน")}else{setReply("พร้อมบันทึกผ่านระบบแล้ว")}setInput("")}catch(e){setError(e instanceof Error?e.message:"ดำเนินการไม่สำเร็จ")}finally{setSending(false)}}
 return <AppShell title={c.eyebrow.split(" / ").pop()}><PageHeader eyebrow={c.eyebrow} title={c.title} description={c.description} actions={<div className="flex items-center gap-2"><StatusIndicator label={loading?"Syncing":"Live"} state={loading?"live":"idle"}/><Action icon={RefreshCw} size="sm" onClick={()=>void load()} disabled={loading} aria-label="Refresh"/></div>}/>
 <div className="grid gap-6 py-8 sm:grid-cols-2 xl:grid-cols-4"><Panel><Metric label="สถานะระบบ" value={error?"Error":"Live"} size="lg"/><p className="mt-3 text-xs text-muted-foreground">Backend เชื่อมต่อบัญชีปัจจุบัน</p></Panel><Panel><Metric label="รายการ" value={loading?"—":String(list.length)} size="lg"/><p className="mt-3 text-xs text-muted-foreground">ข้อมูลที่โหลดได้</p></Panel><Panel><Metric label="โมดูล" value={c.accent} size="lg"/><p className="mt-3 text-xs text-muted-foreground">ฟีเจอร์เฉพาะหน้านี้</p></Panel><Panel><Metric label="วันนี้" value={todayISO()} size="lg"/><p className="mt-3 text-xs text-muted-foreground">วันที่ของบัญชี</p></Panel></div>
 <div className="grid gap-8 lg:grid-cols-[1.45fr_.55fr]"><div className="space-y-8"><Panel tone="ink" className="min-h-[210px] border-transparent"><div className="flex h-full flex-col justify-between gap-10"><div className="flex items-center justify-between"><icon className="size-5" strokeWidth={1.4}/><span className="num text-[10px] opacity-60">{c.accent.toUpperCase()} / LIVE</span></div><div><p className="display text-3xl sm:text-4xl">ข้อมูลของคุณ อยู่ตรงนี้.</p><p className="mt-3 max-w-2xl text-sm leading-6 opacity-65">หน้านี้ใช้ข้อมูลจาก backend จริง และแสดงสถานะการเชื่อมต่อแบบสด ไม่มีตัวเลขสุขภาพจำลอง</p></div></div></Panel>
 {(page==="assistant"||page==="nlp")&&<Panel title={page==="assistant"?"ถาม WK Health":"วิเคราะห์ข้อความ"}><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder={page==="assistant"?"เช่น วันนี้ควรกินอะไรเพิ่ม…":"เช่น ข้าว 1 จาน ไข่ 2 ฟอง…"} className="min-w-0 flex-1 border-b border-border bg-transparent px-1 py-3 text-sm outline-none focus:border-foreground"/><Action icon={sending?Loader2:Send} variant="solid" onClick={()=>void send()} disabled={sending||!input.trim()}>{sending?"กำลังประมวลผล":"ส่ง"}</Action></div>{reply&&<div className="mt-5 border-l-2 border-signal pl-4 text-sm leading-6">{reply}</div>}</Panel>}
 {error?<Panel><div className="border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive"><p className="font-medium">เชื่อมต่อข้อมูลไม่สำเร็จ</p><p className="mt-1 text-xs opacity-80">{error}</p></div></Panel>:<div><SectionHeader title="ข้อมูลล่าสุด" meta={`${list.length} รายการ`} actions={<div className="relative"><Search className="absolute left-2 top-2.5 size-3.5 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา" className="w-36 border-b border-border bg-transparent py-2 pl-7 text-xs outline-none"/></div>}/><Panel bare className="px-5 py-2">{loading?<div className="flex items-center gap-3 py-10 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>กำลังซิงก์ข้อมูล…</div>:list.length===0?<div className="py-12 text-center"><icon className="mx-auto size-7 text-muted-foreground"/><p className="mt-4 text-sm">ยังไม่มีข้อมูล</p><p className="mt-1 text-xs text-muted-foreground">เริ่มใช้งานฟีเจอร์นี้ แล้วข้อมูลจะปรากฏที่นี่</p></div>:list.slice(0,25).map((r,i)=><DataRow key={i} label={label(r,i)} value={value(r)} meta={text(r.date??r.time??r.created_at??r.createdAt??"")} icon={i===0?<Check/>:undefined}/>)}</Panel></div>}</div>
 <div className="space-y-8"><Panel title="การทำงาน"><div className="grid gap-2">{c.action&&<Action icon={Plus} variant="outline" onClick={()=>{setInput("");setReply(c.action+" พร้อมใช้งาน — ใช้ฟีเจอร์หลักของหน้านี้เพื่อบันทึกข้อมูลจริง")}}>{c.action}</Action>}<Action icon={RefreshCw} variant="ghost" onClick={()=>void load()} disabled={loading}>ซิงก์ข้อมูลใหม่</Action></div></Panel><Panel title="ภาพรวม"><Metric label="Records" value={loading?"—":String(list.length)} size="xl"/><div className="mt-6"><ProgressIndicator label="Backend connection" right={error?"0%":"100%"} value={error?0:100}/><DataRow label="Endpoint" value={c.endpoint.replace("/api/","")} /><DataRow label="Last sync" value={loading?"กำลังซิงก์":new Date().toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}/></div></Panel><Panel className="border-border"><div className="flex items-start gap-3"><icon className="mt-0.5 size-4 text-muted-foreground"/><div><p className="text-sm font-medium">WK Health OS</p><p className="mt-1 text-xs leading-5 text-muted-foreground">ทุกหน้าถูกผูกกับบัญชีเดียวกันและใช้ session token เดียวกับระบบหลัก</p></div></div></Panel></div></div></AppShell>
}
