/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as DeviceConnectRouteImport } from './routes/device-connect'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as ExportRouteImport } from './routes/export'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InsightRouteImport } from './routes/insight'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NlpRouteImport } from './routes/nlp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PedometerRouteImport } from './routes/pedometer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as WorkoutRouteImport } from './routes/workout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceConnectRoute = DeviceConnectRouteImport.update({
  id: '/device-connect',
  path: '/device-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightRoute = InsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NlpRoute = NlpRouteImport.update({
  id: '/nlp',
  path: '/nlp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PedometerRoute = PedometerRouteImport.update({
  id: '/pedometer',
  path: '/pedometer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/device-connect': typeof DeviceConnectRoute
  '/diary': typeof DiaryRoute
  '/export': typeof ExportRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/insight': typeof InsightRoute
  '/mood': typeof MoodRoute
  '/music': typeof MusicRoute
  '/nlp': typeof NlpRoute
  '/notifications': typeof NotificationsRoute
  '/pedometer': typeof PedometerRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/stats': typeof StatsRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/device-connect': typeof DeviceConnectRoute
  '/diary': typeof DiaryRoute
  '/export': typeof ExportRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/insight': typeof InsightRoute
  '/mood': typeof MoodRoute
  '/music': typeof MusicRoute
  '/nlp': typeof NlpRoute
  '/notifications': typeof NotificationsRoute
  '/pedometer': typeof PedometerRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/stats': typeof StatsRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/device-connect': typeof DeviceConnectRoute
  '/diary': typeof DiaryRoute
  '/export': typeof ExportRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/insight': typeof InsightRoute
  '/mood': typeof MoodRoute
  '/music': typeof MusicRoute
  '/nlp': typeof NlpRoute
  '/notifications': typeof NotificationsRoute
  '/pedometer': typeof PedometerRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/stats': typeof StatsRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/budget'
    | '/device-connect'
    | '/diary'
    | '/export'
    | '/friends'
    | '/gallery'
    | '/insight'
    | '/mood'
    | '/music'
    | '/nlp'
    | '/notifications'
    | '/pedometer'
    | '/profile'
    | '/scan'
    | '/stats'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/budget'
    | '/device-connect'
    | '/diary'
    | '/export'
    | '/friends'
    | '/gallery'
    | '/insight'
    | '/mood'
    | '/music'
    | '/nlp'
    | '/notifications'
    | '/pedometer'
    | '/profile'
    | '/scan'
    | '/stats'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/budget'
    | '/device-connect'
    | '/diary'
    | '/export'
    | '/friends'
    | '/gallery'
    | '/insight'
    | '/mood'
    | '/music'
    | '/nlp'
    | '/notifications'
    | '/pedometer'
    | '/profile'
    | '/scan'
    | '/stats'
    | '/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BudgetRoute: typeof BudgetRoute
  DeviceConnectRoute: typeof DeviceConnectRoute
  DiaryRoute: typeof DiaryRoute
  ExportRoute: typeof ExportRoute
  FriendsRoute: typeof FriendsRoute
  GalleryRoute: typeof GalleryRoute
  InsightRoute: typeof InsightRoute
  MoodRoute: typeof MoodRoute
  MusicRoute: typeof MusicRoute
  NlpRoute: typeof NlpRoute
  NotificationsRoute: typeof NotificationsRoute
  PedometerRoute: typeof PedometerRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  StatsRoute: typeof StatsRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-connect': {
      id: '/device-connect'
      path: '/device-connect'
      fullPath: '/device-connect'
      preLoaderRoute: typeof DeviceConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight': {
      id: '/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof InsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nlp': {
      id: '/nlp'
      path: '/nlp'
      fullPath: '/nlp'
      preLoaderRoute: typeof NlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedometer': {
      id: '/pedometer'
      path: '/pedometer'
      fullPath: '/pedometer'
      preLoaderRoute: typeof PedometerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BudgetRoute: BudgetRoute,
  DeviceConnectRoute: DeviceConnectRoute,
  DiaryRoute: DiaryRoute,
  ExportRoute: ExportRoute,
  FriendsRoute: FriendsRoute,
  GalleryRoute: GalleryRoute,
  InsightRoute: InsightRoute,
  MoodRoute: MoodRoute,
  MusicRoute: MusicRoute,
  NlpRoute: NlpRoute,
  NotificationsRoute: NotificationsRoute,
  PedometerRoute: PedometerRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  StatsRoute: StatsRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
